**** New Publication - An Inverse Mapping Approach for Process Systems Engineering Using Automatic Differentiation and the Implicit Function Theorem
:PROPERTIES:
:categories: news,publication
:date:     2023/04/25 13:43:14
:updated:  2023/04/25 13:43:14
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2023/04/25/New-Publication---An-Inverse-Mapping-Approach-for-Process-Systems-Engineering-Using-Automatic-Differentiation-and-the-Implicit-Function-Theorem.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2023/04/25/New-Publication---An-Inverse-Mapping-Approach-for-Process-Systems-Engineering-Using-Automatic-Differentiation-and-the-Implicit-Function-Theorem/index.html
:END:

Solving inverse problems, where we know what outputs we want from a model and seek the inputs that provide them, is a difficult task. A conventional approach to this problem is to use a nonlinear program (NLP) solver to iteratively find the inputs for a specific output. If you seek a desired output space, then you must solve the NLP many times to map out the corresponding input space. This is often expensive, and tedious to perform. In this work, we demonstrate a new approach to solving this problem that avoids the NLP formulation, and is faster. The idea is simple; we compute a system of differential equations that maps how the input space changes with the output space. Then from a single known point we can integrate a path in the output space to automatically trace the corresponding path in the input space! We compute the system of differential equations using automatic differentiation, and the implicit derivative theorem. We show two examples of this using a steady state continuously stirred tank reactor, which is a set of nonlinear algebraic equations that define the output space from input variables, and another plug flow reactor where the output space is defined by a set of differential equations that must be numerically integrated. In both cases we use automatic differentiation to define the system of ODEs that relate outputs and inputs, and show that the path integration method developed here is as accurate and faster than even the best NLP approach. The idea in this paper is general and applicable to many other systems, not just chemical reactors.

#+BEGIN_SRC bibtex
@article{alves-2023,
  author =	 {Alves, Victor and Kitchin, John R. and Lima, Fernando V.},
  title =	 {An inverse mapping approach for process systems engineering
                  using automatic differentiation and the implicit function
                  theorem},
  journal =	 {AIChE Journal},
  year =	 2023,
  volume =	 {n/a},
  number =	 {n/a},
  pages =	 {e18119},
  keywords =	 {automatic differentiation, implicit function theorem, inverse
                  mapping, inverse problems, process systems engineering},
  doi =		 {10.1002/aic.18119},
  url =
                  {https://aiche.onlinelibrary.wiley.com/doi/abs/10.1002/aic.18119}
}
#+END_SRC

[[altmetric:10.1002/aic.18119]]

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/UAIUSr4TzBk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+END_EXPORT
