* New publication - Identifying limitations in screening high-throughput photocatalytic bimetallic nanoparticles with machine-learned hydrogen adsorptions
:PROPERTIES:
:categories: news,publication
:date:     2022/09/29 17:23:34
:updated:  2022/09/29 17:23:34
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2022/09/29/New-publication---Identifying-limitations-in-screening-high-throughput-photocatalytic-bimetallic-nanoparticles-with-machine-learned-hydrogen-adsorptions.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2022/09/29/New-publication---Identifying-limitations-in-screening-high-throughput-photocatalytic-bimetallic-nanoparticles-with-machine-learned-hydrogen-adsorptions/index.html
:END:

Hydrogen adsorption energies have long been used in screening to identify promising hydrogen evolution catalysts. In this work we combine a high-throughput experimental study of 5300 different bimetallic catalysts with a high-throughput computational screen of 16M adsorption energies to see how well adsorption energies work for this purpose. We developed a workflow to combine these data sets that accounts for surface stability and adsorption site distributions on alloy surfaces. We find that thermodynamically favorable adsorption energies are necessary to observe high activity, but they are not sufficient, and do not always lead to high activity.  

#+BEGIN_SRC bibtex
@article{broderick-2022-ident-limit,
  author = {Kirby Broderick and Eric Lopato and Brook Wander and Stefan Bernhard and John Kitchin and Zachary Ulissi},
  title = {Identifying Limitations in Screening High-Throughput Photocatalytic Bimetallic Nanoparticles With Machine-Learned Hydrogen Adsorptions},
  journal = {Applied Catalysis B: Environmental},
  volume = {nil},
  number = {nil},
  pages = {121959},
  year = {2022},
  doi = {10.1016/j.apcatb.2022.121959},
  url = {http://dx.doi.org/10.1016/j.apcatb.2022.121959},
  DATE_ADDED = {Thu Sep 22 07:46:56 2022},
}
#+END_SRC

altmetric:10.1016/j.apcatb.2022.12195
9
