* New publication in Catalysis Today
  :PROPERTIES:
  :categories: news, publication
  :date:     2018/04/01 19:07:10
  :updated:  2018/04/01 19:07:10
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2018/04/01/New-publication-in-Catalysis-Today.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2018/04/01/New-publication-in-Catalysis-Today/index.html
  :END:

In this paper we continue our exploration of using high-dimensional neural networks (NN) to model metal surface properties. Our first work started with modeling Au in a variety of structures using ReaxFF and a NN cite:boes-2016-neural-networ. We then modeled atomic oxygen adsorbates on a Pd (111) surface cite:boes-2017-neural-networ, and segregation of an Au-Pd alloy surface cite:boes-2017-model-segreg. Our goal throughout this work has been to systematically build up complexity in the systems we are modeling, and to explore the limitations of these potentials for modeling surfaces. This current work happened in parallel with those works, and focused on modeling Pd adatom diffusion on Pd(111) surfaces. We show another example of how to train a neural network, and then to use it model the temperature dependent diffusion of adatoms on a metal surface using molecular dynamics and Arrhenius analysis.

#+BEGIN_SRC bibtex
@article{gao-2018-model-pallad,
  author =	 {Tianyu Gao and John R. Kitchin},
  title =	 {Modeling Palladium Surfaces With Density Functional Theory,
                  Neural Networks and Molecular Dynamics},
  journal =	 {Catalysis Today},
  year =	 2018,
  doi =		 {10.1016/j.cattod.2018.03.045},
  url =		 {https://doi.org/10.1016/j.cattod.2018.03.045},
  DATE_ADDED =	 {Sun Apr 1 18:47:55 2018},
}
#+END_SRC

altmetric:10.1016/j.cattod.2018.03.045

bibliography:~/Dropbox/bibliography/references.bib