* New publication "SingleNN: Modified Behler–Parrinello Neural Network with Shared Weights for Atomistic Simulations with Transferability"
  :PROPERTIES:
  :date: 2020/07/09
  :categories: news
  :updated:  2021/06/21 11:31:41
  :org-url:  https://kitchingroup.cheme.cmu.edu/org/2020/07/09/New-publication-"SingleNN:-Modified-Behler–Parrinello-Neural-Network-with-Shared-Weights-for-Atomistic-Simulations-with-Transferability".org
  :permalink: https://kitchingroup.cheme.cmu.edu/blog/2020/07/09/New-publication-"SingleNN:-Modified-Behler–Parrinello-Neural-Network-with-Shared-Weights-for-Atomistic-Simulations-with-Transferability"/index.html
  :END:

Many machine learned potentials work by creating a numeric fingerprint that represents the local atomic environment around an atom, and then "machine learning" a function that computes the atomic energy for that atom. The total energy of an atomic configuration is then simply the sum of the atomic energies, and the forces are simply the derivative of that energy with respect to the atomic positions. In the Behler-Parrinello formulation, each element gets its own neural network for these calculations. In this work, we show that a single neural network with multiple outputs can be used instead. This means that all the elements share the weights in the neural network, and the atomic energy of each element is linearly proportional to the output of the last hidden layer. This has some benefits for transferability and suggests that there is a common nonlinear dimensional transform of the numeric fingerprints for the elements in this study.


#+BEGIN_SRC bibtex
@article{liu-2020-singl,
  author =	 {Mingjie Liu and John R. Kitchin},
  title =	 {Singlenn: Modified Behler-Parrinello Neural Network With
                  Shared Weights for Atomistic Simulations With Transferability},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 124,
  number =	 32,
  pages =	 {17811-17818},
  year =	 2020,
  doi =		 {10.1021/acs.jpcc.0c04225},
  url =		 {https://doi.org/10.1021/acs.jpcc.0c04225},
}
#+END_SRC
