* New publication - Structure Sensitive Reaction Kinetics of Chiral Molecules on Intrinsically Chiral Surfaces
DEADLINE: <2025-01-28 Tue>
:PROPERTIES:
:categories: news,publication
:date:     2025/01/27 20:42:00
:updated:  2025/01/28 12:01:40
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/01/27/New-publication---Structure-Sensitive-Reaction-Kinetics-of-Chiral-Molecules-on-Intrinsically-Chiral-Surfaces.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/01/27/New-publication---Structure-Sensitive-Reaction-Kinetics-of-Chiral-Molecules-on-Intrinsically-Chiral-Surfaces/index.html
:END:

We recently published this paper in The Journal of Physical Chemistry C exploring how the atomic structure of chiral copper surfaces influences the reaction kinetics of tartaric acid, a chiral molecule. Researchers developed two models—one using generalized coordination numbers (GCN) and another based on chiral cubic harmonic functions—to predict enantiospecificity, the ability of a surface to distinguish between two mirror-image molecules. Using curved copper surfaces, we measured reaction kinetics across hundreds of orientations and identified key surface structures that maximize enantiospecificity. The findings not only provide insights into the relationship between surface geometry and molecular interactions but also pave the way for designing highly selective catalysts, with potential applications in producing enantiopure pharmaceuticals and advancing green chemistry.


#+BEGIN_SRC bibtex
@article{abdelmaqsoud-2024-struc-sensit,
  author =	 {Kareem Abdelmaqsoud and Michael Radetic and Carlos
                  Fern{\'a}ndez-Cab{\'a}n and Michael Widom and John R. Kitchin
                  and Andrew J. Gellman},
  title =	 {Structure Sensitive Reaction Kinetics of Chiral Molecules on
                  Intrinsically Chiral Surfaces},
  journal =	 {The Journal of Physical Chemistry C},
  volume = 	 {128},
  number = 	 {33},
  pages = 	 {13879-13887},
  year =	 2024,
  doi =		 {10.1021/acs.jpcc.4c04224},
  url =		 {http://dx.doi.org/10.1021/acs.jpcc.4c04224},
  DATE_ADDED =	 {Sat Aug 17 09:45:55 2024},
}
#+END_SRC

altmetric:10.1021/acs.jpcc.4c04224

#+BEGIN_EXPORT html
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/5MpBldx9WafwZO8movWxWS?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
#+END_EXPORT
