* Four new publications!
  :PROPERTIES:
  :date:     2011/03/17 09:00:00
  :categories: news
  :updated:  2013/02/28 10:35:57
  :END:

We recently published papers in the areas of sufur tolerance, oxygen evolution, adsorption and oxide synthesis.

29.  N. Inoglu, and J.R. Kitchin, Identification of sulfur tolerant bimetallic surfaces using DFT parameterized models and atomistic thermodynamics, ACS Catalysis, 1, 399-407 (2011). link.


28.  Isabela C. Man, Hai-Yan Su, Federico Calle-Vallejo, Heine A. Hansen, Jose I. Martinez, Nilay G. Inoglu,  John Kitchin, Thomas F. Jaramillo, Jens K. Norskov, Jan Rossmeisl*, Universality in Oxygen Evolution Electro-Catalysis on Oxide Surfaces, accepted ChemCatChem (Jan 2011).

 
27.  Spencer D. Miller, Nilay Inoglu, and John R. Kitchin*, Configurational correlations in the coverage dependent adsorption energies of oxygen atoms on late transition metal fcc (111) surfaces, accepted J. Chemical Physics, 134, 104709 (2011). link.

 

26.  R. Chao, J. R. Kitchin, K. Gerdes, E. M. Sabolsky, and P. A. Salvador, Preparation of Mesoporous La0.8Sr0.2MnO3 Infiltrated Coatings in Porous SOFC Cathodes Using Evaporation-Induced Self-Assembly Methods, ECS Transactions (Accepted January 2011).