* New publication - Accessing Numerical Energy Hessians With Graph Neural Network Potentials and Their Application in Heterogeneous Catalysis
:PROPERTIES:
:categories: news,publication
:date:     2025/02/11 07:48:57
:updated:  2025/02/11 07:48:57
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/11/New-publication---Accessing-Numerical-Energy-Hessians-With-Graph-Neural-Network-Potentials-and-Their-Application-in-Heterogeneous-Catalysis.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/11/New-publication---Accessing-Numerical-Energy-Hessians-With-Graph-Neural-Network-Potentials-and-Their-Application-in-Heterogeneous-Catalysis/index.html
:END:


The ability to calculate energy Hessians has long been a cornerstone of understanding chemical reactions, but traditional methods like density functional theory (DFT) are computationally expensive. In this breakthrough study, researchers demonstrate how pretrained Graph Neural Network (GNN) models from the Open Catalyst Project (OCP) can effectively determine potential energy Hessians with remarkable accuracy. With an MAE of just 58 cm⁻¹, these machine-learned potentials enable efficient calculation of Gibbs free energy corrections, overcoming limitations of the harmonic approximation by incorporating translational entropy effects. Even in transition state searches, the models significantly improve convergence rates, making computational catalysis more accessible than ever. This research paves the way for AI-powered simulations to accelerate catalyst discovery and optimize reaction pathways at a fraction of the cost of traditional methods.

#+BEGIN_SRC bibtex
@article{wander-2025-acces-numer,
  author =	 {Wander, Brook and Musielewicz, Joseph and Cheula, Raffaele and
                  Kitchin, John R.},
  title =	 {Accessing Numerical Energy Hessians With Graph Neural Network
                  Potentials and Their Application in Heterogeneous Catalysis},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 0,
  number =	 0,
  pages =	 {null},
  year =	 2025,
  doi =		 {10.1021/acs.jpcc.4c07477},
  URL =		 {https://doi.org/10.1021/acs.jpcc.4c07477},
  eprint =	 { https://doi.org/10.1021/acs.jpcc.4c07477 },
}
#+END_SRC


altmetric:10.1021/acs.jpcc.4c07477

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35236620/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
