* New publication in Molecular Simulation
  :PROPERTIES:
  :categories: news, publication
  :date:     2017/02/01 19:22:46
  :updated:  2017/02/01 19:22:46
  :END:

Molecules interact with each other when they adsorb on surfaces and these interactions are coverage dependent. Modeling these interactions is a challenge though, because there are many configurations of adsorbates on the surface, and the surface changes due to the interactions. To mitigate these challenges, one often simplifies the model, e.g. by using a cluster expansion or lattice gas Hamiltonian. These approaches have their own limitations though, and are not that useful for modeling dynamic processes like diffusion. Using molecular potentials enables the dynamic simulations, but not at the same level of accuracy as density functional theory. In this work we use density functional theory to train a neural network, and then use the neural network to model coverage-dependent adsorption isotherms and the dynamics of oxygen diffusion on a Pd(111) surface. We show the neural network can capture the onset of surface oxidation, and that the simulation results have comparable accuracy to the DFT calculations it was trained from.

#+BEGIN_SRC bibtex
@article{boes-2017-neural-networ,
  author =	 {Jacob R. Boes and John R. Kitchin},
  title =	 {Neural Network Predictions of Oxygen Interactions on a Dynamic
                  Pd Surface},
  journal =	 {Molecular Simulation},
  pages =	 {1-9},
  year =	 2017,
  doi =		 {10.1080/08927022.2016.1274984},
  url =		 {https://doi.org/10.1080/08927022.2016.1274984},
  keywords =	 {CBET-1506770},
}
#+END_SRC

altmetric:10.1080/08927022.2016.1274984
