[project]
name = "blogofile-jkitchin-github-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "blogofile",
]

[tool.uv.sources]
blogofile = { path = "../python/blogofile", editable = true }
