#+TITLE: Research topics in the Kitchin Group
#+BEGIN_HTML
<%inherit file="_templates/site.mako" />
#+END_HTML

We describe here the main research areas the Kitchin Group has been active in. For each area we briefly describe what we have done, with reference to most of the publications that resulted from the work.

For a complete listing of our publications see [[./publications.html]].

* Data sharing and functional scientific documents
We are huge proponents of using org-mode to write scientific documents. This has enabled our group to develop novel data sharing strategies cite:kitchin-2015-examp,kitchin-2015-data-surfac-scien and increase our productivity significantly.

* Alloy catalysis
Alloy catalysts frequently do not have the same reactivity as the parent metals. We use density functional theory calculations to understand how the electronic structure of the alloy differs from the parent metals, and how those differences lead to different reactivities. We are especially interested in modeling heterogeneous site distributions cite:boes-2015-estim-bulk, modeling XPS spectra of alloys cite:boes-2015-core-cu, and the limit of single atom alloys cite:tierney-2009-hydrog-dissoc.

We have used density functional theory to identify S-tolerant alloys cite:inoglu-2011-ident-sulfur. Our current work will develop a new understanding of selectivity in acetylene hydrogenation.


* CO_{2} Capture
CO_{2} capture remains an important tool in considering how to mitigate the role of fossil energy on climate change cite:rubin-2012. We have investigated the use of supported amines cite:alesi-2010-co2-adsor, and a commercially available ion exchange resin as a CO_{2} capture sorbent cite:alesi-2012-evaluat-primar. We have shown that supported amines are poisoned by SO_{2}, but may they may be partially regenerated in some cases cite:hallenbeck-2013-effec-o2.


We have used density functional theory calculations to model amine-CO_{2} reactions cite:lee-2012-chemic-molec,mao-2013-inter, as well as process modeling to show that different process conditions are required to optimize a capture process for different solvents cite:lee-2013-compar-co2. We have considered ionic liquids as potential CO_{2} capture solvents cite:thompson-2014-co2-react.

We also have developed a high pressure silica capillary cell for in situ Raman measurements of CO_{2} solubility in solvents for precombustion capture applications. Our current interests include developing a microfluidic device for measuring CO_{2} absorption rates in amine-based solvents. We collaborate with the [[http://annalab.org/][the Anna group]] on this.

We previously explored the electrochemical separation of CO_{2} from flue gas cite:landon-2010-elect-concen,pennline-2010-separ-co2.


PhD Anita Lee: cite:lee-2013-multi-scale

PhD Rich Alesi: cite:walesi-2012-amine-based-sorben

* Metal oxide reactivity

We are generally interested in understanding the reactivity of metal oxides towards oxygen and fuels. We use computational tools to model the electronic structure and reactivity of metal oxides for applications in water splitting and chemical looping.

We derived a number of heuristic rules that describe the reactivity of perovskites cite:akhade-2011-effec,akhade-2012-effec. These principles were expanded into a concept of outer electrons that was used to describe the reactivity of a broad range of oxides cite:calle-vallejo-2013-number. These observations have been found to be robust across a broad range of assumptions in the models used, although some care must be taken in a few cases cite:curnan-2014-effec-concen. We have found novel relationships between oxide electronic structure and reactivity for oxides with rocksalt structures cite:xu-2014-relat.

We did some work in infiltrating solid oxide fuel cell electrodes with
electrocatalysts to improve their activity
cite:chao-2011-prepar-mesop,chao-2012-struc-relat.

An outstanding challenge in modeling oxides is the highly correlated electrons especially in the 3d orbitals of transition metals. We have expanded an approach to use a linear response method to compute U, making a nearly predictive, first-principles method for computing oxide formation energies with pretty good accuracy cite:xu-2015-accur-u.

One new direction we have taken is to identify oxide polymorphs that may be grown as epitaxial thin films cite:mehta-2014-ident-poten.

PhD Robin Chao: cite:chao-2012-improv-solid

* Oxygen evolution electrocatalysis

We are using Raman spectroscopy to probe the oxide/electrolyte interface under oxygen evolution conditions. We have focused most of our work on Ni-oxide containing materials, which are highly active when promoted by Fe impurities cite:landon-2012-spect-charac,michael-2015-alkal-elect. We have also examined Fe-containing molecular electrocatalysts
cite:demeter-2014-elect-oxygen.

We have used density functional theory to show that there are correlations in the reactions of the oxygen evolution reaction that likely limit the activity of oxide-based electrocatalysts cite:man-2011-univer-oxygen. These observations are robust, even with advanced computational methods such as the linear response DFT+U methods cite:xu-2015-linear-respon.

PhD James Landon: cite:landon-2011-elect-oxygen-produc

PhD Ethan Demeter: cite:demeter-2013-promot-base

* Coverage dependent adsorption
Our earliest work was in modeling the coverage dependent adsorption energies of atomic adsorbates on late transition metal surfaces. We showed that there exist strong configurational correlations for many adsorbates on Pd(111) cite:kitchin-2009-correl-pd, and for oxygen on late transition metal surfaces cite:miller-2009-relat-au,miller-2011-config. These principles were generalized in a simple physical model cite:inoglu-2010-simpl that showed the origin of the coverage dependence was an adsorbate-induced modification of the surface electronic structure. We wrote a review book chapter on this topic cite:miller-2012-cover. We demonstrated that DFT can be used to interpret the coverage dependent desorption behavior of oxygen on Pt(111) cite:miller-2014-simul-temper.  Finally, we showed the generality of configurational correlations across many surfaces and for many adsorbates, demonstrating that geometric similarity is a requirement for correlation cite:xu-2014-probin-cover.

PhD Spencer Miller: cite:miller-2011-towar-under

PhD Nilay Inoglu: cite:inoglu-2012-desig-sulfur

bibliography:../Dropbox/bibliography/references.bib


* build					:noexport:
#+BEGIN_SRC emacs-lisp
(org-html-export-to-html nil nil nil t nil)
(rename-file "research.html" "research.html.mako" t)
#+END_SRC

#+RESULTS:
