#+TITLE: 
#+BEGIN_HTML
<%inherit file="_templates/site.mako" />

<h1><font color="#4863A0">sci</font>max - bringing plain text to life</h1>
#+END_HTML

[[https://github.com/jkitchin/scimax][Scimax]] is a set of open-source software tools to integrate narrative text with data, code, figures, equations, tables and citations. Scimax brings plain text to life by making it functional and interactive. With scimax you can embed and run code directly in your documents, and capture the output in your document. You can embed data in your documents with narrative text that explains what it is, and then use the document as a data source for analysis. You can easily convert documents written with scimax to HTML, LaTeX, PDF, even MS Word.

Scimax builds on Emacs, [[http://orgmode.org][org-mode]] and programming tools to provide a rich authoring environment for writing, programming, research and teaching.

* Scientific research
We use scimax as an electronic notebook in all our research. scimax lets us integrate narrative text with citations about what we are trying to do with data and code to perform analysis. scimax integrates project/task management tools and distributed version control tools to enable collaboration in our group.

* Scientific publishing
We write all our scientific manuscripts using scimax. After the documents are written, we use scimax to convert them to the format required by publishers (usually LaTeX). These manuscripts and their supporting information files contain all the data, code and analysis we used in the papers so others can see what we did, and even reuse the data/code.

  - cite:hallenbeck-2013-effec-o2 Experimental
  - cite:miller-2014-simul-temper Combined experimental and computational
  - cite:curnan-2014-effec-concen Computational
  - cite:xu-2014-probin-cover Computational
  - cite:xu-2014-relat Computational
  - cite:mehta-2015-ident-poten Computational
  - cite:boes-2015-estim-bulk Combined experimental and computational
  - cite:boes-2015-estim-bulk-si
  - cite:kitchin-2015-examp Perspective
  - cite:kitchin-2015-data-surfac-scien Perspective 
  - cite:xu-2015-accur-u Computational
  - cite:xu-2015-linear-respon Computational
  - cite:xu-2015-relat Computational
  - cite:xu-2015-tunin-oxide Computational
  - cite:kitchin-2016-autom-data Publishing

We have written two large electronic books using scimax. These books integrate narrative discussion with code, data, equations, figures, tables and citations. In the native format, they are interactive and functional.
  - [[http://kitchingroup.cheme.cmu.edu/pycse][Python computation in science and engineering]]
  - [[http://kitchingroup.cheme.cmu.edu/dft-book][Modeling materials with density functional theory]]

Finally, this blog is written using scimax.
  - blog http://kitchingroup.cheme.cmu.edu

* Build interactive apps
We have built two significant apps on top of the tools in scimax.

** org-ref
org-ref is a bibliography management tool similar to Endnote. It provides tools to insert citations and bibliographies in documents. The citations are hyper-functional, and connect your documents to external search engines, locally stored pdf files, etc.

** contacts
This is a contact manager for scimax. It allows you to quickly find contacts, email them, call them, etc. It can mine your email database for contact information

* Teaching
[[https://github.com/jkitchin/techela][techela]] is a tool based on scimax that acts like a content management system for teaching a class. It provides a framework to distribute, collect, grade and return assignments and course materials. techela provides an integrated gradebook, and communication tools.



bibliography:~/Dropbox/bibliography/references.bib
* build					:noexport:
#+BEGIN_SRC emacs-lisp
(org-html-export-to-html nil nil nil t nil)
(rename-file "scimax.html" "scimax.html.mako" t)
#+END_SRC

#+RESULTS:

