#+OPTIONS: toc:nil
#+EXPORT_FILE_NAME: test.html.mako


#+BEGIN_HTML
<%inherit file="_templates/site.mako" />
<article class="page_box">
<%self:filter chain="markdown">
#+END_HTML

* Alloy catalysis
Alloy catalysts frequently do not have the same reactivity as the parent metals. We use density functional theory calculations to understand how the electronic structure of the alloy differs from the parent metals, and how those differences lead to different reactivities. We are especially interested in modeling heterogeneous site distributions, and the limit of single atom alloys.

cite:boes-2015-estim-bulk

cite:boes-2015-core-cu

* Oxygen evolution electrocatalysis

We are using Raman spectroscopy to probe the oxide/electrolyte interface under oxygen evolution conditions.

cite:landon-2012-spect-charac
cite:demeter-2014-elect-oxygen
cite:michael-2015-alkal-elect

cite:xu-2015-linear-respon

* CO_{2} Capture

We are investigating the use of a commercially available ion exchange resin as a CO<sub>2</sub> capture sorbent. We also have developed a high pressure silica capillary cell for in situ Raman measurements of CO<sub>2</sub> solubility in solvents for precombustion capture applications.

* Metal oxide reactivity

We are generally interested in understanding the reactivity of metal oxides towards oxygen and fuels. We use computational tools to model the electronic structure and reactivity of metal oxides for applications in water splitting and chemical looping.

cite:xu-2015-accur-u

cite:xu-2015-linear-respon

cite:xu-2014-relat

cite:curnan-2014-effec-concen





bibliography:../Dropbox/bibliography/references.bib

#+BEGIN_HTML
</%self:filter>
</article>
#+END_HTML

* build					:noexport:
#+BEGIN_SRC emacs-lisp
(require 'ox-md)
(org-html-export-to-html nil nil nil t nil)
(rename-file "test.html" "test.html.mako" t)
#+END_SRC

#+RESULTS:
