* Professor Kitchin is attending the 2013 China-America Frontiers of Engineering meeting
  :PROPERTIES:
  :categories: news
  :date:     2013/05/12 16:24:29
  :updated:  2013/05/12 16:37:15
  :END:

This meeting will be held in Beijing, China from May 15 to 17. Here is a description of the meeting from the website:

"CAFOE
2013 China-America Frontiers of Engineering Symposium

From May 15 - 17, the 2013 China-America Frontiers of Engineering will take place in Beijing, China. Sixty of the most promising engineers under the age of 45 from China and the United States will meet for an intensive 2-1/2 day symposium on developments at the cutting edge of engineering technology. The event is intended to facilitate international and cross-disciplinary research collaboration, promote the transfer of new techniques and approaches across disparate engineering fields, and encourage the creation of a transpacific network of world-class engineers."

Professor Kitchin will present his work in CO2 capture, water splitting, computational materials design and computing in engineering at a poster session in this meeting.

This meeting is hosted by the National Academy of Engineering and the Chinese Academy of Engineering. Learn more at  http://www.naefrontiers.org/Symposia/CAFOE.aspx
