* DONE 1000+ citations for fuel cell paper on the oxygen reduction reaction!
  CLOSED: [2015-03-30 Mon 20:02]
  :PROPERTIES:
  :categories: news
  :date:     2015/03/30 20:02:58
  :updated:  2015/03/30 20:11:41
  :END:

This landmark paper cite:norskov-2004-origin recently hit 1000+ citations! In this paper we lay out a framework using density functional theory to calculate the stabilities of intermediates in electrochemical processes such as fuel cells and electrolyzers. This was a very early use of electrochemical atomistic thermodynamics in which the electric potential and pH were both accounted for in the electrochemical reaction energies. We showed how the volcano plots frequently observed arise from trends in adsorption energies that are easily calculated. This paper also shows one of the earliest scaling relations between O and OH adsorption energies!

This paper came out shortly after I spent three months at DTU with Jens Nørskov when I was a PhD student. I still remember talking to him about the work that led to this paper one day at their regular afternoon department tea time. He suggested some DFT calculations that I knew how to do, and I went back to the office and worked on them the rest of the night. He wrote this amazing paper afterwards that has been cited over and over. Congratulations Jens! I am proud to have had a part in it.

#+BEGIN_SRC bibtex
@article{norskov-2004-origin,
  author =	 {N{\o}rskov, J. K. and Rossmeisl, J. and Logadottir, A. and
                  Lindqvist, L. and Kitchin, J. R. and Bligaard, T. and J{\'o}nsson,
                  H.},
  title =	 {Origin of the overpotential for oxygen reduction at a
                  fuel-cell cathode},
  journal =	 {Journal of Physical Chemistry B},
  year =	 2004,
  volume =	 108,
  pages =	 {17886-17892},
  number =	 46,
  doi =		 {10.1021/jp047349j},
  url = {https://doi.org/10.1021/jp047349j},
  issn =	 {1520-6106},
  type =	 {Journal Article},
}
#+END_SRC


#+BEGIN_HTML
<img src="http://api.elsevier.com/content/abstract/citation-count?doi=10.1021/jp047349j &httpAccept=image/jpeg&apiKey=5cd06d8a7df3de986bf3d0cd9971a47c"></img>
#+END_HTML

bibliography:../../Dropbox/bibliography/references.bib
