* New publication - Improved Uncertainty Estimation of Graph Neural Network Potentials Using Engineered Latent Space Distance
:PROPERTIES:
:categories: news,publication
:date:     2025/02/01 08:23:24
:updated:  2025/02/01 08:23:24
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/01/New-publication---Improved-Uncertainty-Estimation-of-Graph-Neural-Network-Potentials-Using-Engineered-Latent-Space-Distance.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/01/New-publication---Improved-Uncertainty-Estimation-of-Graph-Neural-Network-Potentials-Using-Engineered-Latent-Space-Distance/index.html
:END:

Machine learning has revolutionized materials discovery, but ensuring reliable predictions remains a challenge. The paper “Improved Uncertainty Estimation of Graph Neural Network Potentials Using Engineered Latent Space Distances” tackles this issue by introducing advanced uncertainty quantification (UQ) techniques for Graph Neural Networks (GNNs) used in catalyst discovery. Traditional models struggle with predicting uncertainty in relaxed energy calculations, a key factor in identifying promising catalytic materials. This work proposes a novel latent space distance approach, significantly improving calibration and reliability compared to standard ensemble methods. By leveraging distribution-free techniques and engineered latent representations, the study enables more accurate and interpretable confidence estimates, ensuring that machine learning-driven catalyst discovery is not just faster but also more trustworthy.


Musielewicz, Joseph; Lan, Janice; Uyttendaele, Matt; Kitchin, John, Improved Uncertainty Estimation of Graph Neural Network Potentials Using Engineered Latent Space Distance, J. Physical Chemistry C (2024). https://doi.org/10.1021/acs.jpcc.4c04972.

#+BEGIN_SRC bibtex
@article{musielewicz-2024-improv-uncer,
  author =	 {Joseph Musielewicz and Janice Lan and Matt Uyttendaele and
                  John R. Kitchin},
  title =	 {Improved Uncertainty Estimation of Graph Neural Network
                  Potentials Using Engineered Latent Space Distances},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 128,
  number =	 49,
  pages =	 {20799-20810},
  year =	 2024,
  doi =		 {10.1021/acs.jpcc.4c04972},
  url =		 {http://dx.doi.org/10.1021/acs.jpcc.4c04972},
  DATE_ADDED =	 {Sat Feb 1 08:18:45 2025},
}
#+END_SRC

altmetric:10.1021/acs.jpcc.4c04972

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35108470/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
