* Adding numerical methods to emacs with dynamic modules
  :PROPERTIES:
  :categories: emacs
  :date:     2017/07/08 10:12:45
  :updated:  2017/07/08 10:13:02
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2017/07/08/Adding-numerical-methods-to-emacs-with-dynamic-modules.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2017/07/08/Adding-numerical-methods-to-emacs-with-dynamic-modules/index.html
  :END:

There is a relatively new feature in Emacs 25 that allows you to extend Emacs using compiled libraries (http://diobla.info/blog-archive/modules-tut.html). This could be very helpful in a few ways:

1. To add functionality that exists in other libraries, e.g.
   1. [[https://github.com/syohex/emacs-libyaml][libyaml]]
   2. [[https://github.com/syohex/emacs-memcached][libmemcached]]
   3. [[https://github.com/syohex/emacs-mruby-test][Embedding Ruby in Emacs]]
2. Interface Emacs with hardware, e.g. [[http://nullprogram.com/blog/2016/11/05/][a joystick]], or [[https://github.com/syohex/emacs-eject][ejecting a CD]].
3. To speed up slow elisp functions
   1. A c implementation of a fibonacci function is 150 times faster than an elisp version [[https://coldnew.github.io/2d16cc25/][here]].
   2. This [[https://github.com/syohex/emacs-parson][json parser]] is up to 4 times faster than the json.el library for some operations.

I am interested in this in particular to bring numerical methods into Emacs. It is fair to ask why. Even I think the numpy/scipy/matplotlib Python stack is currently unparalleled in functionality for scientific programming. But I like writing elisp code so much more! So, we will take a look today at a simple example of integrating a function from the GNU Scientific Library into Emacs.

** Using the GSL to calculate a Bessel function value

A canonical example of using the GSL is given at https://www.gnu.org/software/gsl/manual/html_node/An-Example-Program.html. Here it is for reference. It just calculates a value for a Bessel function. We save this program in a file called example.c.

#+BEGIN_SRC C :tangle example.c
#include <stdio.h>
#include <gsl/gsl_sf_bessel.h>

int
main (void)
{
  double x = 5.0;
  double y = gsl_sf_bessel_J0 (x);
  printf ("J0(%g) = %.18e\n", x, y);
  return 0;
}
#+END_SRC

We have to compile and run this program. Here are the commands to do that.

#+BEGIN_SRC sh
gcc -Wall -I/usr/local/include/ -c example.c
gcc -L/usr/local/include -lgsl example.o 
./a.out
#+END_SRC

#+RESULTS:
: J0(5) = -1.775967713143382642e-01

That is a lot of code and steps to get one number. 

What I would like to do instead is this:

#+BEGIN_SRC emacs-lisp
(require 'gsl-sf-bessel)
(gsl-sf-bessel-J0 5)
#+END_SRC

So, enter the dynamic module!

** A GSL dynamic module for a Bessel function

To create the dynamic module we need a small c file that wraps the GSL function and adds it to the Emacs environment. Here is the smallest example I could come up with for this one function.  Basically, we create a function that takes the emacs environment and arguments, extract what we want from them, and use that to calculate what we need and return it to the environment. Then we register that function  and define what the module provides in emacs_module_init.

#+BEGIN_SRC c :tangle gsl-sf-bessel.c
#include <assert.h>
#include <gsl/gsl_sf_bessel.h>
#include "emacs-module.h"

int plugin_is_GPL_compatible;

static emacs_value
F_gsl_sf_bessel_J0 (emacs_env *env, ptrdiff_t nargs, emacs_value args[], void *data)
{
  assert (nargs == 1);
  double x = env->extract_float (env, args[0]);
  return env->make_float (env, gsl_sf_bessel_J0 (x));
}

int
emacs_module_init(struct emacs_runtime *ert)
{
	emacs_env *env = ert->get_environment(ert);

	emacs_value gsl_sf_bessel_J0_fn = env->make_function(env, 1, 1, F_gsl_sf_bessel_J0, "Regular cylindrical Bessel function of zeroth order, J_0(x)", NULL);

	emacs_value Qfset = env->intern(env, "fset");
	emacs_value Q_gsl_sf_bessel_J0 = env->intern(env, "gsl-sf-bessel-J0");
	emacs_value fset_args[] = { Q_gsl_sf_bessel_J0, gsl_sf_bessel_J0_fn };
	env->funcall(env, Qfset, 2, fset_args);

	emacs_value Qprovide = env->intern(env, "provide");
	emacs_value Q_gsl_sf_bessel = env->intern(env, "gsl-sf-bessel");
	emacs_value provide_args[] = { Q_gsl_sf_bessel };
	env->funcall(env, Qprovide, 1, provide_args);

	return 0;
}
#+END_SRC

Now we compile it into a shared library.

#+BEGIN_SRC sh
gcc -Wall -I/usr/local/include -fPIC -c gsl-sf-bessel.c
gcc -shared -L/usr/local/include -lgsl -o gsl-sf-bessel.so gsl-sf-bessel.o
#+END_SRC

#+RESULTS:

That creates our shared library in gsl-sf-bessel.so.

#+BEGIN_SRC sh
ls *.so
#+END_SRC

#+RESULTS:
: gsl-sf-bessel.so

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/Users/jkitchin/vc/blogofile-jkitchin.github.com/_blog/dynamic-module/")
(require 'gsl-sf-bessel)
(gsl-sf-bessel-J0 5.0)
#+END_SRC

#+RESULTS:
: -0.17759677131433826

That is the same answer as we got before. Here is the documentation we defined. It could use some improvement, e.g. to note that the argument has to be a float, and that only one argument is allowed. I am not sure why the signature doesn't show a single argument.

#+BEGIN_SRC emacs-lisp
(describe-function 'gsl-sf-bessel-J0)
#+END_SRC

#+RESULTS:
: gsl-sf-bessel-J0 is a Lisp function.
: 
: (gsl-sf-bessel-J0 &rest ARGS)
: 
: For more information check the manuals.
: 
: Regular cylindrical Bessel function of zeroth order, J_0(x)

I am not a very skilled C-programmer yet, so I don't know how hard it would be to make this function accept integers as well, or to vectorize it so you could have an arbitrary number of args to it and return a list.


** Summary

Dynamic modules look promising to extend Emacs with. This example is about the simplest function from the GSL there is. There are many more (https://www.gnu.org/software/gsl/doc/html/index.html) functions that do linear algebra on arrays, integration or optimization of functions, interpolation of data, etc. I don't have a sense yet of how easy it will be to integrate these into a module.

It looks like you are not limited to writing these in C. There is an example of a plugin written in Rust [[https://github.com/lunaryorn/emacs-module.rs/blob/master/src/lib.rs][here]], and a framework to write them in [[https://github.com/sigma/go-emacs/][Go]]. Maybe any language that can make a shared library with the required plugin_is_GPL_compatible symbol and emacs_module_init function would work. Those examples do not look significantly easier to write than the C versions though since I am not that fluent in those languages either.

There are some challenges to figure out in developing and using dynamic modules. Here are a few:

1. The documentation on what is possible is not that great yet, so there is a lot of exploring to do. There are a fair number of examples out there though to learn from (https://github.com/emacs-pe/emacs-modules). The [[https://github.com/emacs-mirror/emacs/tree/emacs-25/modules/mod-test][official example]] shows a lot of the functionality.
2. I guess it will be tricky to distribute these. I don't know how easy it would be to build all the libraries for each platform for distribution on MELPA for example. I don't think there is a standard way to incorporate a compile step in elisp package installation. Also, you need an Emacs version of at least 25 with the dynamic module feature compiled in. It is not yet a default enabled option. The required emacs-module.h should be gotten from the emacs build, so people with binaries might not be able to build it anyway.
3. Users will need the libraries the dynamic module uses. In this example, they will need libgsl.
4. Once you require the module, it does not seem possible to modify it, rebuild it, and reload it. It appears you have to close Emacs and reload it. That is tedious.

It would be nice to have a more generic foreign function interface that would allow you to develop more on the elisp side. One effort in that direction is https://github.com/tromey/emacs-ffi. It looks like it might be a lot simpler to use than creating a dynamic module. Once it is installed, it looks like you can write elisp code to wrap the library functions. I will write about this on another day.




