* New publication in Calphad
  :PROPERTIES:
  :categories: news, publication
  :date:     2017/02/05 12:28:51
  :updated:  2017/02/05 12:28:51
  :END:

Alloys can have rich, complex phase behavior. Cu-Pd alloys for example show an unusual behavior where a BCC lattice forms for some compositions, even though the alloy is made from two metals that are exclusively FCC in structure! Being able to model and predict this kind of behavior is a major challenge. In this work, we use cluster expansions to model the configurational degrees of freedom in the FCC and BCC lattices and show qualitatively that we can predict the region where the B2 phase (the BCC one) forms. The agreement with experiment is not quantitative though, and we show that part this disagreement is due to the lack of vibrational entropy in the cluster expansion. When we include vibrational entropy, the qualitative agreement improves.

#+BEGIN_SRC bibtex
@article{geng-2017-first-princ,
  author =	 "Feiyang Geng and Jacob R. Boes and John R. Kitchin",
  title =	 {First-Principles Study of the Cu-Pd Phase Diagram},
  journal =	 "Calphad ",
  volume =	 56,
  pages =	 "224 - 229",
  year =	 2017,
  doi =		 {10.1016/j.calphad.2017.01.009},
  url =
                  {https://doi.org/http://dx.doi.org/10.1016/j.calphad.2017.01.009},
  abstract =	 "Abstract The equilibrium phase diagram of a Cu-Pd alloy has
                  been computed using cluster expansion and Monte Carlo
                  simulation methods combined with density functional theory.
                  The computed phase boundaries show basic features that are
                  consistent with the experimentally reported phase diagram.
                  Without vibrational free energy contributions, the
                  order-disorder transition temperature is underestimated by 100
                  K and the critical point is inconsistent with experimental
                  result. The addition of vibrational free energy contributions
                  yields a more qualitatively correct Cu-Pd phase diagram in the
                  Cu rich region. ",
  issn =	 "0364-5916",
  keywords =	 "Density functional theory",
}

#+END_SRC

altmetric:10.1016/j.calphad.2017.01.009
