* New publication in Applied Materials and Interfaces
  :PROPERTIES:
  :categories: news
  :date:     2014/02/06 16:04:06
  :updated:  2014/02/06 16:04:06
  :END:

*Identifying Potential BO2 Oxide Polymorphs for Epitaxial Growth Candidates*,
by Prateek Mehta, Paul A. Salvador, and John R. Kitchin
http://pubs.acs.org/doi/full/10.1021/am4059149

Transition metal dioxides (BO2) exhibit a number of polymorphic structures with distinct properties, but the isolation of different polymorphs for a given composition is carried out using trial and error experimentation. We present computational studies of the relative stabilities and equations of state for six polymorphs (anatase, brookite, rutile, columbite, pyrite, and fluorite) of five different BO2 dioxides (B = Ti, V, Ru, Ir, and Sn). These properties were computed in a consistent fashion using several exchange correlation functionals within the density functional theory formalism, and the effects of the different functionals are discussed relative to their impact on predictive synthesis. We compare the computational results to prior observations of high-pressure synthesis and epitaxial film growth and then use this discussion to predict new accessible polymorphs in the context of epitaxial stabilization using isostructural substrates. For example, the relative stabilities of the columbite polymorph for VO2 and RuO2 are similar to those of TiO2 and SnO2, the latter two of which have been previously stabilized as epitaxial films.

As with other recent papers, the supporting information file contains embedded data files that enable the reproduction of the data and figures in the paper.
