* New Publication - Solving an inverse problem with generative models
:PROPERTIES:
:categories: news,publication
:date:     2025/06/17 13:24:43
:updated:  2025/06/17 13:24:43
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/06/17/New-Publication---Solving-an-inverse-problem-with-generative-models.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/06/17/New-Publication---Solving-an-inverse-problem-with-generative-models/index.html
:END:

Inverse problems—where we aim to find inputs that produce a desired output—are notoriously challenging in science and engineering. In this study, I explore how generative AI models can tackle these problems by comparing four approaches: a forward model combined with nonlinear optimization, a backward model using partial least squares regression, and two generative methods based on Gaussian mixture models and diffusion-based flow transformations. Using data from a simple RGB-controlled light sensor, the paper demonstrates that generative models can accurately and flexibly infer input settings for target outputs, with advantages such as uncertainty quantification and the ability to condition on partial outputs. This work showcases the promise of generative modeling in reshaping how we approach inverse problems across disciplines.


#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/zx6FHzx8V-Y?si=1OQBQ25Ze8e5mzZl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_SRC bibtex
@article{kitchin-2025-solvin-inver,
  author =	 "Kitchin, John R.",
  title =	 {Solving an Inverse Problem With Generative Models},
  journal =	 "Digital Discovery",
  pages =	 "-",
  year =	 2025,
  doi =		 "10.1039/D5DD00137D",
  url =		 "http://dx.doi.org/10.1039/D5DD00137D",
  abstract =	 "Inverse problems{,} where we seek the values of inputs to a
                  model that lead to a desired set of outputs{,} are a
                  challenges subset of problems in science and engineering. In
                  this work we demonstrate the use of two generative AI methods
                  to solve inverse problems. We compare this approach to two
                  more conventional approaches that use a forward model with
                  nonlinear programming{,} and the use of a backward model. We
                  illustrate each method on a dataset obtained from a simple
                  remote instrument that has three inputs: the setting of the
                  red{,} green and blue channels of an RGB LED. We focus on
                  several outputs from a light sensor that measures intensity at
                  445 nm{,} 515 nm{,} 590 nm{,} and 630 nm. The speciﬁc problem
                  we solve is identifying inputs that lead to a speciﬁc
                  intensity in three of those channels. We show that generative
                  models can be used to solve this kind of inverse problem{,}
                  and they have some advantages over the conventional
                  approaches.",
  publisher =	 "RSC",
}
#+END_SRC

altmetric:10.1039/D5DD00137D
