* New publication - Uncertainty quantification in machine learning and nonlinear least squares regression models
:PROPERTIES:
:categories: news,publication
:date:     2021/11/30 16:44:33
:updated:  2021/12/02 11:57:37
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2021/11/30/New-publication---Uncertainty-quantification-in-machine-learning-and-nonlinear-least-squares-regression-models.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2021/11/30/New-publication---Uncertainty-quantification-in-machine-learning-and-nonlinear-least-squares-regression-models/index.html
:END:

Say you have acquired some data, and fitted a nonlinear model to it. The fit looks good, but how good are predictions from the model? In high dimensional space it is tricky to tell if you are extrapolating, what should you do? First, read this paper! We illustrate a simple tool called the delta method that can help you estimate the prediction uncertainty from your model using automatic differentiation to get the required derivatives. We show some examples, and how you can use this method to refine what data you should use in fitting your models. We even show how to handle some tricky cases with models where the Hessian is not invertable! The examples are from molecular simulation, but the approach is general and should work for other models too.

#+BEGIN_SRC bibtex
@article{zhan-2021-uncer-quant,
  author =	 {Ni Zhan and John R. Kitchin},
  title =	 {Uncertainty Quantification in Machine Learning and Nonlinear
                  Least Squares Regression Models},
  journal =	 {AIChE Journal},
  volume =	 {},
  number =	 {},
  pages =	 {},
  year =	 2021,
  doi =		 {10.1002/aic.17516},
  url =		 {http://dx.doi.org/10.1002/aic.17516},
  DATE_ADDED =	 {Mon Nov 8 08:51:21 2021},
}
#+END_SRC

Checkout the video brief here:

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/xg2nVji7SfY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

altmetric:10.1002/aic.17516
