* New publication - Ligand Enhanced Activity of in Situ Formed Nanoparticles for Photocatalytic Hydrogen Evolution
:PROPERTIES:
:categories: news,publication
:date:     2021/12/02 11:56:53
:updated:  2021/12/02 11:56:53
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2021/12/02/New-publication---Ligand-Enhanced-Activity-of-in-Situ-Formed-Nanoparticles-for-Photocatalytic-Hydrogen-Evolution.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2021/12/02/New-publication---Ligand-Enhanced-Activity-of-in-Situ-Formed-Nanoparticles-for-Photocatalytic-Hydrogen-Evolution/index.html
:END:

In this paper we show that we can stabilize /in situ/ synthesized nanoparticles by including stabilizing ligands in the synthesis. This gives the /in situ/ particles comparable stability to pre-synthesized particles, while retaining the flexibility of the /in situ/ synthesis. We show that not all stabilizing ligands work for all metals, although PEGSH is a reasonable starting point for the metals we considered in this work. Additionally, we show that the incorporation of PEGSH can make some metals that appear inactive without stabilization due to precipitation, become active when stabilized. Although the addition of stabilizing ligands complicates the optimization of the synthesis conditions, it leads to more reproducible, and in some cases better results than leaving them out.

#+BEGIN_SRC bibtex
@article{simon-2021-ligan-enhan,
  author =	 {Zoe C. Simon and Eric M. Lopato and Maya
                  Bhat and Paige J. Moncure and Sarah M. Bernhard and John R.
                  Kitchin and Stefan Bernhard and Jill Millstone},
  title =	 {Ligand Enhanced Activity of in Situ Formed Nanoparticles for
                  Photocatalytic Hydrogen Evolution},
  journal =	 {ChemCatChem},
  volume =	 {},
  number =	 {},
  pages =	 {},
  year =	 2021,
  doi =		 {10.1002/cctc.202101551},
  url =		 {http://dx.doi.org/10.1002/cctc.202101551},
  DATE_ADDED =	 {Mon Nov 29 17:01:16 2021},
}
#+END_SRC

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/EaTYAfQMBlY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

altmetric:10.1002/cctc.202101551
