* Spoken translations in Emacs
  :PROPERTIES:
  :categories: emacs,speech
  :date:     2015/07/01 11:42:28
  :updated:  2015/07/01 11:42:28
  :END:

Finally, continuing our experiments with computer speech for fun, let us try a translation of text to another language that is then spoken. Here is a free translator that has the courtesy to reply with json with the translated text in it. http://mymemory.translated.net/api/get?q=Hello%20World!&langpair=en|de I had to download a German voice called Anna, then get some translated text.

As with previous posts, there is a video: https://www.youtube.com/watch?v=8CBKnahE0ak. I am trying ScreenFlow for these (instead of Camtasia), and I still have not quite mastered the aspect ratio, so the videos still look a little odd.

As a reminder, we have this easy way to speak text in applescript. If you are on Linux, check out [[https://wiki.archlinux.org/index.php/Festival][Festival]] and on windows you may find some inspiration [[http://stackoverflow.com/questions/1040655/ms-speech-from-command-line][here]].

#+BEGIN_SRC emacs-lisp
(do-applescript "say \"Hello. My name is John. I am glad to meet you.\"")
#+END_SRC

#+RESULTS:

You can retrieve json data of the translated text, and then we can use it in our [[http://kitchingroup.cheme.cmu.edu/blog/2015/06/29/Getting-Emacs-to-read-to-me/][word-speak]] function we previously developed. Here is an example in in German.
#+BEGIN_SRC emacs-lisp :results code
(let* ((words-voice "Anna")
       (text "Hello. My name is John. I am glad to meet you.")
       (url (format "http://mymemory.translated.net/api/get?q=%s!&langpair=en|de"
		    text))
       (json (with-current-buffer
		 (url-retrieve-synchronously url)
	       (json-read-from-string
		(buffer-substring url-http-end-of-headers (point-max)))))
       (translated-text (cdr (assoc 'translatedText (cdr (assoc 'responseData json))))))
  (words-speak translated-text)
  translated-text)
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
"Hallo. Mein Name ist John. Ich freue mich, Sie kennen zu lernen.!"
#+END_SRC


How about Chinese? Again, I downloaded a Chinese voice called "Ting-Ting".
#+BEGIN_SRC emacs-lisp :results code
(let* ((words-voice "Ting-Ting")
       (text "Hello. My name is John. I am glad to meet you.")
       (url (format "http://mymemory.translated.net/api/get?q=%s!&langpair=en|zh"
		    text))
       (json (with-current-buffer
		 (url-retrieve-synchronously url)
	       (json-read-from-string
		(buffer-substring url-http-end-of-headers (point-max)))))
       (translated-text (cdr (assoc 'translatedText (cdr (assoc 'responseData json))))))
  (words-speak translated-text)
  translated-text)
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
"你好。我的名字是约翰。我很高兴见到你。!"
#+END_SRC

So, can any Chinese readers and listeners confirm if the text translates correctly, and if Ting-Ting said it correctly? Hopefully it is good enough to make some sense and be useful!
