* DONE A dynamic snippet for a task due 7 days from now
  CLOSED: [2014-02-16 Sun 13:50]
  :PROPERTIES:
  :categories: emacs,org-mode
  :date:     2014/02/16 13:50:27
  :updated:  2014/02/16 15:52:44
  :END:

I have been playing with yasnippets. A pretty cool feature is that you can run elisp code in the template to generate text. Below, I define a snippet that will create a todo item due 7 days from the time you define it. This is an unconventional way to define a snippet, but I did not want to save it to a file just to try it out. So, I put it in a temporary buffer, and load it from there. When you run this block, it will note it is a new snippet, and ask if you want to save it. You can say no. 

We will use the code we developed [[http://kitchingroup.cheme.cmu.edu/blog/2014/02/05/Add-time-to-a-deadline/][here]] to create a timestamp from the
current time plus seven days.

#+BEGIN_SRC emacs-lisp
(yas-global-mode)
(with-temp-buffer
  (insert "# name : todo-followup
# --

*************** TODO $1
${2:		 DEADLINE: `(let ((seven-days (seconds-to-time (* 7 24 60 60))))
  (format-time-string \"<%Y-%m-%d %a>\" (time-add (current-time) seven-days)))`}$0
*************** END 
")
  (yas-load-snippet-buffer-and-close 'org-mode))
#+END_SRC

#+RESULTS:


Now, you will have a new entry in the YASnippet menu that is called todo-followup. If you put the cursor on a blank line, and select that entry you get this below (after you fill in the text for the headline, of course!):

#+BEGIN_EXAMPLE
*************** TODO see how many times this was viewed
		DEADLINE: <2014-02-23 Sun>
*************** END 
#+END_EXAMPLE



That is pretty nice, as it saves a lot of keystrokes for that
particular kind of task. Let us up the ante, and see if we can make it
interactive so you can enter the number of days from now the task is
due.

#+BEGIN_SRC emacs-lisp
(yas-global-mode)
(with-temp-buffer
  (insert "# name : todo-followup
# --

*************** TODO $1
${2:		 DEADLINE: `(let ((ndays (seconds-to-time (* (string-to-int (read-from-minibuffer \"Days until due: \")) 24 60 60))))
  (format-time-string \"<%Y-%m-%d %a>\" (time-add (current-time) ndays)))`}$0
*************** END 
")
  (yas-load-snippet-buffer-and-close 'org-mode))
#+END_SRC

#+RESULTS:

#+BEGIN_EXAMPLE
*************** TODO sweet!
		DEADLINE: <2014-02-26 Wed>
*************** END 
#+END_EXAMPLE
Well, that made it just a bit sweeter! I was prompted for the "Days
until due:", entered 10 days, and a date 10 days from now was
automatically entered!


