* DONE New publication in Crystal Growth & Design
  CLOSED: [2017-08-05 Sat 13:11]
  :PROPERTIES:
  :categories: news,publication
  :date:     2017/08/05 13:11:22
  :updated:  2017/08/05 13:16:35
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2017/08/05/New-publication-in-Crystal-Growth-&-Design.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2017/08/05/New-publication-in-Crystal-Growth-&-Design/index.html
  :END:

Usually, metal oxides grow in a single, most stable crystal structure at a particular set of conditions. For example, TiO_{2} grows in the rutile structure for a large range of pressure and temperature conditions, but under some conditions it can also grow in the anatase structure. In this paper we show that epitaxial stabilization can be used to influence which crystal structures are observed for the growth of tin oxide. Tin oxide is normally only observed in the rutile structure. We grew tin oxide as an epitaxial film on a poly-crystalline substrate of CoNb_{2}O_{6} which has an \alpha-PbO_{2} crystal structure. We found that both rutile and \alpha-PbO_{2} structures could be found in the film, and that the structure correlated with the orientation of the underlying grains. In other words, the orientation of a substrate can influence the structure of an epitaxial film, enabling one to grow films in crystal structures that may be metastable, and unobtainable in bulk samples.

#+BEGIN_SRC bibtex
@article{wittkamper-2017-compet-growt,
  author =	 {Wittkamper, Julia and Xu, Zhongnan and Kombaiah, Boopathy and
                  Ram, Farangis and De Graef, Marc and Kitchin, John R. and
                  Rohrer, Gregory S. and Salvador, Paul A.},
  title =	 {Competitive Growth of Scrutinyite ($\alpha$-PbO2) and Rutile
                  Polymorphs of \ce{SnO2} on All Orientations of Columbite
                  \ce{CoNb2O6} Substrates},
  journal =	 {Crystal Growth \& Design},
  volume =	 17,
  number =	 7,
  pages =	 {3929-3939},
  year =	 2017,
  doi =		 {10.1021/acs.cgd.7b00569},
  url =		 {https://doi.org/10.1021/acs.cgd.7b00569},
  eprint =	 { http://dx.doi.org/10.1021/acs.cgd.7b00569 },
}

#+END_SRC

altmetric:10.1021/acs.cgd.7b00569
