* New publication in ACS Catalysis on composition dependent alloy electronic structure
  :PROPERTIES:
  :categories: news,publication
  :date:     2015/04/24 15:41:03
  :updated:  2015/04/24 15:41:03
  :END:
In this collaborative paper we map out the electronic structure of a Cu-Pd alloy across composition space, and then correlate that electronic structure with the reactivity of the alloy. We experimentally measure the average energy of the filled valence band, and show it is similar to the calculated d-band center. We then show how those measured electronic structure properties correlate with the H_{2}\D_{2} exchange kinetics. The combination of experiments on composition spread alloy films (CSAF) and theory provides an integrated understanding of alloy reactivity in this system.

#+BEGIN_SRC bibtex
@article{gumuslu-2015-correl-elect,
  author =	 {G. Gumuslu and P. Kondratyuk and J. R. Boes and B. Morreale
                  and J. B. Miller and J. R. Kitchin and A. J. Gellman},
  title =	 {Correlation of Electronic Structure With Catalytic Activity:
                  \ce{H2}-\ce{D2} Exchange Across \ce{Cu_{x}Pd_{1-x} Composition
                  Space},
  journal =	 {ACS Catalysis},
  volume =	 {5},
  pages =	 {3137-3147},
  year =	 2015,
  doi =		 {10.1021/cs501586t},
  url =		 {http://dx.doi.org/10.1021/cs501586t},
  date_added =	 {Fri Apr 24 14:47:29 2015},
}
#+END_SRC