* New publication - The Potential of Zero Total Charge Predicts Cation Effects for the Oxygen Reduction Reaction
:PROPERTIES:
:categories: news,publication
:date:     2025/01/29 06:26:00
:updated:  2025/01/29 06:26:00
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/01/29/New-publication---The-Potential-of-Zero-Total-Charge-Predicts-Cation-Effects-for-the-Oxygen-Reduction-Reaction.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/01/29/New-publication---The-Potential-of-Zero-Total-Charge-Predicts-Cation-Effects-for-the-Oxygen-Reduction-Reaction/index.html
:END:


This paper investigates how alkali metal cations influence the oxygen reduction reaction (ORR) on various metal surfaces. By combining experimental data and computational modeling, the authors identify the potential of zero total charge (PZTC) as a key predictor of cation effects. Metals with PZTCs positive of the ORR potential window show increased activity with larger cations (e.g., Li+ < Na+ < K+ < Cs+), enhancing reaction rates by reducing hydroxide poisoning or lowering activation barriers. Conversely, metals with PZTCs negative of the ORR potential repel cations, showing no effect. This work offers a mechanistic understanding of cation effects in electrocatalysis, paving the way for electrolyte design to optimize catalytic performance.


#+BEGIN_SRC bibtex
@article{bender-2024-poten-zero,
  author =	 {Jay T. Bender and Rohan Yuri Sanspeur and Angel E. Valles and
                  Alyssa K. Uvodich and Delia J. Milliron and John R. Kitchin
                  and Joaquin Resasco},
  title =	 {The Potential of Zero Total Charge Predicts Cation Effects for
                  the Oxygen Reduction Reaction},
  journal =	 {ACS Energy Letters},
  volume =	 9,
  number =	 9,
  pages =	 {4724-4733},
  year =	 2024,
  doi =		 {10.1021/acsenergylett.4c01897},
  url =		 {http://dx.doi.org/10.1021/acsenergylett.4c01897},
}
#+END_SRC

altmetric:10.1021/acsenergylett.4c01897



#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35059785/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
