* Using #+call to run code blocks in org-mode
  :PROPERTIES:
  :categories: org-mode
  :date:     2014/02/08 08:54:57
  :updated:  2014/02/08 09:03:25
  :END:
I often put my code blocks right where I need them in my org documents. It usually has a section explaining what I want to do, then the code block that implements the idea, following by the output. Sometimes the code blocks are long, however, and it might be desirable for that code to be in an appendix. [fn:4]

Org-mode enables this with #+CALL. For example, I have a [[*Area%20of%20a%20circle][function]] in the appendix of this post that calculates the area of a circle given its radius. The function is "named" by a line like this:

#+BEGIN_EXAMPLE
#+name: function-name
#+END_EXAMPLE

I can use the function like this:

#+BEGIN_EXAMPLE
#+CALL: circle-area(1)
#+END_EXAMPLE

#+CALL: circle-area(1)

#+RESULTS:
: 3.14159265359

That is pretty nice. You can separate the code out from the main document. You still have to put the #+CALL: line in though. It may be appropriate to put a call inline with your text. If you add the following sentence, and put your cursor on the call_circle-area and press C-c C-c, the output is put in verbatim markers right after it. 

#+BEGIN_EXAMPLE
The area of a circle with unit radius is call_circle-area(1). 
#+END_EXAMPLE

The area of a circle with unit radius is call_circle-area(1) =3.14159265359=. 

Here is another interesting way to do it. We can specify a named results block. Let us consider another [[*Hello%20function][function]] that prints output. We specify a named results block like this:

#+BEGIN_EXAMPLE
#+RESULTS: function-name
#+END_EXAMPLE

Now, whenever you execute that block, the results will get put where this line is like this.

#+RESULTS: hello-block
: hello John

These could be useful approaches to making the "top" of your document cleaner, with less code in it. The code of course is still in the document, but at the end, in an appendix for example. This kind of separation might make it a little harder to find the code, and to reevaluate it,[fn:5] but it might improve the readability for others. 




** Appendix of code

*** Area of a circle
#+name: circle-area
#+header: :var r=0
#+begin_src python :results value
import numpy as np
return np.pi * r**2
#+end_src


*** Hello function

#+name: hello-block
#+header: :var name="John"
#+BEGIN_SRC python  :results output
print 'hello ' + name
#+END_SRC


