* TODO New publication - Beyond the Fourth Paradigm of Modeling in Chemical Engineering
DEADLINE: <2025-02-05 Wed>
:PROPERTIES:
:categories: news,publication
:date:     2025/02/05 07:16:31
:updated:  2025/02/05 07:16:31
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/05/New-publication---Beyond-the-Fourth-Paradigm-of-Modeling-in-Chemical-Engineering.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/05/New-publication---Beyond-the-Fourth-Paradigm-of-Modeling-in-Chemical-Engineering/index.html
:END:

Chemical engineering has undergone multiple modeling revolutions—from empirical correlations and manual analytical methods to computational techniques and, more recently, machine learning (ML). This article argues that we are now on the verge of a new era driven by differentiable programming, which merges domain knowledge with data-driven models in ways that can transform research, education, and industry.

Differentiable programming, powered by automatic differentiation (AD), allows models to compute derivatives efficiently, making optimization, uncertainty quantification, and hybrid physics-informed ML models more accessible. This capability enables engineers to integrate physical principles with data-driven methods, moving beyond “black-box” ML models. The article highlights the role of AD in process modeling, molecular simulations, and control systems, emphasizing its potential to refine chemical engineering calculations beyond traditional regression methods.

However, leveraging these tools requires a workforce skilled in ML, data science, and automation. The paper calls for educational reform, urging chemical engineering programs to integrate these technologies into curricula to prepare future engineers for this computational revolution.

#+BEGIN_SRC bibtex
@article{kitchin-2025-beyon-fourt,
  author =	 {John R. Kitchin and Victor Alves and Carl D. Laird},
  title =	 {Beyond the Fourth Paradigm of Modeling in Chemical
                  Engineering},
  journal =	 {Nature Chemical Engineering},
  volume =	 {nil},
  number =	 {nil},
  pages =	 {nil},
  year =	 2025,
  doi =		 {10.1038/s44286-024-00170-x},
  url =		 {http://dx.doi.org/10.1038/s44286-024-00170-x},
  DATE_ADDED =	 {Tue Jan 28 15:30:08 2025},
}
#+END_SRC

altmetric:10.1038/s44286-024-00170-x

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/34957390/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
