* New publication - Unifying theory of electronic descriptors of metal surfaces upon perturbation
:PROPERTIES:
:categories: news,publication
:date:     2025/01/30 06:33:00
:updated:  2025/01/30 06:33:00
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/01/30/New-publication---Unifying-theory-of-electronic-descriptors-of-metal-surfaces-upon-perturbation.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/01/30/New-publication---Unifying-theory-of-electronic-descriptors-of-metal-surfaces-upon-perturbation/index.html
:END:

The paper “Unifying Theory of Electronic Descriptors of Metal Surfaces upon Perturbation” by Huang et al. presents a novel framework for predicting electronic properties of metal surfaces using interpretable deep learning. Unlike traditional black-box machine learning models, this approach integrates physical insights to enhance interpretability without sacrificing accuracy. The study identifies a previously overlooked factor—orbital resonance in d-electron hopping—which influences the electronic structure of transition and noble metal surfaces alongside known effects like charge transfer, strain, and ligand interactions. By leveraging a physics-infused deep learning model, the authors provide a unified method for predicting electronic descriptors, offering a powerful tool for the rational design of catalytic materials and other functional surfaces in materials science. This work bridges the gap between theory and data-driven approaches, paving the way for more efficient and interpretable materials discovery.

Yang Huang, Shih-Han Wang, Mohith Kamanuru, Luke E. K. Achenie, John R. Kitchin, and Hongliang Xin, Unifying theory of electronic descriptors of metal surfaces upon perturbation, Phys. Rev. B 110, L121404 (2024). https://doi.org/10.1103/PhysRevB.110.L121404.

#+BEGIN_SRC bibtex
@article{huang-2024-unify-theor,
  author =	 {Yang Huang and Shih-Han Wang and Mohith Kamanuru and Luke E.
                  K. Achenie and John R. Kitchin and Hongliang Xin},
  title =	 {Unifying Theory of Electronic Descriptors of Metal Surfaces
                  Upon Perturbation},
  journal =	 {Physical Review B},
  volume =	 110,
  number =	 12,
  pages =	 {L121404},
  year =	 2024,
  doi =		 {10.1103/physrevb.110.l121404},
  url =		 {http://dx.doi.org/10.1103/PhysRevB.110.L121404},
  DATE_ADDED =	 {Wed Jan 29 19:39:29 2025},
}
#+END_SRC

altmetric:10.1103/physrevb.110.l121404

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35076105/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
