* DONE Extracting bibtex file from an org-buffer
  CLOSED: [2014-02-19 Wed 18:46]
  :PROPERTIES:
  :categories: bibtex,org-mode
  :date:     2014/02/19 18:45:27
  :updated:  2014/02/19 19:27:20
  :END:

We use citation links a lot in our org-files, like this: cite:thompson-2014-co2-react. Sometimes there are multiple citations like this cite:mehta-2014-ident-poten,hallenbeck-2013-effec-o2. It would be convenient at times to extract a bibtex file from these citations. That way we could easily share files. This is possible in RefTeX from a LaTeX file. Org makes it easy to export to LaTeX, so this seems like it should be easy. It would be easy, if I always put the bibliography link in the file. I usually do not, so let us check if that is the case, and if it is not add the bibliography to the end before we export. Then, with the LaTeX file in hand, we open it, and call the RefTeX functions to get the bibliography. Finally, we will create a link to the actual created file, and add it as a source block that can be tangled at the end of the file.

Here is a function that does the extraction and some house cleaning. We actually take the contents of the buffer and save it in a temporary file, so that we do not accidentally clobber a tex or bibtex file here.

#+BEGIN_SRC emacs-lisp
(defun kg-extract-bibtex ()
  "create bibtex file of entries cited in this buffer"

  (let* ((tempname (make-temp-file "extract-bib"))
         (contents (buffer-string))
         (cb (current-buffer))
	 basename texfile bibfile results)
    
    (find-file tempname)
    (insert contents)
    (setq basename (file-name-sans-extension 
		    (file-name-nondirectory buffer-file-name))
	  texfile (concat basename ".tex")
	  bibfile (concat basename ".bib"))

  (save-excursion
    (goto-char (point-min))
    (unless (re-search-forward "^bibliography:" (point-max) 'end)
      (insert (format "\nbibliography:%s" (mapconcat 'identity reftex-default-bibliography ",")))))

    (org-latex-export-to-latex)
    (find-file texfile)
    (reftex-parse-all)
    (reftex-create-bibtex-file bibfile)
    (setq results (buffer-string))
    (kill-buffer bibfile)
    (kill-buffer texfile)
    (delete-file texfile)
    (delete-file tempname)

    (switch-to-buffer cb)
    (save-excursion
      (goto-char (point-max))
      (insert (format "

,** Bibtex entries

,#+BEGIN_EXAMPLE: 
%s
,#+END_EXAMPLE" results)))))

(kg-extract-bibtex)
#+END_SRC

#+RESULTS:

There it is! The src block does not render in HTML very well, since it appears to be simple text. It looks fine in the org file though.

It might be a good idea to replace the bibliography line with the new file, but I will leave that as an exercise for later.




** Bibtex entries

#+BEGIN_EXAMPLE: 
@article{hallenbeck-2013-effec-o2,
  author =	 "Hallenbeck, Alexander P. and Kitchin, John R.",
  title =	 "Effects of \ce{O_2} and \ce{SO_2} on the Capture
                  Capacity of a Primary-Amine Based Polymeric
                  \ce{CO_2} Sorbent",
  year =	 2013,
  doi =		 "10.1021/ie400582a",
  eprint =	 "http://pubs.acs.org/doi/pdf/10.1021/ie400582a",
  journal =	 "Industrial \& Engineering Chemistry Research",
  pages =	 "10788-10794",
  url =		 "http://pubs.acs.org/doi/abs/10.1021/ie400582a",
}

@article{mehta-2014-ident-poten,
  author =	 {Mehta, Prateek and Salvador, Paul A. and Kitchin,
                  John R.},
  title =	 {Identifying Potential BO2 Oxide Polymorphs for
                  Epitaxial Growth Candidates},
  journal =	 {ACS Applied Materials \& Interfaces},
  volume =	 0,
  number =	 0,
  pages =	 {null},
  year =	 2014,
  doi =		 {10.1021/am4059149},
  URL =		 {http://pubs.acs.org/doi/abs/10.1021/am4059149},
  eprint =	 {http://pubs.acs.org/doi/pdf/10.1021/am4059149}
}

@Article{thompson-2014-co2-react,
  author =	 {Thompson, Robert L. and Albenze, Erik and Shi, Wei
                  and Hopkinson, David and Damodaran, Krishnan and
                  Lee, Anita and Kitchin, John and Luebke, David
                  Richard and Nulwala, Hunaid},
  title =	 {\ce{CO_2} Reactive Ionic Liquids: Effects of
                  functional groups on the anion and its influence on
                  the physical properties},
  journal =	 {RSC Adv.},
  year =	 2014,
  pages =	 "-",
  publisher =	 {The Royal Society of Chemistry},
  doi =		 {10.1039/C3RA47097K},
  url =		 {https://doi.org/10.1039/C3RA47097K},
  abstract =	 "Next generation of gas separation materials are
                  needed to alleviate issues faced in energy and
                  environmental area. Ionic liquids (ILs) are
                  promising class of material for CO2 separations. In
                  this work{,} CO2 reactive triazolides ILs were
                  synthesized and characterized with the aim of
                  developing deeper understanding on how structural
                  changes affect the overall properties for CO2
                  separation. Important insights were gained
                  illustrating the effects of substituents on the
                  anion. It was found that substituents play a crucial
                  role in dictating the overall physical properties of
                  reactive ionic liquids. Depending upon the
                  electronic and steric nature of the substituent{,}
                  CO2 capacities between 0.07-0.4 mol CO2/mol IL were
                  observed. Detailed spectroscopic{,} CO2
                  absorption{,} rheological{,} and simulation studies
                  were carried out to understand the nature and
                  influence of these substituents. The effect of water
                  content was also evaluated{,} and it was found that
                  water had an unexpected impact on the properties of
                  these materials{,} resulting in an increased
                  viscosity{,} but little change in the CO2
                  reactivity."
}
#+END_EXAMPLE
