* A short example
  :PROPERTIES:
  :categories: emacs,orgref,orgmode,citations
  :date:     2015/12/11 18:05:43
  :updated:  2015/12/11 18:05:43
  :END:

As a potential solution for citions in org-mode for non-LaTeX export, here we introduce csl (citation syntax lisp). The idea is heavily influenced by the xml-based Citation Syntax Language, but uses lisp sexps instead.

Briefly, there is a csl file that contains two variables: citation-style and bibliography-style. The citation-style defines how the in-text citations are represented for different types of citations. The bibliography-style defines how the bibliography is constructed.

What do we gain by this?
1. No need for external citeproc program, and hackability by org-mode experts.
2. Punctuation transposition and space chomping, i.e. put superscripts on the right side of punctuation if you want it, and remove whitespace before superscripts if you want it.
3. Total tunability of the citation format to different backends.
4. Easy to change bibliography format with the bibliographystyle link.

The real code for this is too long to blog about. Instead, you should check it out here: https://github.com/jkitchin/org-ref/tree/master/citeproc

** Reference types

- A book cite:kittel-2005-introd-solid.

- An article cite:kitchin-2015-examp

- A miscellaneous bibtex type cite:xu-suppor.

** Citation types

- Regular citation:  cite:kitchin-2015-examp
- citeauthor:  citeauthor:kitchin-2015-examp
- citeyear:   citeyear:kitchin-2015-examp

** Multiple citations and sorting within citation
- a,b: cite:kitchin-2015-examp,kitchin-2015-data-surfac-scien
- b,a: cite:kitchin-2015-data-surfac-scien,kitchin-2015-examp

** Space chomping and punctuation testing
- Citation at end of sentence cite:kitchin-2015-examp.
- Citation in clause cite:kitchin-2015-examp,kitchin-2015-data-surfac-scien, with a comma.
- Citation in middle of cite:kitchin-2015-examp,kitchin-2015-data-surfac-scien a sentence.

** Building
   :PROPERTIES:
   :date:     2015/12/11 14:47:59
   :updated:  2015/12/11 14:48:26
   :END:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path ".")
(require 'org-ref-citeproc)

(when (file-exists-p "readme.html") (delete-file "readme.html"))
(let ((org-export-before-parsing-hook '(orcp-citeproc)))
  (browse-url (org-html-export-to-html)))
#+End_src

#+RESULTS:
: #<process open ./readme.html>

#+BEGIN_SRC emacs-lisp
(add-hook 'org-export-before-parsing-hook 'orcp-citeproc)
#+END_SRC

#+RESULTS:
| orcp-citeproc |

** Summary thoughts
1. Other bibtex entries need to be tested out.
2. Remaining bibtex fields need to be defined.
3. Standardization of styling that can be done. Not all features described in my csl are supported, e.g. et. al. and probably others.
4. The author-year style needs name disambiguation somehow.
5. Next step, hyperlinking in html.

** Bibliography
bibliographystyle:unsrt
bibliography:~/Dropbox/bibliography/references.bib

