* Word-based diffs for org-mode
  :PROPERTIES:
  :categories: orgmode
  :END:

When we write manuscripts we often want or need to see how one version differs from another. latexdiff is pretty good for this, and today we consider how to use it when your org-file is in git. It turns out we can use git to retrieve the old versions for comparison.

#+BEGIN_SRC sh
git hist
#+END_SRC

#+RESULTS:
: * 4ff3b06 Wed Jan 6 13:32:32 2016 | initial commit (HEAD -> master) [John Kitchin]

You can see above, at the time I ran the command there was one commit. As we develop the manuscript, we periodically export the result to see how it looks. At some point, all the changes should be committed /including the tex file/. We will use the different versions of the org and tex files to generate latexdiffs.

** Generating diffs
Supposing you have a commit that represents some interesting point in the past, e.g. a submitted version, or the last edits made by a collaborator, here is how we generate a diff of the changes between the current version and that version.

First, check out your history. We will compare the current version to the commit =6f9a77a=.

#+BEGIN_SRC sh
git hist
#+END_SRC

#+RESULTS:
: * 6f9a77a Wed Jan 6 13:37:03 2016 | successful build. we will compare to this version later. (HEAD -> master) [John Kitchin]
: * 26fdf5c Wed Jan 6 13:34:20 2016 | new files added, tex and pdf [John Kitchin]
: * 4ff3b06 Wed Jan 6 13:32:32 2016 | initial commit [John Kitchin]

#+BEGIN_SRC sh
git diff --color-words  --word-diff=plain 6f9a77a -- latex-diff-org.org
#+END_SRC

** Generating the latexdiff

Run this in a bash shell (it doesn't work for me in org-mode I suppose because it is using sh, not bash). I find latexdiff somewhat on the fragile side, for example you cannot make changes in section headings or the latexdiff result won't compile. So we ignore those commands below. Somewhat unfortunate, but livable I suppose.

#+BEGIN_SRC sh
latexdiff --exclude-textcmd="section,subsection" <(git show 6f9a77a:latex-diff-org.tex) latex-diff-org.tex > diff.tex
#+END_SRC

#+RESULTS:

It works like this, however.
#+BEGIN_SRC emacs-lisp
(shell-command "latexdiff --exclude-textcmd=\"section,subsection\" <(git show 6f9a77a:latex-diff-org.tex) latex-diff-org.tex > diff.tex")
#+END_SRC

#+RESULTS:
: 0

Now compile the diff to get the pdf:

#+BEGIN_SRC sh
pdflatex -shell-escape diff.tex
pdflatex -shell-escape diff.tex
#+END_SRC


** A "convenient" function
So, we might as well get ourselves a convenient function for that. Helm is my goto selector, so here we grab some candidates based on the commits.

#+BEGIN_SRC emacs-lisp :results code
(mapcar (lambda (s)
	  (let ((commit (nth 1 (split-string s)))
		msg)
	  (string-match "|.*$" s)
	  (cons (concat commit " " (match-string 0 s)) commit)))
	(split-string (shell-command-to-string "git hist") "\n"))
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(("6f9a77a | successful build. we will compare to this version later. (HEAD -> master) [John Kitchin]" . "6f9a77a")
 ("26fdf5c | new files added, tex and pdf [John Kitchin]" . "26fdf5c")
 ("4ff3b06 | initial commit [John Kitchin]" . "4ff3b06"))
#+END_SRC

Here is the new function that calls helm to select a commit, and then runs our latexdiff function.

#+BEGIN_SRC emacs-lisp
(defun latexdiff (commit)
  "Export to LaTeX and do a latexdiff from the version in COMMIT."
  (save-buffer)
  (let* ((fname (org-latex-export-to-latex))
	 (cmd (format
	       "latexdiff --exclude-textcmd=\"section,subsection\" <(git show %s:%s) %s > diff.tex"
	       commit fname fname)))
    (message cmd)

    (shell-command cmd)
    (shell-command "pdflatex -shell-escape -interaction nonstopmode diff.tex")
    (shell-command "pdflatex -shell-escape -interaction nonstopmode diff.tex")
    (org-open-file "diff.pdf")))

(helm :sources `((name . "commits")
		 (candidates . ,(mapcar (lambda (s)
					 (let ((commit (nth 1 (split-string s)))
					       msg)
					   (string-match "|.*$" s)
					   (cons (concat commit " " (match-string 0 s)) commit)))
				       (split-string (shell-command-to-string "git hist") "\n")))
		 (action . (lambda (commit)
			     (latexdiff commit)))))
#+END_SRC

#+RESULTS:

It works, but it is probably limited to tex files in the root git directory.
