* org-ref meets hydra
  :PROPERTIES:
  :categories: emacs
  :date:     2015/02/20 21:17:20
  :updated:  2015/02/20 21:17:20
  :END:
I am enjoying learning about [[https://github.com/abo-abo/hydra][abo-abo/hydra]], which is a nice package for making minibuffer menus to run commands. It is light-weight solution that does not mess up your window too much, and it is easier to use than any home-grown solution I have made in the past. Here is a simple little code that gives me three options when I press "zz" quickly (a key-chord). I can press "c" to put in a cite link using helm, "r" to insert a ref link using helm, and "l" to insert a new label. Any other key just cancels the menu. One thing to remember ("zz"), and hints for the rest!

#+BEGIN_SRC emacs-lisp
(require 'hydra)
(setq hydra-is-helpful t)

(require 'key-chord)
(key-chord-mode 1)
(key-chord-define-global
 "zz"
 (defhydra org-ref-hydra ()
   "org-ref"
   ("c" org-ref-helm-insert-cite-link "cite")
   ("r" org-ref-helm-insert-ref-link "ref")
   ("l" org-ref-helm-insert-label-link "label")
   ("R" org-ref "org-ref")))
#+END_SRC

#+RESULTS:
: org-ref-hydra/body

Pretty nice. Check out the nice hydra interface to [[https://github.com/jkitchin/jmax/blob/master/words.el][words.el]]. A simple press of "ww" gets you easy access to single key presses of all the nice words functions. What would you hydra for?