* New publication in JACS
  :PROPERTIES:
  :categories: news, publication
  :date:     2014/04/07 21:08:42
  :updated:  2014/04/07 21:08:42
  :END:
*Electrocatalytic Oxygen Evolution with an Immobilized TAML Activator*

Ethan L. Demeter, Shayna L. Hilburg, Newell R. Washburn, Terrence J. Collins, and John R. Kitchin

Iron complexes of tetra-amido macrocyclic ligands are important members of the suite of oxidation catalysts known as TAML activators. TAML activators are known to be fast homogeneous water oxidation (WO) catalysts, producing oxygen in the presence of chemical oxidants, e.g., ceric ammonium nitrate. These homogeneous systems exhibited low turnover numbers (TONs). Here we demonstrate immobilization on glassy carbon and carbon paper in an ink composed of the prototype TAML activator, carbon black, and Nafion and the subsequent use of this composition in heterogeneous electrocatalytic WO. The immobilized TAML system is shown to readily produce O2 with much higher TONs than the homogeneous predecessors.

http://pubs.acs.org/doi/full/10.1021/ja5015986

Congratulations Ethan!
