* New publication - Enumeration of surface site nuclearity and shape in a database of intermetallic low-index surface facets
:PROPERTIES:
:categories: news,publication
:date:     2025/02/02 07:49:45
:updated:  2025/02/02 07:49:45
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/02/New-publication---Enumeration-of-surface-site-nuclearity-and-shape-in-a-database-of-intermetallic-low-index-surface-facets.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/02/New-publication---Enumeration-of-surface-site-nuclearity-and-shape-in-a-database-of-intermetallic-low-index-surface-facets/index.html
:END:

Imagine if we could design catalysts with atomic precision, selecting exactly where and how the active sites appear on a surface. That’s the premise of a new study by Sharma et al., which introduces an open-source tool to systematically map and classify catalytic surface sites in intermetallic materials. By analyzing 29,002 low-index surfaces across various metal combinations, the tool identifies “nuclearity”—the number of active atoms in a site—and their geometrical arrangements. This capability helps researchers pinpoint materials with atomic-level control over reactivity and selectivity, paving the way for more efficient and tailored catalysts. The study provides a roadmap for rational catalyst design by linking surface site structures to thermodynamic stability and crystal properties, making it easier to predict which materials will perform best. The Surface Nuclearity Calculator is now freely available, opening the door to further exploration of how surface atomic arrangements shape catalytic behavior.

Unnatti Sharma; Angela Nguyen; John Robert Kitchin; Zachary W Ulissi; Michael J Janik, Enumeration of surface site nuclearity and shape in a database of intermetallic low-index surface facets, J. Catalysis, 440, 115795 (2024). https://doi.org/10.1016/j.jcat.2024.115795.

#+BEGIN_SRC bibtex
@article{sharma-2024-enumer-surfac,
  author =	 {Unnatti Sharma and Angela Nguyen and John R. Kitchin and
                  Zachary W. Ulissi and Michael J. Janik},
  title =	 {Enumeration of Surface Site Nuclearity and Shape in a Database
                  of Intermetallic Low-Index Surface Facets},
  journal =	 {Journal of Catalysis},
  volume =	 440,
  pages =	 115795,
  year =	 2024,
  doi =		 {10.1016/j.jcat.2024.115795},
  url =		 {http://dx.doi.org/10.1016/j.jcat.2024.115795},
}
#+END_SRC

altmetric:10.1016/j.jcat.2024.115795

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35111555/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
