* Professor Kitchin awarded the Philip L. Dowd Fellowship Award 
  :PROPERTIES:
  :categories: news
  :date:     2014/02/28 13:44:31
  :updated:  2014/02/28 13:44:31
  :END:
The [[https://www.cit.cmu.edu/faculty_staff/faculty_awards/dowd.html][Dowd Fellowship]] is awarded to a faculty member in engineering to recognize educational contributions and to encourage the undertaking of an educational project such as textbook writing, educational technology development, laboratory experience improvement, educational software, or course and curriculum development.

Professor Kitchin was recognized for his work in creating the [[http://kitchingroup.cheme.cmu.edu/dft-book][dft-book]], [[http://kitchingroup.cheme.cmu.edu][pycse]], and their integration into courses. These resources notably integrate technical narrative text, equation, images along with code and the output. He is continuing to develop these resources and similar materials for a new Master's course in chemical reaction engineering.

