* Altmetric API

Altmetric provides an [[http://api.altmetric.com][API]] to access data about the things they monitor.


I am most interested in the DOI API: http://api.altmetric.com/docs/call_doi.html

Here is an example of retrieving some data for doi:10.1007/s00799-016-0173-7. Note that not all data is available in the json you get back, e.g. if there are no google plus counts, it is not listed in the json data.

#+BEGIN_SRC python :results output org drawer
import pprint
import requests

pp = pprint.PrettyPrinter()

req = requests.get('http://api.altmetric.com/v1/doi/10.1007/s00799-016-0173-7')
pp.pprint(req.json())
#+END_SRC

#+RESULTS:
:RESULTS:
{'added_on': 1465911575,
 'altmetric_id': 8729145,
 'altmetric_jid': '4f6fa4ed3cf058f610002bbc',
 'cited_by_accounts_count': 2,
 'cited_by_posts_count': 2,
 'cited_by_tweeters_count': 2,
 'cohorts': {'pub': 1, 'sci': 1},
 'context': {'all': {'count': 5357011,
                     'higher_than': 2698315,
                     'mean': 6.2704072827961,
                     'pct': 50,
                     'rank': 2606877},
             'journal': {'count': 100,
                         'higher_than': 32,
                         'mean': 6.2053131313131,
                         'pct': 32,
                         'rank': 68},
             'similar_age_3m': {'count': 171806,
                                'higher_than': 92303,
                                'mean': 10.720463048223,
                                'pct': 53,
                                'rank': 77157},
             'similar_age_journal_3m': {'count': 7,
                                        'higher_than': 1,
                                        'mean': 10.268333333333,
                                        'pct': 14,
                                        'rank': 6}},
 'details_url': 'http://www.altmetric.com/details.php?citation_id=8729145',
 'doi': '10.1007/s00799-016-0173-7',
 'history': {'1d': 0,
             '1m': 0,
             '1w': 0,
             '1y': 1.35,
             '2d': 0,
             '3d': 0,
             '3m': 1.35,
             '4d': 0,
             '5d': 0,
             '6d': 0,
             '6m': 1.35,
             'at': 1.35},
 'images': {'large': 'https://altmetric-badges.a.ssl.fastly.net/?size=180&score=2&types=tttttttt',
            'medium': 'https://altmetric-badges.a.ssl.fastly.net/?size=100&score=2&types=tttttttt',
            'small': 'https://altmetric-badges.a.ssl.fastly.net/?size=64&score=2&types=tttttttt'},
 'is_oa': False,
 'issns': ['1432-1300'],
 'journal': 'International Journal on Digital Libraries',
 'last_updated': 1465914231,
 'published_on': 1465603200,
 'publisher_subjects': [{'name': 'Library And Information Studies',
                         'scheme': 'era'},
                        {'name': 'Computer Science', 'scheme': 'springer'},
                        {'name': 'Database Management', 'scheme': 'springer'},
                        {'name': 'Information Systems and Communication '
                                 'Service',
                         'scheme': 'springer'}],
 'readers': {'citeulike': '0', 'connotea': '0', 'mendeley': '2'},
 'readers_count': 2,
 'schema': '1.5.4',
 'scopus_subjects': ['Social Sciences'],
 'score': 1.35,
 'title': 'Automating data sharing through authoring tools',
 'type': 'article',
 'url': 'http://dx.doi.org/10.1007/s00799-016-0173-7'}
:END:

From that data, we can extract quite a bit of useful information.

#+BEGIN_SRC python :results output org drawer
import json
import requests

req = requests.get('http://api.altmetric.com/v1/doi/10.1007/s00799-016-0173-7')
j = req.json()

print(j.get('cited_by_tweeters_count', 0))
print(j.get('cited_by_fbwalls_count', 0))  # facebook
print(j.get('cited_by_msm_count', 0))  # news I think
print(j.get('cited_by_feeds_count', 0))  # blogs I think
print(j.get('cited_by_posts_count', 0))  # blogs I think
print(j.get('cited_by_gplus_count', 0))  # Google+
print(j['is_oa'])  # open access
print(j['score'])  # Attention score
print(j['cohorts']['pub'])  # public
print(j['cohorts']['sci'])  # scientists
print(j['readers'])
print(j['url'])
print(j['details_url'])

print(j['context']['all']['pct'])  # All outputs
print(j['context']['journal']['pct'])
print(j['context']['similar_age_3m']['pct'])  # compared to similar age
print(j['context']['similar_age_journal_3m']['pct'])  # similar age and journal
#+END_SRC

#+RESULTS:
:RESULTS:
2
0
0
0
2
0
False
1.35
1
1
{'mendeley': '2', 'connotea': '0', 'citeulike': '0'}
http://dx.doi.org/10.1007/s00799-016-0173-7
http://www.altmetric.com/details.php?citation_id=8729145
50
32
53
14
:END:



** Paper by Meagan Mauter
#+BEGIN_SRC python :results output org drawer
import pprint
import requests

pp = pprint.PrettyPrinter()

req = requests.get('http://api.altmetric.com/v1/doi/10.1021/es5060989')
pp.pprint(req.json())
#+END_SRC

#+RESULTS:
:RESULTS:
{'abstract': 'Secondary application of unconverted heat produced during '
             'electric power generation has the potential to improve the '
             'life-cycle fuel efficiency of the electric power industry and '
             'the sectors it serves. This work quantifies the residual heat '
             '(also known as waste heat) generated by U.S. thermal power '
             'plants and assesses the intermittency and transport issues that '
             'must be considered when planning to utilize this heat. Combining '
             'Energy Information Administration plant-level data with '
             'literature-reported process efficiency data, we develop '
             'estimates of the unconverted heat flux from individual U.S. '
             'thermal power plants in 2012. Together these power plants '
             'discharged an estimated 18.9 billion GJth of residual heat in '
             '2012, 4% of which was discharged at temperatures greater than 90 '
             '°C. We also characterize the temperature, spatial distribution, '
             'and temporal availability of this residual heat at the plant '
             'level and model the implications for the technical and economic '
             'feasibility of its end use. Increased implementation of flue gas '
             'desulfurization technologies at coal-fired facilities and the '
             'higher quality heat generated in the exhaust of natural gas fuel '
             'cycles are expected to increase the availability of residual '
             'heat generated by 10.6% in 2040.',
 'added_on': 1434777401,
 'altmetric_id': 4191302,
 'altmetric_jid': '4f6fa4eb3cf058f6100027ef',
 'cited_by_accounts_count': 5,
 'cited_by_fbwalls_count': 1,
 'cited_by_gplus_count': 1,
 'cited_by_posts_count': 5,
 'cited_by_tweeters_count': 3,
 'cohorts': {'pub': 1, 'sci': 2},
 'context': {'all': {'count': 4785528,
                     'higher_than': 2984447,
                     'mean': 5.72647012043,
                     'pct': 62,
                     'rank': 1783986},
             'journal': {'count': 4919,
                         'higher_than': 2678,
                         'mean': 9.1540976006507,
                         'pct': 54,
                         'rank': 2224},
             'similar_age_3m': {'count': 173023,
                                'higher_than': 112932,
                                'mean': 8.4118428754727,
                                'pct': 65,
                                'rank': 59051},
             'similar_age_journal_3m': {'count': 122,
                                        'higher_than': 73,
                                        'mean': 8.8715371900826,
                                        'pct': 59,
                                        'rank': 49}},
 'details_url': 'http://www.altmetric.com/details.php?citation_id=4191302',
 'doi': '10.1021/es5060989',
 'history': {'1d': 0,
             '1m': 0,
             '1w': 0,
             '1y': 2.75,
             '2d': 0,
             '3d': 0,
             '3m': 0,
             '4d': 0,
             '5d': 0,
             '6d': 0,
             '6m': 0,
             'at': 2.75},
 'images': {'large': 'https://altmetric-badges.a.ssl.fastly.net/?size=180&score=3&types=tttttffg',
            'medium': 'https://altmetric-badges.a.ssl.fastly.net/?size=100&score=3&types=tttttffg',
            'small': 'https://altmetric-badges.a.ssl.fastly.net/?size=64&score=3&types=tttttffg'},
 'is_oa': False,
 'issns': ['1520-5851'],
 'journal': 'Environmental Science & Technology',
 'last_updated': 1440430714,
 'pmid': '26061407',
 'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
 'readers': {'citeulike': '0', 'connotea': '0', 'mendeley': '13'},
 'readers_count': 13,
 'schema': '1.5.4',
 'scopus_subjects': ['Chemistry', 'Environmental Science', 'Physical Sciences'],
 'score': 2.75,
 'subjects': ['environmentalhealth'],
 'title': 'Quantity, Quality, and Availability of Waste Heat from United '
          'States Thermal Power Generation',
 'tq': ['Quantity, quality, and availability of waste heat from U.S. thermal '
        '#power generation,',
        'Technoeconomically feasible transport distance of residual heat from '
        'US Thermal e Generation'],
 'type': 'article',
 'url': 'http://dx.doi.org/10.1021/es5060989'}
:END:

** Gellman N Chem paper

#+BEGIN_SRC python :results output org drawer
import pprint
import requests

pp = pprint.PrettyPrinter()

req = requests.get('http://api.altmetric.com/v1/doi/10.1038/nchem.2250')
pp.pprint(req.json())
#+END_SRC

#+RESULTS:
:RESULTS:
{'abstract': 'The homochirality of biomolecules is a signature of life on '
             'Earth and has significant implications in, for example, the '
             'production of pharmaceutical compounds. It has been suggested '
             'that biomolecular homochirality may have arisen from the '
             'amplification of a spontaneously formed small enantiomeric '
             'excess (e.e.). Many minerals exhibit naturally chiral surfaces '
             'and so adsorption has been proposed as one possible mechanism '
             'for such an amplification of e.e. Here we show that when '
             'gas-phase mixtures of D- and L-aspartic acid are exposed to an '
             'achiral Cu(111) surface, a small e.e. in the gas phase, e.e.g, '
             'leads to an amplification of the e.e. on the surface, e.e.s, '
             'under equilibrium conditions. Adsorption-induced amplification '
             'of e.e. does not require a chiral surface. The dependence of '
             'e.e.s on e.e.g has been modelled successfully using a '
             'Langmuir-like adsorption isotherm that incorporates the '
             'formation of homochiral adsorbate clusters on the surface.',
 'added_on': 1430845955,
 'altmetric_id': 3969782,
 'altmetric_jid': '4f6fa52f3cf058f610004265',
 'cited_by_accounts_count': 22,
 'cited_by_fbwalls_count': 1,
 'cited_by_feeds_count': 1,
 'cited_by_msm_count': 2,
 'cited_by_posts_count': 23,
 'cited_by_tweeters_count': 18,
 'cohorts': {'doc': 1, 'pub': 8, 'sci': 9},
 'context': {'all': {'count': 5310772,
                     'higher_than': 5155818,
                     'mean': 6.2319383445464,
                     'pct': 97,
                     'rank': 154865},
             'journal': {'count': 1418,
                         'higher_than': 1164,
                         'mean': 22.292201834862,
                         'pct': 82,
                         'rank': 254},
             'similar_age_3m': {'count': 161999,
                                'higher_than': 153551,
                                'mean': 9.5255127841085,
                                'pct': 94,
                                'rank': 8443},
             'similar_age_journal_3m': {'count': 65,
                                        'higher_than': 47,
                                        'mean': 24.013,
                                        'pct': 72,
                                        'rank': 18}},
 'details_url': 'http://www.altmetric.com/details.php?citation_id=3969782',
 'doi': '10.1038/nchem.2250',
 'history': {'1d': 0,
             '1m': 0,
             '1w': 0,
             '1y': 0.5,
             '2d': 0,
             '3d': 0,
             '3m': 0,
             '4d': 0,
             '5d': 0,
             '6d': 0,
             '6m': 0,
             'at': 33.55},
 'images': {'large': 'https://altmetric-badges.a.ssl.fastly.net/?size=180&score=34&types=mbtttttf',
            'medium': 'https://altmetric-badges.a.ssl.fastly.net/?size=100&score=34&types=mbtttttf',
            'small': 'https://altmetric-badges.a.ssl.fastly.net/?size=64&score=34&types=mbtttttf'},
 'is_oa': False,
 'issns': ['1755-4349'],
 'journal': 'Nature Chemistry',
 'last_updated': 1451923092,
 'pmid': '25991532',
 'published_on': 1430697600,
 'publisher_subjects': [{'name': 'Surface chemistry', 'scheme': 'npg'},
                        {'name': 'Chemical Sciences', 'scheme': 'era'}],
 'readers': {'citeulike': '0', 'connotea': '0', 'mendeley': '29'},
 'readers_count': 29,
 'schema': '1.5.4',
 'scopus_subjects': ['Chemistry', 'Chemical Engineering', 'Physical Sciences'],
 'score': 33.55,
 'subjects': ['chemistry'],
 'title': 'Adsorption-induced auto-amplification of enantiomeric excess on an '
          'achiral surface',
 'tq': ['Enantioenrichment of chiral molecules through adsorption on an '
        'achiral surface',
        'Very cool Nat Chem paper by Prof. Gellman of',
        '@NatureChemistry:Enantioenrichment of chiral molecules through '
        'adsorption on achiral surface'],
 'type': 'article',
 'url': 'http://dx.doi.org/10.1038/nchem.2250'}
:END:


#+BEGIN_SRC python :results output org drawer
import pprint
import requests

pp = pprint.PrettyPrinter()

req = requests.get('http://api.altmetric.com/v1/doi/10.1038/nchem.2250')
j = req.json()

print(j['context']['all']['pct'])  # All outputs
print(j['context']['journal']['pct'])
print(j['context']['similar_age_3m']['pct'])  # compared to similar age
print(j['context']['similar_age_journal_3m']['pct'])  # similar age and journal
#+END_SRC

#+RESULTS:
:RESULTS:
97
82
94
72
:END:

** An example with no mentions
#+BEGIN_SRC python :results output org drawer
import pprint
import requests

pp = pprint.PrettyPrinter()

req = requests.get('http://api.altmetric.com/v1/doi/10.1016/j.jcis.2015.08.055')
print(req.status_code)
#+END_SRC

#+RESULTS:
:RESULTS:
404
:END:


** orcid

#+BEGIN_SRC python :results value
import requests
import json

resp = requests.get("http://pub.orcid.org/0000-0003-2625-9232/orcid-works",
                    headers={'Accept':'application/orcid+json'})

results = resp.json()

DOIS = []
for i, result in enumerate(results['orcid-profile']['orcid-activities']
                           ['orcid-works']['orcid-work']):
    ext_ids = result['work-external-identifiers']['work-external-identifier']
    for eid in ext_ids:
        
        if eid['work-external-identifier-type'] == 'DOI':
            doi = eid['work-external-identifier-id']['value']
        else:
            doi = None

        DOIS += [[doi]]

return DOIS
#+END_SRC

#+RESULTS:
| 10.1016/j.susc.2015.10.001                       |
| 10.1016/j.susc.2015.05.007                       |
| 10.1063/1.4916823                                |
| 10.1063/1.4914093                                |
| 10.1021/jp511426q                                |
| 10.1063/1.4914093                                |
| 10.1016/j.susc.2015.02.011                       |
| 10.1063/1.4914093                                |
| None                                             |
| 10.1021/cs501585k                                |
| None                                             |
| 10.1016/j.susc.2015.02.011                       |
| None                                             |
| 10.1021/jp511426q                                |
| None                                             |
| 10.1021/jp508805h                                |
| 10.1016/j.catcom.2013.10.028                     |
| 10.1016/j.catcom.2013.10.028                     |
| 10.1021/ja5015986                                |
| 10.1021/am4059149                                |
| 10.1007/s11244-013-0166-3                        |
| None                                             |
| 10.1016/j.catcom.2013.10.028                     |
| None                                             |
| 10.1039/c3ra47097k                               |
| None                                             |
| 10.1039/c3ra47097k                               |
| 10.1021/jp508805h                                |
| None                                             |
| 10.1021/am4059149                                |
| None                                             |
| 10.1021/ja5015986                                |
| None                                             |
| 10.1021/jp507957n                                |
| None                                             |
| 10.1021/jp507957n                                |
| 10.1007/s11244-013-0166-3                        |
| 10.1021/ie400582a                                |
| None                                             |
| None                                             |
| [[http://dx.doi.org/10.1016/j.molstruc.2013.01.046]] |
| 10.1021/ie400582a                                |
| None                                             |
| None                                             |
| [[http://dx.doi.org/10.1016/j.ijggc.2013.06.020]]    |
| 10.1021/ie301419q                                |
| 10.1021/cs3002644                                |
| 10.2172/1149701                                  |
| None                                             |
| None                                             |
| 10.1016/j.pecs.2012.03.003                       |
| None                                             |
| 10.1111/j.1551-2916.2012.05236.x                 |
| None                                             |
| 10.1111/j.1551-2916.2012.05236.x                 |
| None                                             |
| 10.1021/cs3002644                                |
| None                                             |
| 10.1007/s11244-012-9808-0                        |
| None                                             |
| 10.1007/s11244-012-9808-0                        |
| None                                             |
| None                                             |
| None                                             |
| 10.1021/ie300452c                                |
| 10.1021/ie300452c                                |
| None                                             |
| None                                             |
| 10.1063/1.4746117                                |
| None                                             |
| 10.1063/1.4746117                                |
| 10.1039/9781849734776-00083                      |
| None                                             |
| 10.1039/9781849734776-00083                      |
| None                                             |
| 10.1021/ie301419q                                |
| None                                             |
| None                                             |
| None                                             |
| 10.1002/cctc.201000397                           |
| None                                             |
| 10.1002/cctc.201000397                           |
| None                                             |
| None                                             |
| 10.1149/1.3570235                                |
| None                                             |
| 10.1021/cs200039t                                |
| None                                             |
| 10.1021/cs200039t                                |
| None                                             |
| 10.1063/1.3631948                                |
| None                                             |
| 10.1063/1.3631948                                |
| None                                             |
| 10.1063/1.3561287                                |
| None                                             |
| 10.1063/1.3561287                                |
| None                                             |
| 10.1002/cssc.201000056                           |
| 10.1016/j.fuel.2009.11.036                       |
| 10.1080/08927022.2010.481794                     |
| 045414\n10.1103/PhysRevB.82.045414               |
| None                                             |
| 10.1016/j.fuel.2009.11.036                       |
| None                                             |
| 10.1080/08927022.2010.481794                     |
| None                                             |
| None                                             |
| 10.1149/1.3432440                                |
| None                                             |
| None                                             |
| 10.1149/1.3432440                                |
| 10.1002/cssc.201000056                           |
| None                                             |
| None                                             |
| 10.1080/08927020902833137                        |
| None                                             |
| None                                             |
| 10.1080/08927020902833137                        |
| 10.1080/08927020902833129                        |
| None                                             |
| None                                             |
| 10.1080/08927020902833129                        |
| None                                             |
| 124710\n10.1063/1.3096964                        |
| None                                             |
| 10.1016/j.susc.2009.01.021                       |
| 10.1016/j.susc.2009.01.021                       |
| None                                             |
| None                                             |
| 246102\n10.1103/PhysRevLett.103.246102           |
| None                                             |
| 205412\n10.1103/PhysRevB.79.205412               |
| None                                             |
| 10.1016/j.jcat.2008.11.020                       |
| None                                             |
| None                                             |
| 10.1016/j.jcat.2008.11.020                       |
| None                                             |
| None                                             |
| 10.1117/12.776303                                |
| None                                             |
| 10.1117/12.776303                                |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| 10.1039/b608782p                                 |
| 075437\n10.1103/PhysRevB.77.075437               |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| None                                             |
| 10.1149/1.2358292                                |
| 10.1149/1.2358292                                |
| None                                             |
| 10.1149/1.1856988                                |
| None                                             |
| None                                             |
| 10.1149/1.1856988                                |
| 10.1016/j.cattod.2005.04.008                     |
| None                                             |
| None                                             |
| 10.1016/j.cattod.2005.04.008                     |
| None                                             |
| None                                             |
| None                                             |
| 156801\n10.1103/PhysRevLett.93.156801            |
| 10.1021/jp047349j                                |
| None                                             |
| 10.1021/jp047349j                                |
| None                                             |
| 10.1063/1.1737365                                |
| None                                             |
| None                                             |
| 10.1063/1.1737365                                |
| None                                             |
| 10.1016/j.susc.2003.09.007                       |
| 10.1016/j.susc.2003.09.007                       |
| None                                             |
| None                                             |
| 10.1016/j.susc.2003.08.041                       |
| 10.1016/j.susc.2003.08.041                       |
| None                                             |
| None                                             |
| 10.1016/s0039-6028(02)02679-1                    |
| 10.1016/S0039-6028(02)02679-1                    |
| None                                             |
| 10.1073/pnas.072514399                           |
| None                                             |
| None                                             |
| 10.1073/pnas.072514399                           |
| None                                             |
| 10.1021/jo00117a004                              |
| None                                             |
| None                                             |
| 10.1016/j.pecs.2012.03.003                       |

