* Installing and configuring blogofile
[[http://docs.blogofile.com/en/latest/]]

** installing blogofile
First, we install the python modules we need.
#+BEGIN_SRC sh
pip install Blogofile
pip install Blogofile-blog
#+END_SRC

** setup the site
#+BEGIN_SRC sh
blogofile init blogofile-jkitchin.github.com blog

cd blogofile-jkitchin.github.com
git init
git add .
git commit -m "initial commit"

echo _site > .gitignore
git add .gitignore
git commit .gitignore -m "add .gitignore"
#+END_SRC
When you are in the blogofile directory, you will be on the source branch of the repository.

Now, run 

#+BEGIN_SRC sh
blogofile build
#+END_SRC

That creates the _site directory, but it is not under vc with git yet because we have it in the .gitignore file. When we are ready to deploy, we will copy everything from _site to _deploy. 

We will create a _deploy directory which will be under git, but on the master branch.  We will push content from the master branch in the _deploy directory to github.

Now:
#+BEGIN_SRC sh
mkdir _deploy
cd _deploy
git init
git add .
git commit -m "site initial commit"
#+END_SRC

For now this is all we do to configure the version control. We have a working blog site that needs to be configured with our information.  

Next, I am going to configure the two git repositories to point to my github repository.

git config remote.origin.url git@github.com:jkitchin/jkitchin.github.com
