#!/bin/sh

:;exec emacs -batch  -l ~/Dropbox/kitchingroup/jmax/init.el -l "$0" "$@"

;; usage: export-org-section section-id org-file

;; now goto, narrow and export the section
(let ((section-id (pop command-line-args-left))
      (org-file (pop command-line-args-left)))
  (print (format "Opened %s" org-file))
  (find-file (expand-file-name org-file))
  (org-open-link-from-string (format "[[#%s]]" section-id))
  (org-narrow-to-subtree)
  (org-latex-export-to-pdf)
)
