* Zhongnan receives the Bradford and Diane Smith Graduate Fellowship
  :PROPERTIES:
  :date:     2013/01/03 09:00:00
  :categories: news
  :updated:  2013/02/28 10:53:32
  :END:
Congratulations Zhongnan!
* New group members to the Kitchin Research group for 2013!
  :PROPERTIES:
  :categories: news
  :date:     2013/01/01 09:00:00
  :updated:  2013/02/28 10:52:26
  :END:

Bin Liu has joined us as a postdoc from Argonne National Lab. He will be working on superalloy oxidation.

Steve Illes has joined us as a PhD student from Purdue University. He will be using Raman spectroscopy to investigate electrode surfaces under oxygen evolution conditions.

Jacob Boes has also joined us as a PhD student. He will be using DFT to study multicomponent alloys.

Prateek Mehta has joined the group as an MS student. He will be working on predicting oxide polymorph stability.

* Professor Kitchin was awarded the Presidential Early Career Award for Scientists and Engineers (PECASE)
  :PROPERTIES:
  :date:     2012/07/15 09:00:00
  :categories: news
  :updated:  2013/02/28 10:41:19
  :END:
[[http://www.cmu.edu/homepage/society/2012/summer/pecase-winners.shtml][web announcement]]
* Sneha Akhade completed her MS
  :PROPERTIES:
  :categories: news
  :date:     2012/05/15 09:00:00
  :updated:  2013/02/28 10:39:15
  :END:
Her thesis was titled "Effect of strain on the electronic structure and reactivity of 3d Perovskite surfaces.
* Rich Alesi completed his PhD!
  :PROPERTIES:
  :categories: news
  :date:     2012/05/15 09:00:00
  :updated:  2013/02/28 10:38:06
  :END:
His thesis was titled: "Amine based sorbents: developing a quantitative framework for understanding CO2 capture". Rich is now working at Intel.

* James Landon successfully defends PhD dissertation
  :PROPERTIES:
  :categories: news
  :date:     2011/04/04 09:00:00
  :updated:  2013/02/28 09:15:32
  :END:

April 4, 2011 James will be joining the Center for Applied Energy Research in Kentucky this summer. Congratulations! 

* Four new publications!
  :PROPERTIES:
  :date:     2011/03/17 09:00:00
  :categories: news
  :updated:  2013/02/28 10:35:57
  :END:

We recently published papers in the areas of sufur tolerance, oxygen evolution, adsorption and oxide synthesis.

29.  N. Inoglu, and J.R. Kitchin, Identification of sulfur tolerant bimetallic surfaces using DFT parameterized models and atomistic thermodynamics, ACS Catalysis, 1, 399-407 (2011). link.


28.  Isabela C. Man, Hai-Yan Su, Federico Calle-Vallejo, Heine A. Hansen, Jose I. Martinez, Nilay G. Inoglu,  John Kitchin, Thomas F. Jaramillo, Jens K. Norskov, Jan Rossmeisl*, Universality in Oxygen Evolution Electro-Catalysis on Oxide Surfaces, accepted ChemCatChem (Jan 2011).

 
27.  Spencer D. Miller, Nilay Inoglu, and John R. Kitchin*, Configurational correlations in the coverage dependent adsorption energies of oxygen atoms on late transition metal fcc (111) surfaces, accepted J. Chemical Physics, 134, 104709 (2011). link.

 

26.  R. Chao, J. R. Kitchin, K. Gerdes, E. M. Sabolsky, and P. A. Salvador, Preparation of Mesoporous La0.8Sr0.2MnO3 Infiltrated Coatings in Porous SOFC Cathodes Using Evaporation-Induced Self-Assembly Methods, ECS Transactions (Accepted January 2011).
* Spencer Miller successfully defends his PhD dissertation!
  :PROPERTIES:
  :categories: news
  :date: 2011/03/17 09:00:00
  :updated:  2013/02/28 10:36:02
  :END:

Congratulations to Spencer for defending his dissertation entitled "Towards an Understanding of Coverage Dependent Atomic Adsorption on Late Transition Metals". The defense occurred on March 9, 2011. 

*  Nilay Inoglu has successfully defended her PhD dissertation
  :PROPERTIES:
  :categories: news
  :date: 2011/03/17 09:00:00
  :updated:  2013/02/28 10:36:02
  :END:
Congratulations to Nilay for successfully defending her dissertation entitled "Design of Sulfur Tolerant Transition Metal Catalysts and Oxide Based Oxygen Evolution Electrocatalysts". She defended on March 17, 2011.

Nilay will be joining Exxon Mobil later this year.
