* New paper on SO2 tolerance of CO2 sorbent accepted in I&ECR
  :PROPERTIES:
  :categories: news
  :date:     2013/07/09 07:16:49
  :updated:  2013/07/09 07:16:49
  :END:
Our paper "Effects of O2 and SO2 on the capture capacity of a primary-amine based polymeric CO2 sorbent" by Alexander Hallenbeck and John R. Kitchin was accepted today in Industrial & Engineering Chemistry Research. In this paper we showed that the ion exchange resin OC1065 is  susceptible to poisoning by SO2, but that it can be partially chemically regenerated. It can also be damaged by long term exposure to air at elevated temperatures.

* New paper accepted on CO_2 capture simulation
  :PROPERTIES:
  :date:     2013/06/25 04:54:00
  :categories: news
  :updated:  2013/07/08 16:33:21
  :END:
Our manuscript titled "Comparisons of Amine Solvents for Post-combustion CO$_2$ Capture: A Multi-objective Analysis Approach" by Anita Lee, John Eslick, David Miller, and John Kitchin was just accepted in International Journal of Greenhouse Gas Control. In this paper we used a genetic algorithm to find pareto-optimal operating conditions of amine solvent CO2 capture systems that minimize capital cost and parasitic power cost. We compared MEA, DEA and AMP, and found that there are operating conditions where both solvents could be better than MEA.

* Zhongnan Xu receives an ICMR International Research Fellowship
  :PROPERTIES:
  :categories: news
  :date:     2013/05/24 09:41:40
  :updated:  2013/05/24 09:41:40
  :END:
Zhongnan will be visiting the Denmark Technical University to collaborate with Jan Rossmeisl in the next year! This fellowship is supported by the IMI Program of the National Science Foundation under Award No. DMR 08-43934 through UC Santa Barbara. Congratulations Zhongnan!
* Professor Kitchin is attending the 2013 China-America Frontiers of Engineering meeting
  :PROPERTIES:
  :categories: news
  :date:     2013/05/12 16:24:29
  :updated:  2013/05/12 16:37:15
  :END:

This meeting will be held in Beijing, China from May 15 to 17. Here is a description of the meeting from the website:

"CAFOE
2013 China-America Frontiers of Engineering Symposium

From May 15 - 17, the 2013 China-America Frontiers of Engineering will take place in Beijing, China. Sixty of the most promising engineers under the age of 45 from China and the United States will meet for an intensive 2-1/2 day symposium on developments at the cutting edge of engineering technology. The event is intended to facilitate international and cross-disciplinary research collaboration, promote the transfer of new techniques and approaches across disparate engineering fields, and encourage the creation of a transpacific network of world-class engineers."

Professor Kitchin will present his work in CO2 capture, water splitting, computational materials design and computing in engineering at a poster session in this meeting.

This meeting is hosted by the National Academy of Engineering and the Chinese Academy of Engineering. Learn more at  http://www.naefrontiers.org/Symposia/CAFOE.aspx

* Successful PhD Defense for Ethan Demeter
  :PROPERTIES:
  :categories: news
  :date:     2013/04/24 17:00:00
  :updated:  2013/05/12 16:20:58
  :END:
Congratulations to Ethan Demeter for successfully defending his dissertation entitled "The Promotion of Base Metal Catalysts for the Electrochemical Oxygen Evolution Reaction"!

* Successful PhD defense for Anita Lee
  :PROPERTIES:
  :date:     2013/04/26 13:00:00
  :categories: news
  :updated:  2013/05/12 16:20:50
  :END:
Congratulations to Anita Lee for successfully defending her dissertation entitled "A Multi-Scale Approach to Understanding CO2-Solvent Systems for the Development of CO2 Capture Technologies"!

* Two new MS theses completed
  :PROPERTIES:
  :categories: news
  :date:     2013/03/25 19:55:53
  :updated:  2013/03/25 19:55:53
  :END:
Congratulations to Zhizhong Ding and Vivek Vinodan who completed their MS theses! 

Vivek's thesis was on "Modeling chemical looping processes", and he was co-advised with Prof. Ydstie. Zhizhong's thesis was on "Ni-Fe-based oxygen carriers for chemical looping applications" and he was co-advised by Prof. Miller. 
* Matt Curnan received an ICMR International Research Fellowship
  :PROPERTIES:
  :categories: news
  :date:     2012/12/03 09:41:40  
  :updated:  2013/05/24 09:43:35
  :END:
Matt will be visiting the University of Seoul, Korea to collaborate with Jeong Woo Han in the summer of 2013! This fellowship is supported by the IMI Program of the National Science Foundation under Award No. DMR 08-43934 through UC Santa Barbara. Congratulations Matt!
* Zhongnan receives the Bradford and Diane Smith Graduate Fellowship
  :PROPERTIES:
  :date:     2013/01/03 09:00:00
  :categories: news
  :updated:  2013/02/28 11:28:33
  :END:
Congratulations Zhongnan!
* New group members to the Kitchin Research group for 2013!
  :PROPERTIES:
  :categories: news
  :date:     2013/01/01 09:00:00
  :updated:  2013/02/28 10:52:26
  :END:

Bin Liu has joined us as a postdoc from Argonne National Lab. He will be working on superalloy oxidation.

Steve Illes has joined us as a PhD student from Purdue University. He will be using Raman spectroscopy to investigate electrode surfaces under oxygen evolution conditions.

Jacob Boes has also joined us as a PhD student. He will be using DFT to study multicomponent alloys.

Prateek Mehta has joined the group as an MS student. He will be working on predicting oxide polymorph stability.

* Professor Kitchin was awarded the Presidential Early Career Award for Scientists and Engineers (PECASE)
  :PROPERTIES:
  :date:     2012/07/15 09:00:00
  :categories: news
  :updated:  2013/02/28 10:41:19
  :END:
[[http://www.cmu.edu/homepage/society/2012/summer/pecase-winners.shtml][web announcement]]
* Sneha Akhade completed her MS
  :PROPERTIES:
  :categories: news
  :date:     2012/05/15 09:00:00
  :updated:  2013/02/28 10:39:15
  :END:
Her thesis was titled "Effect of strain on the electronic structure and reactivity of 3d Perovskite surfaces.
* Rich Alesi completed his PhD!
  :PROPERTIES:
  :categories: news
  :date:     2012/05/15 09:00:00
  :updated:  2013/02/28 10:38:06
  :END:
His thesis was titled: "Amine based sorbents: developing a quantitative framework for understanding CO2 capture". Rich is now working at Intel.

* James Landon successfully defends PhD dissertation
  :PROPERTIES:
  :categories: news
  :date:     2011/04/04 09:00:00
  :updated:  2013/02/28 09:15:32
  :END:

April 4, 2011 James will be joining the Center for Applied Energy Research in Kentucky this summer. Congratulations! 

* Four new publications!
  :PROPERTIES:
  :date:     2011/03/17 09:00:00
  :categories: news
  :updated:  2013/02/28 10:35:57
  :END:

We recently published papers in the areas of sufur tolerance, oxygen evolution, adsorption and oxide synthesis.

29.  N. Inoglu, and J.R. Kitchin, Identification of sulfur tolerant bimetallic surfaces using DFT parameterized models and atomistic thermodynamics, ACS Catalysis, 1, 399-407 (2011). link.


28.  Isabela C. Man, Hai-Yan Su, Federico Calle-Vallejo, Heine A. Hansen, Jose I. Martinez, Nilay G. Inoglu,  John Kitchin, Thomas F. Jaramillo, Jens K. Norskov, Jan Rossmeisl*, Universality in Oxygen Evolution Electro-Catalysis on Oxide Surfaces, accepted ChemCatChem (Jan 2011).

 
27.  Spencer D. Miller, Nilay Inoglu, and John R. Kitchin*, Configurational correlations in the coverage dependent adsorption energies of oxygen atoms on late transition metal fcc (111) surfaces, accepted J. Chemical Physics, 134, 104709 (2011). link.

 

26.  R. Chao, J. R. Kitchin, K. Gerdes, E. M. Sabolsky, and P. A. Salvador, Preparation of Mesoporous La0.8Sr0.2MnO3 Infiltrated Coatings in Porous SOFC Cathodes Using Evaporation-Induced Self-Assembly Methods, ECS Transactions (Accepted January 2011).
* Spencer Miller successfully defends his PhD dissertation!
  :PROPERTIES:
  :categories: news
  :date: 2011/03/17 09:00:00
  :updated:  2013/02/28 10:36:02
  :END:

Congratulations to Spencer for defending his dissertation entitled "Towards an Understanding of Coverage Dependent Atomic Adsorption on Late Transition Metals". The defense occurred on March 9, 2011. 

*  Nilay Inoglu has successfully defended her PhD dissertation
  :PROPERTIES:
  :categories: news
  :date: 2011/03/17 09:00:00
  :updated:  2013/02/28 10:36:02
  :END:
Congratulations to Nilay for successfully defending her dissertation entitled "Design of Sulfur Tolerant Transition Metal Catalysts and Oxide Based Oxygen Evolution Electrocatalysts". She defended on March 17, 2011.

Nilay will be joining Exxon Mobil later this year.
*  Anita Lee successfully defended her PhD proposal!
  :PROPERTIES:
  :categories: news
  :date:     2011/03/18 13:01:00
  :updated:  2013/02/28 21:35:54
  :permalink: http://jkitchin.github.com/blog/2011-03-18-anita-lee-successfully-defended-her-phd-proposal!/index.html
  :END:

Anita is combining molecular modeling with systems modeling to identify potential limitations in amine-based CO2 capture technologies. Her proposal was titled "Can we do better than MEA? A Multi-scale Modeling Approach to Designing Novel Amines Solvents for Post Combustion CO2 Capture" and she defended it on March 16, 2011. 
* Professor Kitchin wins 2010 Kun Li Teaching Award
  :PROPERTIES:
  :date:     2010/05/21 11:31:00
  :categories: news
  :updated:  2013/02/28 21:37:13
  :permalink: http://jkitchin.github.com/blog/2010-05-21-professor-kitchin-wins-2010-kun-li-teaching-award/index.html
  :END:
Thanks seniors!
* Anita Lee selected for a 2010-2011 Steinbrenner Graduate Fellowship
  :PROPERTIES:
  :categories: news
  :date:     2010/04/25 15:24:00
  :updated:  2013/02/28 21:38:27
  :permalink: http://jkitchin.github.com/blog/2010-04-25-anita-lee-selected-for-a-2010-2011-steinbrenner-graduate-fellowship/index.html
  :END:


She was selected for her research on a comprehensive computational approach to evaluating amine based solvents for post combustion CO2 capture. 
* Prof. Kitchin wins DOE Early Career Award!
  :PROPERTIES:
  :date:     2010/01/14 16:37:00
  :categories: news
  :updated:  2013/02/28 21:39:40
  :permalink: http://jkitchin.github.com/blog/2010-01-14-prof.-kitchin-wins-doe-early-career-award!/index.html
  :END:

The project is entitled "Multifunctional Oxygen Evolution Electrocatalyst Design and Synthesis". 
* Nilay Inoglu won an International Research Fellowship
  :PROPERTIES:
  :categories: news
  :date:     2009/11/07 22:40:00
  :updated:  2013/02/28 21:40:36
  :permalink: http://jkitchin.github.com/blog/2009-11-07-nilay-inoglu-won-an-international-research-fellowship/index.html
  :END:

Nilay will visit the Department of Physics at the Denmark Technical University next year to work with Jens Norskov. 
*  Rich Alesi passed his PhD proposal defense
  :PROPERTIES:
  :date:     2009/11/07 22:37:00
  :categories: news
  :updated:  2013/02/28 21:41:26
  :permalink: http://jkitchin.github.com/blog/2009-11-07-rich-alesi-passed-his-phd-proposal-defense/index.html
  :END:

Rich passed his proposal defense on designing amidine-based CO2 sorbents. 
