#+TITLE: Documentation for /Users/jkitchin/Dropbox/kitchingroup/jmax/jmax-bibtex.el
* Variables
** jmax-bibtex-journal-abbreviations
Documentation: List of (string journal-full-name journal-abbreviation). Find abbreviations at http://cassi.cas.org/search.jsp.

** jmax-lower-case-words
Documentation: List of words to keep lowercase

** jmax-nonascii-latex-replacements
Documentation: Cons list of non-ascii characters and their LaTeX representations

* Functions

** jmax-bibtex-generate-longtitles nil
Documentation: generates longtitles.bib which are @string definitions of the
full journal names in `jmax-bibtex-journal-abbreviations'.

Code:
#+BEGIN_SRC emacs-lisp
(lambda nil "generates longtitles.bib which are @string definitions of the
full journal names in `jmax-bibtex-journal-abbreviations'." (interactive) (let ((temp-file "longtitles.bib") (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (let ((--dolist-tail-- jmax-bibtex-journal-abbreviations) row) (while --dolist-tail-- (setq row (car --dolist-tail--)) (insert (format "@string{%s=\"%s\"}
" (nth 0 row) (nth 1 row))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
#+END_SRC
** jmax-bibtex-generate-shorttitles nil
Documentation: generates shorttitles.bib which are @string definitions of the
abbreviated journal names in `jmax-bibtex-journal-abbreviations'.

Code:
#+BEGIN_SRC emacs-lisp
(lambda nil "generates shorttitles.bib which are @string definitions of the
abbreviated journal names in `jmax-bibtex-journal-abbreviations'." (interactive) (let ((temp-file "shorttitles.bib") (temp-buffer (get-buffer-create (generate-new-buffer-name " *temp file*")))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (let ((--dolist-tail-- jmax-bibtex-journal-abbreviations) row) (while --dolist-tail-- (setq row (car --dolist-tail--)) (insert (format "@string{%s=\"%s\"}
" (nth 0 row) (nth 2 row))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
#+END_SRC
** jmax-bibtex-mode-keys nil
Documentation: Modify keymaps used by `bibtex-mode'.

Code:
#+BEGIN_SRC emacs-lisp
(lambda nil "Modify keymaps used by `bibtex-mode'." (local-set-key (kbd "M-n") (quote jmax-bibtex-next-entry)) (local-set-key (kbd "M-p") (quote jmax-bibtex-previous-entry)))
#+END_SRC
** jmax-bibtex-next-entry (&optional n)
Documentation: Jump to the beginning of the next bibtex entry. N is a prefix
argument. If it is numeric, jump that many entries
forward. Negative numbers do nothing.

Code:
#+BEGIN_SRC emacs-lisp
(lambda (&optional n) "Jump to the beginning of the next bibtex entry. N is a prefix
argument. If it is numeric, jump that many entries
forward. Negative numbers do nothing." (interactive "P") (if (= (point) (save-excursion (bibtex-beginning-of-entry))) (progn (forward-char) (bibtex-next-entry))) (if (re-search-forward bibtex-entry-head nil t (and (numberp n) n)) (progn (bibtex-beginning-of-entry))))
#+END_SRC
** jmax-bibtex-previous-entry (&optional n)
Documentation: Jump to beginning of the previous bibtex entry. N is a prefix
argument. If it is numeric, jump that many entries back.

Code:
#+BEGIN_SRC emacs-lisp
(lambda (&optional n) "Jump to beginning of the previous bibtex entry. N is a prefix
argument. If it is numeric, jump that many entries back." (interactive "P") (bibtex-beginning-of-entry) (if (re-search-backward bibtex-entry-head nil t (and (numberp n) n)) (progn (bibtex-beginning-of-entry))))
#+END_SRC
** jmax-replace-nonascii nil
Documentation: hook function to replace non-ascii characters in a bibtex
entry. 

Code:
#+BEGIN_SRC emacs-lisp
(lambda nil "hook function to replace non-ascii characters in a bibtex
entry. " (interactive) (save-restriction (bibtex-narrow-to-entry) (goto-char (point-min)) (let ((--dolist-tail-- (mapcar (function (lambda (x) (car x))) jmax-nonascii-latex-replacements)) char) (while --dolist-tail-- (setq char (car --dolist-tail--)) (while (re-search-forward char nil t) (replace-match (cdr (assoc char jmax-nonascii-latex-replacements)))) (goto-char (point-min)) (setq --dolist-tail-- (cdr --dolist-tail--))))))
#+END_SRC
** jmax-sentence-case-article (&optional key start end)
Documentation: Convert a bibtex entry article title to sentence-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles.

Code:
#+BEGIN_SRC emacs-lisp
(lambda (&optional key start end) "Convert a bibtex entry article title to sentence-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles." (interactive) (bibtex-beginning-of-entry) (let* ((title (bibtex-autokey-get-field "title")) (words (split-string title)) (start 0)) (if (string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry))))) (progn (setq words (mapcar (function (lambda (word) (if (string-match "\\$\\|{\\|}\\|\\\\" word) word (s-downcase word)))) words)) (let* ((v words)) (setcar v (s-capitalize (car words)))) (setq title (mapconcat (quote identity) words " ")) (while (string-match "[a-z]:\\s-+\\([A-Z]\\)" title start) (let ((char (substring title (match-beginning 1) (match-end 1)))) (let* ((start (match-beginning 1)) (end (match-end 1))) (setq title (cl--set-substring title start end (format "%s" (upcase char))))) (setq start (match-end 1)))) (bibtex-set-field "title" title) (bibtex-clean-entry) (bibtex-fill-entry)))))
#+END_SRC
** jmax-set-journal-string (full-journal-name)
Documentation: set a bibtex journal name to the string that represents
FULL-JOURNAL_NAME. This is defined in
`jmax-bibtex-journal-abbreviations'.

Code:
#+BEGIN_SRC emacs-lisp
(lambda (full-journal-name) "set a bibtex journal name to the string that represents
FULL-JOURNAL_NAME. This is defined in
`jmax-bibtex-journal-abbreviations'." (interactive (list (ido-completing-read "Journal: " (mapcar (function (lambda (x) (nth 1 x))) jmax-bibtex-journal-abbreviations)))) (let ((alist (mapcar (function (lambda (x) (cons (nth 1 x) (nth 0 x)))) jmax-bibtex-journal-abbreviations))) (bibtex-set-field "journal" (cdr (assoc full-journal-name alist)) t) (bibtex-fill-entry) (bibtex-clean-entry)))
#+END_SRC
** jmax-stringify-journal-name (&optional key start end)
Documentation: replace journal name in a bibtex entry with a string. The
strings are defined in `jmax-bibtex-journal-abbreviations'. The optional
arguments allow you to use this with `bibtex-map-entries'

Code:
#+BEGIN_SRC emacs-lisp
(lambda (&optional key start end) "replace journal name in a bibtex entry with a string. The
strings are defined in `jmax-bibtex-journal-abbreviations'. The optional
arguments allow you to use this with `bibtex-map-entries'" (interactive) (bibtex-beginning-of-entry) (if (string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry))))) (progn (let* ((full-names (mapcar (function (lambda (row) (cons (nth 1 row) (nth 0 row)))) jmax-bibtex-journal-abbreviations)) (abbrev-names (mapcar (function (lambda (row) (cons (nth 2 row) (nth 0 row)))) jmax-bibtex-journal-abbreviations)) (journal (s-trim (bibtex-autokey-get-field "journal"))) (bstring (or (cdr (assoc journal full-names)) (cdr (assoc journal abbrev-names))))) (if bstring (progn (bibtex-set-field "journal" bstring t) (bibtex-fill-entry)))))))
#+END_SRC
** jmax-title-case-article (&optional key start end)
Documentation: Convert a bibtex entry article title to title-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles.

Code:
#+BEGIN_SRC emacs-lisp
(lambda (&optional key start end) "Convert a bibtex entry article title to title-case. The
arguments are optional, and are only there so you can use this
function with `bibtex-map-entries' to change all the title
entries in articles." (interactive) (bibtex-beginning-of-entry) (let* ((title (bibtex-autokey-get-field "title")) (words (split-string title)) (start 0)) (if (string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry))))) (progn (setq words (mapcar (function (lambda (word) (if (or (string-match "\\$\\|{\\|}\\|\\\\" word) (-contains\? jmax-lower-case-words (s-downcase word))) word (s-capitalize word)))) words)) (if (-contains\? jmax-lower-case-words (car words)) (progn (let* ((v words)) (setcar v (s-capitalize (car words)))))) (setq title (mapconcat (quote identity) words " ")) (while (string-match "[a-zA-Z]-\\([a-z]\\)" title start) (let ((char (substring title (match-beginning 1) (match-end 1)))) (let* ((start (match-beginning 1)) (end (match-end 1))) (setq title (cl--set-substring title start end (format "%s" (upcase char))))) (setq start (match-end 1)))) (bibtex-set-field "title" title) (bibtex-fill-entry)))))
#+END_SRC
