* New publication - AdsorbDiff: Adsorbate Placement via Conditional Denoising Diffusion
:PROPERTIES:
:categories: news,publication
:date:     2025/01/31 07:17:17
:updated:  2025/02/01 09:00:18
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/01/31/New-publication---AdsorbDiff:-Adsorbate-Placement-via-Conditional-Denoising-Diffusion.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/01/31/New-publication---AdsorbDiff:-Adsorbate-Placement-via-Conditional-Denoising-Diffusion/index.html
:END:

The paper “AdsorbDiff: Adsorbate Placement via Conditional Denoising Diffusion” presents a novel machine learning framework for optimizing the placement of adsorbates on catalyst surfaces. Traditional methods rely on heuristics or brute-force searches to determine the lowest energy configuration, a key step in computational catalyst discovery. AdsorbDiff introduces a conditional denoising diffusion model that predicts optimal adsorbate sites and orientations while accounting for periodic boundary conditions. The model integrates machine learning force fields and Density Functional Theory (DFT) evaluations to ensure accurate energy assessments. Compared to prior approaches, AdsorbDiff achieves up to a 5x speedup and a 3.5x improvement in accuracy. The study also explores the impact of pretraining and model architectures, demonstrating robust generalization to unseen adsorbates and slabs. This advancement significantly accelerates computational screening for new catalysts, paving the way for more efficient materials discovery.

AdsorbDiff: Adsorbate Placement via Conditional Denoising Diffusion, Adeesh Kolluru, John R. Kitchin Proceedings of the 41st International Conference on Machine Learning, PMLR 235:25042-25057, 2024.


#+BEGIN_SRC bibtex
@InProceedings{pmlr-v235-kolluru24a,
  title = 	 {{A}dsorb{D}iff: Adsorbate Placement via Conditional Denoising Diffusion},
  author =       {Kolluru, Adeesh and Kitchin, John R.},
  booktitle = 	 {Proceedings of the 41st International Conference on Machine Learning},
  pages = 	 {25042--25057},
  year = 	 {2024},
  editor = 	 {Salakhutdinov, Ruslan and Kolter, Zico and Heller, Katherine and Weller, Adrian and Oliver, Nuria and Scarlett, Jonathan and Berkenkamp, Felix},
  volume = 	 {235},
  series = 	 {Proceedings of Machine Learning Research},
  month = 	 {21--27 Jul},
  publisher =    {PMLR},
  pdf = 	 {https://raw.githubusercontent.com/mlresearch/v235/main/assets/kolluru24a/kolluru24a.pdf},
  url = 	 {https://proceedings.mlr.press/v235/kolluru24a.html},
  abstract = 	 {Determining the optimal configuration of adsorbates on a slab (adslab) is pivotal in the exploration of novel catalysts across diverse applications. Traditionally, the quest for the lowest energy adslab configuration involves placing the adsorbate onto the slab followed by an optimization process. Prior methodologies have relied on heuristics, problem-specific intuitions, or brute-force approaches to guide adsorbate placement. In this work, we propose a novel framework for adsorbate placement using denoising diffusion. The model is designed to predict the optimal adsorbate site and orientation corresponding to the lowest energy configuration. Further, we have an end-to-end evaluation framework where diffusion-predicted adslab configuration is optimized with a pretrained machine learning force field and finally evaluated with Density Functional Theory (DFT). Our findings demonstrate an acceleration of up to 5x or 3.5x improvement in accuracy compared to the previous best approach. Given the novelty of this framework and application, we provide insights into the impact of pretraining, model architectures, and conduct extensive experiments to underscore the significance of this approach.}
}

#+END_SRC


#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35095690/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
