* New publication - WhereWulff A Semiautonomous Workflow for Systematic Catalyst Surface Reactivity under Reaction Conditions
:PROPERTIES:
:categories: news,publication
:date:     2023/04/16 09:46:53
:updated:  2023/04/16 09:49:02
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2023/04/16/New-publication---WhereWulff-A-Semiautonomous-Workflow-for-Systematic-Catalyst-Surface-Reactivity-under-Reaction-Conditions.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2023/04/16/New-publication---WhereWulff-A-Semiautonomous-Workflow-for-Systematic-Catalyst-Surface-Reactivity-under-Reaction-Conditions/index.html
:END:

Suppose you want to explore metal oxides as potential water oxidation electrocatalysts. There are many steps to do this. You can use databases of materials to get compositions and structures, but for each one you have to determine the ground state structure, including magnetic states, for each bulk structure, and filter out bulk materials that are not stable under water oxidation conditions. Then, using the remaining structures you have to construct slabs and determine which surfaces are likely to be stable, and most relevant. After that you have to compute adsorption energies on those surfaces to see which surfaces have the most relevant reactivity (while also being stable). This results in hundreds to thousands of calculations that depend on each other in important ways. It is very useful to use software workflow tools to facilitate and manage this process. In this paper we develop a workflow like this for exploring metal oxides for water oxidation. The software is open source and available at https://github.com/ulissigroup/wherewulff.

The paper is free to read for 6 months at https://pubs.acs.org/doi/10.1021/acs.jcim.3c00142.

#+BEGIN_SRC bibtex
@article{sanspeur-2023,
  author = {Rohan Yuri Sanspeur and Javier Heras-Domingo and John R. Kitchin and Zachary Ulissi},
  title = {wherewulff: a Semiautonomous Workflow for Systematic Catalyst Surface Reactivity Under Reaction Conditions},
  journal = {Journal of Chemical Information and Modeling},
  volume = {nil},
  number = {nil},
  pages = {nil},
  year = {2023},
  doi = {10.1021/acs.jcim.3c00142},
  url = {http://dx.doi.org/10.1021/acs.jcim.3c00142},
  DATE_ADDED = {Sun Apr 16 09:17:23 2023},
}
#+END_SRC

altmetric:10.1021/acs.jcim.3c00142

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/UyjTvIeZOEk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+END_EXPORT
