* New publication - Neural network embeddings based similarity search method for atomistic systems 
:PROPERTIES:
:categories: news,publication
:date:     2022/09/12 17:26:44
:updated:  2022/09/12 17:26:44
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2022/09/12/New-publication---Neural-network-embeddings-based-similarity-search-method-for-atomistic-systems.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2022/09/12/New-publication---Neural-network-embeddings-based-similarity-search-method-for-atomistic-systems/index.html
:END:

Searching for atomic structures in databases is like finding a needle in the haystack. It is difficult to construct a query that finds what you want, without finding nothing, or everything! It is difficult to use atomic coordinates because they are sensitive to translations, rotations and permutations. There are many ways to construct equivalent unit cells that also make it difficult to uniquely query materials. 

In this paper we show how to construct queries for atomic structures that allow you to quickly find similar atomic structures. We achieve this by using invariant fingerprint vectors from machine learning models coupled with approximate nearest neighbor vector search algorithms. We apply it to molecules, bulk materials and adsorbates on surfaces. We show how the geometric similarity in found atomic systems leads to better data sets for building new machine learning models, and that the found systems tend to show geometric and electronic structure similarity.

You can read more about this work here (it is Open Access):
Yilin Yang, Mingie Liu, John Kitchin, Digital Discovery, 2022, https://doi.org/10.1039/D2DD00055E


#+BEGIN_SRC bibtex
@article{yang-2022-neural-networ,
  author =	 {Yilin Yang and Mingjie Liu and John R. Kitchin},
  title =	 {Neural Network Embeddings Based Similarity Search Method for
                  Atomistic Systems},
  journal =	 {Digital Discovery},
  volume =	 {},
  number =	 {},
  pages =	 {},
  year =	 2022,
  doi =		 {10.1039/d2dd00055e},
  url =		 {https://doi.org/10.1039/D2DD00055E},
  DATE_ADDED =	 {Mon Sep 12 17:21:30 2022},
}
#+END_SRC

altmetric:10.1039/D2DD00055E


#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/lbIxEk2nd6Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT
