* TODO New publication in Molecular Simulation
  :PROPERTIES:
  :categories: news,publication
  :date:     2018/01/03 06:28:21
  :updated:  2018/01/03 06:28:21
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2018/01/03/New-publication-in-Molecular-Simulation.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2018/01/03/New-publication-in-Molecular-Simulation/index.html
  :END:
  

This paper is our latest work using neural networks in molecular simulation. In this work, we build a Behler-Parinello neural network potential of bulk zirconia. The potential can describe several polymorphs of zirconia, as well as oxygen vacancy defect formation energies and diffusion barriers. We show that we can use the potential to model oxygen vacancy diffusion using molecular dynamics at different temperatures, and to use that data to estimate the effective diffusion activation energy. This is further evidence of the general utility of the neural network-based potential for molecular simulations with DFT accuracy.

#+BEGIN_SRC bibtex
@article{wang-2018-densit-funct,
  author =	 {Chen Wang and Akshay Tharval and John R. Kitchin},
  title =	 {A Density Functional Theory Parameterised Neural Network Model
                  of Zirconia},
  journal =	 {Molecular Simulation},
  volume =	 0,
  number =	 0,
  pages =	 {1-8},
  year =	 2018,
  doi =		 {10.1080/08927022.2017.1420185},
  url =		 {https://doi.org/10.1080/08927022.2017.1420185},
  eprint =	 { https://doi.org/10.1080/08927022.2017.1420185 },
  publisher =	 {Taylor \& Francis},
}
#+END_SRC

altmetric:10.1080/08927022.2017.1420185

