* New publication - Cattsunami: Accelerating Transition State Energy Calculations With Pretrained Graph Neural Networks
:PROPERTIES:
:categories: news,publication
:date:     2025/03/17 20:58:15
:updated:  2025/03/17 20:58:15
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/03/17/New-publication---Cattsunami:-Accelerating-Transition-State-Energy-Calculations-With-Pretrained-Graph-Neural-Networks.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/03/17/New-publication---Cattsunami:-Accelerating-Transition-State-Energy-Calculations-With-Pretrained-Graph-Neural-Networks/index.html
:END:


In this work, we tackled the challenge of accelerating catalyst discovery by focusing on transition state energy calculations. We show that a graph neural network potential, despite being trained on a different task, could accurately predict transition states—a crucial step in catalyst discovery—with a remarkable 28x speedup over traditional methods. To provide a benchmark for machine learning model performance in this area, we also curated the Open Catalyst 2020 Nudged Elastic Band (OC20NEB) dataset, which includes 932 DFT nudged elastic band calculations. To showcase the effectiveness of our approach, we applied it to two case studies: reaction mechanism search and ammonia synthesis. These demonstrations highlighted the significant potential of machine learning to enhance and speed up catalyst research.

#+BEGIN_SRC bibtex
@article{wander-2025-catts,
  author =	 {Brook Wander and Muhammed Shuaibi and John R. Kitchin and
                  Zachary W. Ulissi and C. Lawrence Zitnick},
  title =	 {{CatTsunami}: Accelerating Transition State Energy Calculations
                  With Pretrained Graph Neural Networks},
  journal =	 {ACS Catalysis},
  volume =	 {nil},
  number =	 {nil},
  pages =	 {5283-5294},
  year =	 2025,
  doi =		 {10.1021/acscatal.4c04272},
  url =		 {http://dx.doi.org/10.1021/acscatal.4c04272},
  DATE_ADDED =	 {Mon Mar 17 20:50:26 2025},
}
#+END_SRC



altmetric:10.1021/acscatal.4c04272
