* New publication - Applying Large Graph Neural Networks to Predict Transition Metal Complex Energies Using the tmQM_wB97MV Data Set
:PROPERTIES:
:categories: news,publication
:date:     2023/12/10 14:53:33
:updated:  2023/12/10 14:53:33
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2023/12/10/New-publication---Applying-Large-Graph-Neural-Networks-to-Predict-Transition-Metal-Complex-Energies-Using-the-tmQM_wB97MV-Data-Set.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2023/12/10/New-publication---Applying-Large-Graph-Neural-Networks-to-Predict-Transition-Metal-Complex-Energies-Using-the-tmQM_wB97MV-Data-Set/index.html
:END:

In this work, we show that we can use large graph neural networks to predict transition metal complex energies. We developed an improved dataset at a higher level of theory, and tested models ranging from GemNet-T (best) to SchNet (worst). The model performance saturates with the size of neutral structures, and improves with increasing size of charged structures. Finally, we showed that a pre-trained model from OC20 was even better than training from scratch. This indicates a degree of transferability from heterogeneous catalyst models to homogeneous molecular catalysts.

#+BEGIN_SRC bibtex
@article{garrison-2023-apply-large,
  author =	 {Garrison, Aaron G. and Heras-Domingo, Javier and Kitchin, John
                  R. and dos Passos Gomes, Gabriel and Ulissi, Zachary W. and
                  Blau, Samuel M.},
  title =	 {Applying Large Graph Neural Networks To Predict Transition
                  Metal Complex Energies Using the tmQM\_wB97MV Data Set},
  journal =	 {Journal of Chemical Information and Modeling},
  volume =	 0,
  number =	 0,
  pages =	 {null},
  year =	 2023,
  doi =		 {10.1021/acs.jcim.3c01226},
  URL =		 {https://doi.org/10.1021/acs.jcim.3c01226},
  eprint =	 {https://doi.org/10.1021/acs.jcim.3c01226},
  note =	 {PMID: 38049389},
}

#+END_SRC

altmetric:10.1021/acs.jcim.3c01226

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/p_DpuIdcelY?si=HaBtCUlByRjuJU7i" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+END_EXPORT
