* Youtube live-streamed research talks
  :PROPERTIES:
  :categories: news
  :date:     2021/06/29 12:07:46
  :updated:  2021/06/29 12:08:03
  :org-url:  https://kitchingroup.cheme.cmu.edu/org/2021/06/29/Youtube-live-streamed-research-talks.org
  :permalink: https://kitchingroup.cheme.cmu.edu/blog/2021/06/29/Youtube-live-streamed-research-talks/index.html
  :END:

For fun, I have been live-streaming some of our research talks from the past year. Two of these talks are shown below. This is an experiment of sorts, let me know if you like them!

** Machine learned potentials and automatic differentiation in molecular simulation

Machine learned potentials are revolutionizing molecular simulations. In this talk, I will introduce what machine learned potentials are, how we think about them, and how we create them. Then, I will show an example of how we use them to model segregation in a metal alloy surface at many different bulk compositions. Finally, I will show how automatic differentiation, which is one of the foundations of machine learning, can be used more broadly in scientific programming with derivatives.

This was the second talk I did, but it is somewhat of an introduction to the next talk below.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/KKPogR9iObg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

** Leveraging machine learning to accelerate simulations of dilute alloy catalysts with adsorbates

In this talk I talk about how we use machine learning to build cheap and accurate surrogate models of alloy catalyst surfaces in the dilute limit. I will show how we use this to simulate acrolein adsorption on dilute Ag-Pd alloys.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/UGmv7IIqM_8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 #+END_EXPORT


