* New publication in J. Phys. Chem. C
  :PROPERTIES:
  :categories: news, publication
  :date:     2017/01/31 09:30:16
  :updated:  2017/01/31 09:30:16
  :END:

The surface composition of an alloy is rarely the same as the bulk composition due to segregation, and it changes with changing reaction conditions. Segregation is a ubiquitous issue in alloy catalysis, and makes modeling alloy surfaces a challenge, because we need to know the surface composition to model them! In this work, we take a first step in using density functional theory to build a neural network potential that we can use with Monte Carlo simulations to predict the temperature dependent surface composition of an Au-Pd bulk alloy in a vacuum. This approach yielded quantitative predictions in good agreement with experimental measurements over the entire bulk composition range. 

#+BEGIN_SRC bibtex
@article{boes-2017-model-segreg,
  author =	 {Boes, Jacob Russell and Kitchin, John R.},
  title =	 {Modeling Segregation on {AuPd}(111) Surfaces With Density
                  Functional Theory and Monte Carlo Simulations},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 0,
  number =	 {ja},
  pages =	 {null},
  year =	 2017,
  doi =		 {10.1021/acs.jpcc.6b12752},
  url =		 {https://doi.org/10.1021/acs.jpcc.6b12752},
  eprint =	 { https://doi.org/10.1021/acs.jpcc.6b12752 },
}

#+END_SRC

altmetric:10.1021/acs.jpcc.6b12752
