* Updating Multiple RESULTS blocks in org-mode
  :PROPERTIES:
  :categories: orgmode
  :date:     2015/03/11 17:33:51
  :updated:  2015/03/11 17:33:51
  :END:

There was a recent question on the org-mode mailing list about getting multiple named block results to update when a named code block is run. I suppose you might want to do this if you need to see the results in more than one place. org-mode (at the moment) only updates the first named block that it finds from the beginning of the buffer. Challenge accepted ;)

Here is a function that will update all the named RESULTS blocks. The idea is to make a hook function that runs after you run a block. The hook function will get the block name, and if there is one, find all the named results in the buffer and update them.

#+BEGIN_SRC emacs-lisp
(defun update-results ()
  ;; get name of src block
  (let ((name (org-element-property :name (org-element-at-point)))
	(results)
	(begin))
    (when name
      (setq results
	    (save-excursion
	      (goto-char (org-babel-find-named-result name))
	      (forward-line)
	      (buffer-substring
	       (point) (org-element-property :end (org-element-at-point)))))
      (save-excursion
	(goto-char (point-min))
	(while (setq begin (org-babel-find-named-result name (point)))
	  (goto-char begin)
	  (forward-line)
	  (setf (buffer-substring
		 (point)
		 (org-element-property :end (org-element-at-point)))
		results))))))

(add-hook 'org-babel-after-execute-hook 'update-results)
#+END_SRC

#+RESULTS:
| update-results | (lambda nil (org-refresh-images)) |

Now let us test it out. Here is an unnamed block that should be ignored.
#+BEGIN_SRC python
print 4
#+END_SRC

#+RESULTS:
: 4

Here we have a named results block from a code block we will see later.
#+RESULTS: testcode
: [0.0825119635983067, 0.12793443834890417, 0.5235765147357154]

Here is our named code block that just prints three random numbers.

#+name: testcode
#+BEGIN_SRC python
import random

print [random.random() for i in range(3)]
#+END_SRC

#+RESULTS: testcode
: [0.0825119635983067, 0.12793443834890417, 0.5235765147357154]

Swell, everytime I run the block, the named results get updated everywhere! It isn't tested more than this post, so I would spend some time trying out your use cases before doing anything mission critical. Your mileage might vary. For example, if you have a named block outside a narrowed region it is not clear to me it would update. In other words, there might be other corners where this doesn't update like you thing.


