* DONE New publication in Surface Science
  CLOSED: [2015-11-17 Tue 20:44]
  :PROPERTIES:
  :categories: news,publication
  :date:     2015/11/17 20:44:50
  :updated:  2015/11/20 19:32:19
  :END:
Some time ago we published this paper on the coverage dependence of the adsorption energies of atomic adsorbates on different sites cite:xu-2014-probin-cover. One of the concerns in that work was whether van der Waal forces were significant for some adsorbates. Well, now we have addressed that concern in a new paper in Surface Science! In this new work we use the BEEF functional to simultaneously access the impact of van der Waal forces on the adsorption energy trends, as well as do some error analysis on the significance of the coverage dependence. I won't ruin the surprise too much; the good news is that yes van der Waals do influence adsorption of atomic adsorbates on metal surfaces, but the trends are mostly the same! See the paper for more details. Congratulations Hari!

#+BEGIN_SRC bibtex
@article{thirumalai-2015-pt-pd,
  author =	 "Hari Thirumalai and John R. Kitchin",
  title =	 {The Role of Vdw Interactions in Coverage Dependent Adsorption
                  Energies of Atomic Adsorbates on Pt(111) and Pd(111)},
  journal =	 "Surface Science ",
  pages =	 " - ",
  year =	 2015,
  doi =		 {10.1016/j.susc.2015.10.001},
  url =
                  "http://www.sciencedirect.com/science/article/pii/S0039602815003052",
  issn =	 "0039-6028",
}
#+END_SRC

See it here: http://www.sciencedirect.com/science/article/pii/S0039602815003052
