* Zhongnan Xu wins AIChE CRE Division Travel Award
  :PROPERTIES:
  :categories: news,award
  :date:     2015/09/13 11:13:00
  :updated:  2015/09/13 11:13:00
  :END:

Zhongnan Xu has been selected to receive a travel award from the AIChE Catalysis and Reaction Engineering Division to attend the annual meeting that will be held November 8-13 in Salt Lake City, Utah.

Zhongnan has three presenations at the AICHE meeting.

430759 Towards Accurate and Fast Discovery of Compound Materials As Catalysts: Lessons Learned from Oxides
Sunday, November 8, 2015
Exhibit Hall 1 (Salt Palace Convention Center) https://aiche.confex.com/aiche/2015/webprogram/Paper430759.html

415101 Tuning Oxide Activity through Modification of the Crystal and Electronic Structure: From Strain to Potential Polymorphs
Tuesday, November 10, 2015: 3:15 PM. https://aiche.confex.com/aiche/2015/webprogram/Paper415101.html

410339 Relationships Between the Surface Electronic and Chemical Properties of Doped 4d and 5d Late Transition Metal Dioxide Tuesday, November 10, 2015: 5:15 PM
355B (Salt Palace Convention Center) https://aiche.confex.com/aiche/2015/webprogram/Paper410339.html

Congratulations Zhongnan!
