* DONE New publication in J. Phys. Chem. C
  CLOSED: [2015-08-24 Mon 09:20]
  :PROPERTIES:
  :categories: publication, news
  :date:     2015/08/24 09:20:16
  :updated:  2015/08/24 10:35:46
  :END:

Predicting the relative stability of oxide polymorphs is critical to predicting which structures are likely to be experimentally observed. The energetics of TiO_{2} polymorphs are particularly challenging because the energies of the different polymorphs are relatively close together. Consequently, one predicts different relative stabilities using different exchange correlation functionals with DFT. In this paper, we show that DFT+U is able to give experimentally consistent relative orderings for the GGA functionals, and that linear response U can be used to predict a reasonable value of U.  Hybrid functionals can also do this for some ranges of the exact exchange fraction, but there is not yet a method to calculate from first-principles the amount of exact exchange required to achieve that. Notably, the U-values are pseudopotential and functional dependent.

This paper is open-access.

#+BEGIN_SRC bibtex
@article{curnan-2015-inves-energ,
  author =	 {Matthew Curnan and John R. Kitchin},
  title =	 {Investigating the Energetic Ordering of Stable and Metastable
                  TiO$_2$ Polymorphs Using DFT+U and Hybrid Functionals},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 0,
  number =	 {},
  pages =	 {},
  year =	 2015,
  doi =		 {10.1021/acs.jpcc.5b05338},
  url =		 { https://doi.org/10.1021/acs.jpcc.5b05338 },
  eprint =	 { https://doi.org/10.1021/acs.jpcc.5b05338 },
}

#+END_SRC

http://pubs.acs.org/doi/abs/10.1021/acs.jpcc.5b05338

#+BEGIN_HTML
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<div data-badge-type='medium-donut' class='altmetric-embed' data-badge-details='right' data-doi='10.1021/acs.jpcc.5b05338'></div>
#+END_HTML
