* New publication - Multiscale Optimization of Formic Acid Dehydrogenation Process via Linear Model Decision Tree Surrogates
:PROPERTIES:
:categories: news,publication
:date:     2025/02/03 06:50:27
:updated:  2025/02/03 06:50:27
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/03/New-publication---Multiscale-Optimization-of-Formic-Acid-Dehydrogenation-Process-via-Linear-Model-Decision-Tree-Surrogates.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/03/New-publication---Multiscale-Optimization-of-Formic-Acid-Dehydrogenation-Process-via-Linear-Model-Decision-Tree-Surrogates/index.html
:END:

In a push to optimize hydrogen storage and release, this study explores the multiscale optimization of formic acid dehydrogenation using linear model decision tree (LMDT) surrogates. This method tackles the challenge of integrating models that operate at different scales—ranging from atomistic catalyst design to reactor operation and techno-economic assessment. By replacing complex physics-based models with data-driven surrogates, the researchers created a framework that enables simultaneous optimization across these scales. The study finds that co-optimizing all three scales together leads to a 40% cost reduction compared to optimizing each part separately. The model also confirms economies of scale in hydrogen production, showing that optimal catalyst choice shifts from platinum to copper as production capacity increases. While the approach simplifies multiscale optimization, its accuracy depends on high-quality training data, and future work may integrate uncertainty quantification to improve reliability. This breakthrough highlights the power of surrogate models in chemical process optimization, paving the way for more cost-effective hydrogen energy solutions.


Ethan M. Sunshine, Giovanna Bucci, Tanusree Chatterjeed, Shyam Deod, Victoria M. Ehlinger, Wenqin Lib, Thomas Moore, Corey Myers, Wenyu Sun, Bo-Xun Wang, Mengyao Yuan, John R. Kitchin, Carl D. Laird, Matthew J. McNenly, Sneha A. Akhade, Multiscale Optimization of Formic Acid Dehydrogenation Process via Linear Model Decision Tree Surrogates, Computers and Chemical Engineering, 194, 108921 (2024) https://doi.org/10.1016/j.compchemeng.2024.108921.


#+BEGIN_SRC bibtex
@article{sunshine-2024-multis-optim,
  author =	 {Ethan M. Sunshine and Giovanna Bucci and Tanusree Chatterjee
                  and Shyam Deo and Victoria M. Ehlinger and Wenqin Li and
                  Thomas Moore and Corey Myers and Wenyu Sun and Bo-Xun Wang and
                  Mengyao Yuan and John R. Kitchin and Carl D. Laird and Matthew
                  J. McNenly and Sneha A. Akhade},
  title =	 {Multiscale Optimization of Formic Acid Dehydrogenation Process
                  Via Linear Model Decision Tree Surrogates},
  journal =	 {Computers &amp; Chemical Engineering},
  volume = 	 {194},
  pages =	 108921,
  year =	 2024,
  doi =		 {10.1016/j.compchemeng.2024.108921},
  url =		 {http://dx.doi.org/10.1016/j.compchemeng.2024.108921},
  DATE_ADDED =	 {Mon Nov 25 14:10:36 2024},
}
#+END_SRC

altmetric:10.1016/j.compchemeng.2024.108921

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35111575/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>replace. Tab to end.
#+END_EXPORT
