* New publication - Parallelized Screening of Characterized and DFT-Modelled Bimetallic Colloidal Co-Catalysts for Photocatalytic Hydrogen Evolution
  :PROPERTIES:
  :categories: news
  :date:     2020/03/10 10:20:52
  :updated:  2021/06/22 12:12:57
  :org-url:  https://kitchingroup.cheme.cmu.edu/org/2020/03/10/New-publication---Parallelized-Screening-of-Characterized-and-DFT-Modelled-Bimetallic-Colloidal-Co-Catalysts-for-Photocatalytic-Hydrogen-Evolution.org
  :permalink: https://kitchingroup.cheme.cmu.edu/blog/2020/03/10/New-publication---Parallelized-Screening-of-Characterized-and-DFT-Modelled-Bimetallic-Colloidal-Co-Catalysts-for-Photocatalytic-Hydrogen-Evolution/index.html
  :END:

Generating renewable hydrogen is an important capability for reducing CO_{2} emissions. In this work we use a photo-driven process where light interacts with a photosensitizer to generate electrons that reduce metal ions in solution to create nanoparticle catalysts, which subsequently catalyze hydrogen evolution from the oxidation of an amino alcohol. A challenge in this work is figuring out what the synthesis conditions are that lead to high activity; the metal salt compositions and concentrations, photosensitizer concentration, the concentration of amino alcohol and solvent choices all impact the catalytic performance. Exploring all these variables one at a time is expensive and time-consuming. To address this, we used a 96-well plate photoreactor that enabled us to run many experiments in parallel using a colorimetric hydrogen detecting tape to measure activity. This allowed us to explore many bimetallic co-catalysts comprised of Pd/Sn, Pd/Mo, Pd/Ru, Pd/Pb, Pd/Ni, Ni/Sn, Mo/Sn and Pt/Sn. Of these we found Pd/Sn showed the highest synergistic behavior, and best activity. We also show using DFT that Pd/Sn has a near optimal hydrogen adsorption energy, which is consistent with other highly active hydrogen evolution catalysts. This work shows an effective way to quickly screen hundreds of reaction conditions to explore the relationship between synthesis conditions and catalytic activity.

#+BEGIN_SRC bibtex :exports code
@article{lopato-2020-paral-screen,
  author =	 {Eric M. Lopato and Emily A Eikey and Zoe C Simon and Seoin
                  Back and Kevin Tran and Jacqueline Lewis and Jakub F.
                  Kowalewski and Sadegh Yazdi and John R. Kitchin and Zachary W.
                  Ulissi and Jill E. Millstone and Stefan Bernhard},
  title =	 {Parallelized Screening of Characterized and {DFT}-Modelled
                  Bimetallic Colloidal Co-Catalysts for Photocatalytic Hydrogen
                  Evolution},
  journal =	 {ACS Catalysis},
  volume =	 {10},
  number =	 {7},
  pages =	 {4244-4252},
  year =	 2020,
  doi =		 {10.1021/acscatal.9b05404},
  url =		 {https://doi.org/10.1021/acscatal.9b05404},
}
#+END_SRC

altmetric:10.1021/acscatal.9b05404
