* New publication - Investigating the Error Imbalance of Large-Scale Machine Learning Potentials in Catalysis
:PROPERTIES:
:categories: news,publication
:date:     2025/01/28 14:41:30
:updated:  2025/01/28 15:19:21
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/01/28/New-publication---Investigating-the-Error-Imbalance-of-Large-Scale-Machine-Learning-Potentials-in-Catalysis.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/01/28/New-publication---Investigating-the-Error-Imbalance-of-Large-Scale-Machine-Learning-Potentials-in-Catalysis/index.html
:END:

The paper “Investigating the Error Imbalance of Large-Scale Machine Learning Potentials in Catalysis” by Kareem Abdelmaqsoud et al. explores the persistent error imbalance in machine learning potentials (MLPs) trained on the Open Catalyst 2020 (OC20) dataset. While MLPs have significantly accelerated catalyst discovery by approximating density functional theory (DFT) calculations, the study finds that non-metals exhibit disproportionately high prediction errors compared to intermetallics and metalloids. The authors investigate two primary sources of this imbalance: (1) DFT convergence errors and (2) surface reconstruction inconsistencies. They determine that while DFT convergence errors exist, they do not significantly impact MLP performance. However, surface reconstructions introduce inconsistencies in adsorption energy referencing, making them difficult for MLPs to model accurately. By removing these reconstructions from validation sets, the study achieves a 35% reduction in mean absolute error (MAE) and a more balanced error distribution. The paper suggests an alternative approach: training MLPs on total energies rather than adsorption energies, which eliminates referencing issues and maintains comparable accuracy ￼. This research provides valuable insights for improving MLP robustness in catalysis and optimizing large-scale computational datasets.


#+BEGIN_SRC bibtex
@article{abdelmaqsoud-2024-inves-error,
  author =	 {Kareem Abdelmaqsoud and Muhammed Shuaibi and Adeesh Kolluru
                  and Raffaele Cheula and John R. Kitchin},
  title =	 {Investigating the Error Imbalance of Large-Scale Machine
                  Learning Potentials in Catalysis},
  journal =	 {Catalysis Science &amp; Technology},
  volume = 	 {14},
  number = 	 {20},
  pages = 	 {5899-5908},
  year =	 2024,
  doi =		 {10.1039/d4cy00615a},
  url =		 {http://dx.doi.org/10.1039/d4cy00615a},
  DATE_ADDED =	 {Sat Aug 17 09:45:44 2024},
}
#+END_SRC

altmetric:10.1039/d4cy00615a

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35051885/height/192/theme/modern/size/large/thumbnail/no/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
