* DONE New publication in J. Phys. Chem. Lett.
  CLOSED: [2017-09-25 Mon 20:24]
  :PROPERTIES:
  :categories: news,publication
  :date:     2017/09/25 20:24:45
  :updated:  2017/09/26 07:16:16
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2017/09/25/New-publication-in-J.-Phys.-Chem.-Lett..org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2017/09/25/New-publication-in-J.-Phys.-Chem.-Lett./index.html
  :END:

DFT calculations are extensively used to predict the chemical properties of metal alloy surfaces, but they are expensive which limits the number of calculations that can be practically be calculated. In this paper, we explore a perturbation approach known as alchemy to take previously calculated results and extend them to new compositions. We use oxygen reduction as a prototype reaction, and show that alchemy is often much faster than DFT, with an accuracy within 0.1 eV of the DFT. There are cases where the accuracy is not as good suggesting that further improvements to the perturbation model could be beneficial. Overall, alchemy appears to be a useful tool in high-throughput screening research.

#+BEGIN_SRC bibtex
@article{saravanan-2017-alchem-predic,
  title =	 {Alchemical Predictions for Computational Catalysis: Potential
                  and Limitations},
  year =	 2017,
  Author =	 {Saravanan, Karthikeyan and Kitchin, John R. and von
                  Lilienfeld, O. Anatole and Keith, John A.},
  Bdsk-Url-1 =	 {https://doi.org/10.1021/acs.jpclett.7b01974},
  Doi =		 {10.1021/acs.jpclett.7b01974},
  Eprint =	 {https://doi.org/10.1021/acs.jpclett.7b01974},
  Journal =	 {The Journal of Physical Chemistry Letters},
  Note =	 {PMID: 28938798},
  Number =	 {ja},
  Pages =	 {null},
  Url =		 {https://doi.org/10.1021/acs.jpclett.7b01974},
  Volume =	 0,
}

#+END_SRC  

altmetric:10.1021/acs.jpclett.7b01974
