* New publication "Machine-learning accelerated geometry optimization in molecular simulation"
  :PROPERTIES:
  :categories: news
  :date:     2021/06/21 11:52:32
  :updated:  2021/06/21 11:52:32
  :org-url:  https://kitchingroup.cheme.cmu.edu/org/2021/06/21/New-publication-"Machine-learning-accelerated-geometry-optimization-in-molecular-simulation".org
  :permalink: https://kitchingroup.cheme.cmu.edu/blog/2021/06/21/New-publication-"Machine-learning-accelerated-geometry-optimization-in-molecular-simulation"/index.html
  :END:

Geometry optimization and transition state searches are two very common tasks in molecular simulation. Typically every one of these is done from scratch, and they can only be made faster by using a better initial guess. Typical optimization algorithms use some variation of gradient descent, and the best ones also use an iterative approach to estimate the Hessian (second derivatives). The problem is we do not know the underlying function that is being optimized, so there is hardly any choice to benefit from the Hessian (which allows bigger, more accurate steps to be taken).

In this paper, we use machine learning to develop a surrogate model that is cheap compared to the DFT calculations, and that has an uncertainty quantification so we can tell when it is accurate. This allows us to take many cheap steps when the surrogate model is accurate, and only do expensive calculations when needed. More importantly though, the surrogate model works across many different geometry optimizations, which allows us to benefit from previous calculations. We show this works on a variety of atomic geometries ranging from metal slabs, slabs with adsorbates, and nanoparticle geometries, as well as with nudged elastic band calculations for transitions state searches.


#+BEGIN_SRC bibtex
@article{yang-2021-machin-learn,
  author =	 {Yilin Yang and Omar A. Jim{\'e}nez-Negr{\'o}n and John R.
                  Kitchin},
  title =	 {Machine-Learning Accelerated Geometry Optimization in
                  Molecular Simulation},
  journal =	 {The Journal of Chemical Physics},
  volume =	 154,
  number =	 23,
  pages =	 234704,
  year =	 2021,
  doi =		 {10.1063/5.0049665},
  url =		 {https://doi.org/10.1063/5.0049665},
}
#+END_SRC

altmetric:10.1063/5.0049665
