* New publication - Sequential Sampling Methods for Finding Classification Boundaries in Engineering Applications
:PROPERTIES:
:categories: publication, news
:date:     2023/09/19 15:57:56
:updated:  2023/09/19 15:57:56
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2023/09/19/New-publication---Sequential-Sampling-Methods-for-Finding-Classification-Boundaries-in-Engineering-Applications.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2023/09/19/New-publication---Sequential-Sampling-Methods-for-Finding-Classification-Boundaries-in-Engineering-Applications/index.html
:END:

We have a new publication out! In this work we show how to use classification algorithms to find boundaries in science and engineering applications. These applications come up all over the place, for example you may want to know what compositions phase separate, and which ones are single phase, or what conditions lead to degradation and which ones don't. You might want to know which operating parameters have desirable properties, and which don't. In this work we show how to efficiently find the boundaries between these regions using active learning and a classifier. We show that this approach is generally better (more accurate and fewer experiments) than doing a dense grid search.

#+BEGIN_SRC bibtex
@article{bhat-2023-sequen-sampl,
  author =	 {Maya Bhat and John R. Kitchin},
  title =	 {Sequential Sampling Methods for Finding Classification
                  Boundaries in Engineering Applications},
  journal =	 {Industrial \& Engineering Chemistry Research},
  volume =	 {n/a},
  number =	 {n/a},
  pages =	 {n/a},
  year =	 2023,
  doi =		 {10.1021/acs.iecr.3c02362},
  url =		 {http://dx.doi.org/10.1021/acs.iecr.3c02362}
}
#+END_SRC

Check out the Youtube video summary here:

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/upvDBvLMGgo?si=ZTUpVP2-dKOd4Yuh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+END_EXPORT

altmetric:10.1021/acs.iecr.3c02362
