* New publication in J. Phys. Chem. C
  :PROPERTIES:
  :categories: news,publication
  :date:     2015/05/07 15:07:17
  :updated:  2015/05/07 15:07:17
  :END:
In this paper we show that the electrolyte can  modify the reactivity of nickel hydroxide based electrodes for electrochemical water oxidation. There are two effects that are important: 1) Fe-impurities, and 2) the identify of the electrolyte cation. Fe-impurities are known to promote water oxidation. We found that a LiOH electrolyte can /suppress/ the oxygen evolution reaction, which is also known from the battery literature. KOH and CsOH are the best electrolytes for the OER on nickel hydroxide based electrodes.

"Alkaline Electrolyte and Fe Impurity Effects on the Performance and Active-phase Structure of NiOOH Thin Films for OER Catalysis Applications"

http://pubs.acs.org/doi/abs/10.1021/acs.jpcc.5b02458

#+BEGIN_SRC bibtex
@article{michael-2015-alkal-elect,
  author =	 {Michael, John and Demeter, Ethan L and Illes, Steven M. and
                  Fan, Qingqi and Boes, Jacob R. and Kitchin, John R.},
  title =	 {Alkaline Electrolyte and Fe Impurity Effects on the
                  Performance and Active-Phase Structure of NiOOH Thin Films for
                  OER Catalysis Applications},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 0,
  number =	 {ja},
  pages =	 {null},
  year =	 2015,
  doi =		 {10.1021/acs.jpcc.5b02458},
  url =		 { http://dx.doi.org/10.1021/acs.jpcc.5b02458 },
  eprint =	 { http://dx.doi.org/10.1021/acs.jpcc.5b02458 },
}
#+END_SRC