** Creating a navigation document
   :PROPERTIES:
   :date:     2013/04/30 09:32:05
   :updated:  2013/04/30 09:32:05
   :END:
In this section we write some code that creates text with a link to each file we need to review. This is something I imagine we would do after all the files have been turned in and collected. This buffer would facilitate navigating all the files, and checking them off. First we create checkboxes. All this does is create an easy to use navigation document that facilitates opening the files, grading them, and marking them as done.

#+BEGIN_SRC emacs-lisp :results output org raw
(require 'find-lisp)

(dolist (fname (find-lisp-find-files "." "\\HW1.org$") nil)
  (princ (format "- [ ] [[file:%s][%s]]\n" fname (file-name-nondirectory fname))))
#+END_SRC


In the results above I have marked one entry as completed.

It might be preferrable to have links to places in the file, e.g. to problem 2.
#+BEGIN_SRC emacs-lisp :results output org raw
(require 'find-lisp)

(dolist (fname (find-lisp-find-files "." "\\HW1.org$") nil)
  (princ (format "- [ ] [[file:%s::*2][%s - problem 2]]\n" fname (file-name-nondirectory fname))))
#+END_SRC


We can also create headings with TODO tags. Here I nest the headline under the current headline manually. One benefit of using TODO tags is when you mark them as done there can be a timestamp logged on when you did that.

#+BEGIN_SRC emacs-lisp :results output org raw
(require 'find-lisp)

(dolist (fname (find-lisp-find-files "." "\\HW1.org$") nil)
  (princ (format "*** TODO [[file:%s][%s]]\n" fname (file-name-nondirectory fname))))
#+END_SRC

#+RESULTS:
*** TODO [[file:c:/Users/jkitchin/Dropbox/blogofile-jkitchin.github.com/_blog/org-report/Slim-Shady-HW1.org][Slim-Shady-HW1.org]]
*** DONE [[file:c:/Users/jkitchin/Dropbox/blogofile-jkitchin.github.com/_blog/org-report/John-Doe-HW1.org][John-Doe-HW1.org]]
    CLOSED: [2013-04-30 Tue 08:16]
*** TODO [[file:c:/Users/jkitchin/Dropbox/blogofile-jkitchin.github.com/_blog/org-report/Jim-Vicious-HW1.org][Jim-Vicious-HW1.org]]
*** TODO [[file:c:/Users/jkitchin/Dropbox/blogofile-jkitchin.github.com/_blog/org-report/Ellen-Donnte-HW1.org][Ellen-Donnte-HW1.org]]
