* New publication - Pourbaix Machine Learning Framework Identifies Acidic Water Oxidation Catalysts Exhibiting Suppressed Ruthenium Dissolution
:PROPERTIES:
:categories: news,publication
:date:     2024/06/08 13:43:06
:updated:  2024/06/08 13:43:06
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2024/06/08/New-publication---Pourbaix-Machine-Learning-Framework-Identifies-Acidic-Water-Oxidation-Catalysts-Exhibiting-Suppressed-Ruthenium-Dissolution.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2024/06/08/New-publication---Pourbaix-Machine-Learning-Framework-Identifies-Acidic-Water-Oxidation-Catalysts-Exhibiting-Suppressed-Ruthenium-Dissolution/index.html
:END:

Water splitting is a crucial technology for renewable hydrogen generation. Under acid conditions most metals that would be used for the oxidation reaction tend to dissolve, limiting their utility. Iridium oxide is widely regarded as the most active and stable material, but it is very expensive. Ruthenium oxide is the next most active material, but it is less stable and tends to dissolve over time. In this work we studied 36,000 mixed metal oxides to identify potential compositions that would stabilize ruthenium from dissolution. We found a candidate Ru_{0.6}Cr_{0.2}Ti_{0.2}O_{2} with promise. We synthesized this material anf show that it has superior stability and improved activity compared to RuO_{2}.

#+BEGIN_SRC bibtex
@article{abed-2024-pourb-machin,
  author =	 {Jehad Abed and Javier Heras-Domingo and Rohan Yuri Sanspeur
                  and Mingchuan Luo and Wajdi Alnoush and Debora Motta Meira and
                  Hsiaotsu Wang and Jian Wang and Jigang Zhou and Daojin Zhou
                  and Khalid Fatih and John R. Kitchin and Drew Higgins and
                  Zachary W. Ulissi and Edward H. Sargent},
  title =	 {Pourbaix Machine Learning Framework Identifies Acidic Water
                  Oxidation Catalysts Exhibiting Suppressed Ruthenium
                  Dissolution},
  journal =	 {Journal of the American Chemical Society},
  volume =	 {nil},
  number =	 {nil},
  pages =	 {nil},
  year =	 2024,
  doi =		 {10.1021/jacs.4c01353},
  url =		 {http://dx.doi.org/10.1021/jacs.4c01353},
  DATE_ADDED =	 {Sat Jun 8 13:12:31 2024},
}
#+END_SRC

altmetric:10.1021/jacs.4c01353

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/8nlepsWOxl0?si=a_FR5vDxMkiLsmNk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT
