* Calling remote code-blocks in org-mode
  :PROPERTIES:
  :categories: orgmode,interactive,plotting
  :date:     2016/02/09 20:40:59
  :updated:  2016/02/09 20:40:59
  :END:

We often write code in supporting information files that generates figures or tables in a scientific manuscript. Today, we explore how to call those code blocks remotely but get the output in the file we call it from. We will write code in [[./si.org]] that generates an interactive figure that is presented in this file. We will use data published in citenum:hallenbeck-2015-compar-co2. You can find the data we used in the SI for that paper, or more conveniently [[https://github.com/KitchinHUB/kitchingroup-62][here]].

So, we make a named code block in the [[./si.org]] file called "figure-1". Then we call it like this:

#+BEGIN_EXAMPLE
#+call: si.org:figure-1() :wrap html
#+END_EXAMPLE

That executes the code block in the other file, and wraps the output in an HTML block /in this file/! I do not like my code blocks to execute when I export because they are usually expensive calculations, so I have to manually run the line with C-c C-c, but you can override that behavior with a local setting of org-export-babel-evaluate. So, without further delay, here is the result. Now we have a nice, neat blog post file, with code in an [[./si.org]] file!

#+call: si.org:figure-1() :wrap html

#+RESULTS:
#+BEGIN_html
<iframe id="igraph" scrolling="no" style="border:none;"seamless="seamless" src="https://plot.ly/~jkitchin/6.embed" height="525" width="100%"></iframe>
#+END_html

** References
bibliography:~/Dropbox/bibliography/references.bib
