* DONE Creating bibliographies in other formats with org-ref
  CLOSED: [2014-05-18 Sun 10:11]
  :PROPERTIES:
  :categories: org-mode,bibtex
  :date:     2014/05/18 10:11:18
  :updated:  2014/05/18 11:55:34
  :END:

org-ref automatically generates bibliographies in LaTeX export, and it does a reasonable job automatically generating HTML bibliographies (ox-bibtex probably does this better, but it relies on an external program, whereas this approach is all elisp). Here we illustrate how to generate other formats, e.g. plain text, or org-mode formatted.

org-ref provides a convenient function that generates a bibliography entry for a key formatted according to the variable org-ref-bibliography-entry-format. This variable is a string that uses the reftex percent escapes to create an entry. The default is setup for an HTML entry like this:

#+BEGIN_EXAMPLE
  "%a, %t, <i>%j</i>, <b>%v(%n)</b>, %p (%y). <a href=\"%U\">link</a>. <a href=\"http://dx.doi.org/%D\">doi</a>."
#+END_EXAMPLE

We can redefine it temporarily to get other formats. Here is an example of getting an org-formatted entry with some italics and bold text.

#+BEGIN_SRC emacs-lisp :results value raw 
(let ((org-ref-bibliography-entry-format "%a, %t, /%j/, *%v(%n)*, %p (%y). [[%U][link]]. [[http://dx.doi.org/%D][doi]]."))
(org-ref-get-bibtex-entry-citation "andriotis-2014-infor"))
#+END_SRC

#+RESULTS:
"Andriotis, Mpourmpakis, , Broderick, Rajan, Datta, Somnath, Sunkara \& Menon, Informatics guided discovery of surface  structure-chemistry relationships in catalytic  nanoparticles, /The Journal of Chemical Physics/, *140(9)*, 094705 (2014). [[http://scitation.aip.org/content/aip/journal/jcp/140/9/10.1063/1.4867010][link]]. [[http://dx.doi.org/10.1063/1.4867010][doi]].

Now, we put some citations of various types in for water splitting autocite:mccrory-2013-bench-heter, CO_{2} capture citet:alesi-2012-evaluat-primar, and microfluidic devices cite:voicu-2014-microf-studies. We will convert these links to a bibliography shortly.

Next, we generate an org-formatted bibliography. We will create a bracketed label at the beginning of the entry, and the org-format after that. This is a functional enough bibliography to be useful I think, and it illustrates the ideas. We will do some light transforming to replace escaped & with regular & in the bibliography.

#+BEGIN_SRC emacs-lisp :results value raw
;; temorarily redefine the format
(let ((org-ref-bibliography-entry-format "%a, %t, /%j/, *%v(%n)*, %p (%y). [[%U][link]]. [[http://dx.doi.org/%D][doi]]."))

  (mapconcat 
   (lambda (key)
     (format "[%s] %s" key 
	     (replace-regexp-in-string 
	      "\\\\&" 
	      "&" (org-ref-get-bibtex-entry-citation key))))
   (org-ref-get-bibtex-keys) "\n\n"))
#+END_SRC

#+RESULTS:
[alesi-2012-evaluat-primar] Alesi & Kitchin, Evaluation of a Primary Amine-Functionalized  Ion-Exchange Resin for \ce{CO_2} Capture, /Industrial & Engineering Chemistry Research/, *51(19)*, 6907-6915 (2012). [[http://dx.doi.org/10.1021/ie300452c][link]]. [[http://dx.doi.org/10.1021/ie300452c][doi]].

[mccrory-2013-bench-heter] McCrory, Jung, Peters, Jonas & Jaramillo, Benchmarking Heterogeneous Electrocatalysts for the  Oxygen Evolution Reaction, /J. Am. Chem. Soc./, *135(45)*, 16977--16987 (2013). [[http://dx.doi.org/10.1021/ja407115p][link]]. [[http://dx.doi.org/10.1021/ja407115p][doi]].

[voicu-2014-microf-studies] Voicu, Abolhasani, Choueiri, Rachelle, Lestari, Seiler, , Menard, Greener, Guenther, Axel, Stephan & Kumacheva, Microfluidic Studies of \ce{CO_2} Sequestration by  Frustrated {L}ewis Pairs, /Journal of the American Chemical Society/, *0(0)*, null (2014). [[][link]]. [[http://dx.doi.org/10.1021/ja411601a][doi]].

You can see some minor issues with the formatting, e.g. sometimes the link is empty, if there is no url in the bibtex entry. There is no easy way to fix that. The 0 and null values in the last entry are because that is an ASAP article, and that is what is in the bibtex entry. I do not try to expand the latex code, and do not plan to do that. I do not know why there appears to be a blank author in the last entry, or why the author full names are not used. Those are reftex issues and  low priority to fix for me. They do not exist in the LaTeX export. The main point here is to get a reasonably useful bibliography that you can adapt as you want.


[[bibliography:~/Dropbox/bibliography/references.bib]]





