* New publication - Evaluation of the Degree of Rate Control via Automatic Differentiation
:PROPERTIES:
:categories: news,publication
:date:     2022/03/07 08:40:41
:updated:  2022/03/07 08:40:41
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2022/03/07/New-publication---Evaluation-of-the-Degree-of-Rate-Control-via-Automatic-Differentiation.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2022/03/07/New-publication---Evaluation-of-the-Degree-of-Rate-Control-via-Automatic-Differentiation/index.html
:END:

Determining which steps in a chemical reaction network are important in controlling the reaction rate is challenging. The degree of rate control is a valuable tool for this, but it requires the derivatives of the reaction rate with respect to rate parameters. In many scenarios we do not have an analytical expression for the reaction rate, and even when we do the derivatives may be tedious to derive and implement. In this work, we show how to use automatic differentiation to address this difficulty, enabling straightforward evaluation of the degree of rate control and sensitivity analysis of complex reaction networks.

#+BEGIN_SRC bibtex
@article{yang-2022-evaluat,
  author =	 {Yang, Yilin and Achar, Siddarth K. and Kitchin, John R.},
  title =	 {Evaluation of the degree of rate control via automatic
                  differentiation},
  journal =	 {AIChE Journal},
  volume =	 {n/a},
  number =	 {n/a},
  pages =	 {e17653},
  year =	 2022,
  keywords =	 {catalysis, reaction kinetics},
  doi =		 {10.1002/aic.17653},
  url =		 {https://aiche.onlinelibrary.wiley.com/doi/abs/10.1002/aic.17653},
  eprint =	 {https://aiche.onlinelibrary.wiley.com/doi/pdf/10.1002/aic.17653},
  abstract =	 {Abstract The degree of rate control (DRC) quantitatively
                  identifies the kinetically relevant (sometimes known as
                  rate-limiting) steps of a complex reaction network. This
                  concept relies on derivatives which are commonly implemented
                  numerically, for example, with finite differences (FDs).
                  Numerical derivatives are tedious to implement, and can be
                  problematic, and unstable or unreliable. In this study, we
                  demonstrate the use of automatic differentiation (AD) in the
                  evaluation of the DRC. AD libraries are increasingly available
                  through modern machine learning frameworks. Compared with the
                  FDs, AD provides solutions with higher accuracy with lower
                  computational cost. We demonstrate applications in
                  steady-state and transient kinetics. Furthermore, we
                  illustrate a hybrid local-global sensitivity analysis method,
                  the distributed evaluation of local sensitivity analysis, to
                  assess the importance of kinetic parameters over an uncertain
                  space. This method also benefits from AD to obtain
                  high-quality results efficiently.}
}
#+END_SRC

altmetric:10.1002/aic.17653

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/1bpVL8EQflE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT
