* New publication in SoftwareX
  :PROPERTIES:
  :categories: news, publication
  :date:     2019/07/08 07:15:33
  :updated:  2019/07/08 07:15:33
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2019/07/08/New-publication-in-SoftwareX.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2019/07/08/New-publication-in-SoftwareX/index.html
  :END:

Bibliometrics are increasingly used to quantify scholarly productivity. In this paper, we introduce a Python package called [[https://pypi.org/project/pybliometrics/][pybliometrics]] that provides a scriptable interface to Scopus to aggregate publication data for analysis. The package provides pretty comprehensive coverage of the APIs for author, abstract, affiliation and citation queries. The manuscript shows examples for downloading abstracts in bulk, building collaboration network graphs, and analyzing citation trends. You have to get a key from Scopus to access their databases, and the package provides some guidance on how to get it and configure the package. If you are interested in bibliometrics, this package may be useful to you!


#+BEGIN_SRC bibtex
@article{rose-2019-pybliom,
  author =	 {Michael E. Rose and John R. Kitchin},
  title =	 {Pybliometrics: Scriptable Bibliometrics Using a Python
                  Interface To Scopus},
  journal =	 {SoftwareX},
  volume =	 10,
  number =	 {nil},
  pages =	 100263,
  year =	 2019,
  doi =		 {10.1016/j.softx.2019.100263},
  url =		 {https://doi.org/10.1016/j.softx.2019.100263},
  DATE_ADDED =	 {Mon Jul 8 07:06:58 2019},
}
#+END_SRC

altmetric:10.1016/j.softx.2019.100263
