* DONE New publication in Topics in Catalysis
  CLOSED: [2018-01-27 Sat 16:39]
  :PROPERTIES:
  :categories: news,publication
  :date:     2018/01/27 16:39:35
  :updated:  2018/04/01 18:49:28
  :org-url:  http://kitchingroup.cheme.cmu.edu/org/2018/01/27/New-publication-in-Topics-in-Catalysis.org
  :permalink: http://kitchingroup.cheme.cmu.edu/blog/2018/01/27/New-publication-in-Topics-in-Catalysis/index.html
  :END:

Single atom alloys are alloys in the extreme dilute limit, where single atoms of a reactive metal are surrounded by comparatively unreactive metals. This makes the single reactive atoms like single atom sites where reactions can occur. These sites are interesting because they are metallic, but their electronic structure is different than the atoms in more concentrated alloys. This means there is the opportunity for different, perhaps better catalytic performance for the single atom alloys. In this paper, we studied the electronic structure and some representative reaction pathways on a series of single atom alloy surfaces.

#+BEGIN_SRC bibtex
@article{Thirumalai2018,
  author =	 "Thirumalai, Hari and Kitchin, John R.",
  title =	 "Investigating the Reactivity of Single Atom Alloys Using
                  Density Functional Theory",
  journal =	 "Topics in Catalysis",
  year =	 "2018",
  month =	 "Jan",
  day =		 "25",
  abstract =	 "Single atom alloys are gaining importance as atom-efficient
                  catalysts which can be extremely selective and active towards
                  the formation of desired products. They possess such desirable
                  characteristics because of the presence of a highly reactive
                  single atom in a less reactive host surface. In this work, we
                  calculated the electronic structure of several representative
                  single atom alloys. We examined single atom alloys of gold,
                  silver and copper doped with single atoms of platinum,
                  palladium, iridium, rhodium and nickel in the context of the
                  d-band model of Hammer and N{\o}rskov. The reactivity of these
                  alloys was probed through the dissociation of water and nitric
                  oxide and the hydrogenation of acetylene to ethylene. We
                  observed that these alloys exhibit a sharp peak in their atom
                  projected d-band density of states, which we hypothesize could
                  be the cause of high surface reactivity. We found that the
                  d-band centers and d-band widths of these systems correlated
                  linearly as with other alloys, but that the energy of
                  adsorption of a hydrogen atom on these surfaces could not be
                  correlated with the d-band center, or the average reactivity
                  of the surface. Finally, the single atom alloys, with the
                  exception of copper--palladium showed good catalytic behavior
                  by activating the reactant molecules more strongly than the
                  bulk atom behavior and showing favorable reaction pathways on
                  the free energy diagrams for the reactions investigated.",
  issn =	 "1572-9028",
  doi =		 "10.1007/s11244-018-0899-0",
  url =		 "https://doi.org/10.1007/s11244-018-0899-0"
}
#+END_SRC

altmetric:10.1007/s11244-018-0899-0
