* New publication - Surface Segregation Studies in Ternary Noble Metal Alloys Comparing DFT and Machine Learning with Experimental Data
:PROPERTIES:
:categories: news,publication
:date:     2024/06/06 09:17:13
:updated:  2024/06/06 11:57:57
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2024/06/06/New-publication---Surface-Segregation-Studies-in-Ternary-Noble-Metal-Alloys-Comparing-DFT-and-Machine-Learning-with-Experimental-Data.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2024/06/06/New-publication---Surface-Segregation-Studies-in-Ternary-Noble-Metal-Alloys-Comparing-DFT-and-Machine-Learning-with-Experimental-Data/index.html
:END:

Alloy segregation is hard to model; you need large unit cells to get fine-grained compositions, and /a lot/ of DFT calculations to sample all the possible configurations. The challenge gets even bigger when you consider a ternary alloy, and want to model segregation over the entire ternary alloy composition space, and across multiple surfaces. We tackle this problem in this work using the Open Catalyst Project machine learned potentials (MLPs) that are fine-tuned on a few thousand DFT calculations. We use those MLPs with Monte Carlo simulations to predict segregation on three ternary alloy (111), (110), and (100) surfaces. We compare our predictions to experimental measurements on a polycrystalline CSAF. Similar to previous work of ours, we find qualitative and quantitative agreements in some composition ranges, and disagreement in others. We trace the limitations of quantitative accuracy to limitations in the DFT calculations.

#+BEGIN_SRC bibtex
@article{broderick-2024-surfac-segreg,
  author =	 {Kirby Broderick and Robert A. Burnley and Andrew J. Gellman
                  and John R. Kitchin},
  title =	 {Surface Segregation Studies in Ternary Noble Metal Alloys:
                  Comparing Dft and Machine Learning With Experimental Data},
  journal =	 {ChemPhysChem},
  volume =	 {nil},
  number =	 {nil},
  pages =	 {nil},
  year =	 2024,
  doi =		 {10.1002/cphc.202400073},
  url =		 {http://dx.doi.org/10.1002/cphc.202400073},
  DATE_ADDED =	 {Thu Jun 6 08:37:37 2024},
}
#+END_SRC

altmetric:10.1002/cphc.202400073


#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/x-bCzsn_lmQ?si=oxTCVklbUgr8VwZt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT
