* New publication - High throughput discovery of ternary Cu-Fe-Ru alloy catalysts for photo-driven hydrogen production
:PROPERTIES:
:categories: news,publication
:date:     2023/04/15 08:14:28
:updated:  2023/04/15 08:14:28
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2023/04/15/New-publication---High-throughput-discovery-of-ternary-Cu-Fe-Ru-alloy-catalysts-for-photo-driven-hydrogen-production.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2023/04/15/New-publication---High-throughput-discovery-of-ternary-Cu-Fe-Ru-alloy-catalysts-for-photo-driven-hydrogen-production/index.html
:END:

Finding new ways to make hydrogen with renewable energy and renewable feedstocks using earth abundant materials remains a challenge in catalysis today. Metal nanoparticles are common heterogeneous catalysts for hydrogen production, and their properties can often be improved by using multiple metals at a time. In this work we show a high-throughput experimental approach to discovering a ternary alloy catalyst containing earth abundant metals that is more active at producing hydrogen than any of the pure metals it is made of. It a surprising discovery because these metals are not typically miscible, and they do not form a well characterized material, but rather a distribution of particle sizes and compositions. 

#+BEGIN_SRC bibtex
@article{bhat-2023-high-throug,
  author = {Maya Bhat and Zoe C Simon and Savannah Talledo and Riti Sen and Jacob H. Smith and Stefan Bernhard and Jill E Millstone and John R Kitchin},
  title = {High Throughput Discovery of Ternary Cu-Fe-Ru Alloy Catalysts for Photo-Driven Hydrogen Production},
  journal = {Reaction Chemistry \& Engineering},
  volume = {nil},
  number = {nil},
  pages = {nil},
  year = {2023},
  doi = {10.1039/d3re00059a},
  url = {http://dx.doi.org/10.1039/D3RE00059A},
  DATE_ADDED = {Sat Apr 15 07:55:55 2023},
}
#+END_SRC

altmetric:10.1039/d3re00059a

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/2OXbkIvWkjs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+END_EXPORT
