* New publication - Accelerated Optimization of Pure Metal and Ligand Compositions for Light-driven Hydrogen Production
:PROPERTIES:
:categories: news,publication
:date:     2021/12/03 09:20:05
:updated:  2021/12/03 09:20:05
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2021/12/03/New-publication---Accelerated-Optimization-of-Pure-Metal-and-Ligand-Compositions-for-Light-driven-Hydrogen-Production.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2021/12/03/New-publication---Accelerated-Optimization-of-Pure-Metal-and-Ligand-Compositions-for-Light-driven-Hydrogen-Production/index.html
:END:

In this new collaborative work we show how we combine a high-throughput photoreactor with a design of experiment approach to efficiently find optimal in situ synthesis compositions for making metal nanoparticle catalysts for light-driven hydrogen production.  The challenge in this work is there are several components that interact with each other including metal salts, stabilizing ligands and photosensitizers, as well as some noise in the measurements. It is difficult to optimize these components one at a time, so we use a design of experiment approach. The high-throughput data enables us to explore the composition space around the optimum and to identify specific compositions for focused and expensive characterization efforts. We use this on Au, Cu, Fe and Ni and show that all of them can have high activity when they are independently optimized. It is interesting to note that Au and Cu form stable metallic nanoparticles, but Ni appears to form oxide nanoparticles and Fe appears to form sulfide nanoparticles.

#+BEGIN_SRC bibtex
@article{bhat-2022-accel-optim,
  author =	 {Maya Bhat and Eric Lopato and Zoe C Simon and Jill E Millstone
                  and Stefan Bernhard and John R Kitchin},
  title =	 {Accelerated Optimization of Pure Metal and Ligand Compositions
                  for Light-Driven Hydrogen Production},
  journal =	 {Reaction Chemistry \& Engineering},
  volume =	 {},
  number =	 {},
  pages =	 {},
  year =	 2022,
  doi =		 {10.1039/d1re00441g},
  url =		 {http://dx.doi.org/10.1039/D1RE00441G},
  DATE_ADDED =	 {Mon Nov 29 17:00:12 2021},
}
#+END_SRC

altmetric:10.1039/d1re00441g

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/FdKBwAUAPq4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT
