* DONE New publication in ACS Catalysis on data sharing practices
  CLOSED: [2015-05-17 Sun 14:22]
  :PROPERTIES:
  :categories: news,publication
  :date:     2015/05/17 14:22:54
  :updated:  2015/07/12 18:57:06
  :END:
In this perspective we show an example of data sharing practices we have developed. We use the supporting information file from cite:boes-2015-estim-bulk to show how one can extract the data from our paper and reuse it for new purposes. We illustrate this for both computational and experimental data. We use org-mode for doing this, but we also show that data in the supporting information can be extracted using Python, and independently of Emacs, so that org-mode is not critical for people who do not use it.

#+BEGIN_HTML
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<div class='altmetric-embed' data-doi="10.1021/acscatal.5b00538"></div>
#+END_HTML

#+BEGIN_SRC bibtex
@article{kitchin-2015-examp,
  author =	 {Kitchin, John R.},
  title =	 {Examples of Effective Data Sharing in Scientific Publishing},
  journal =	 {ACS Catalysis},
  volume =	 {5},
  number =	 {6},
  pages =	 {3894-3899},
  year =	 2015,
  doi =		 {10.1021/acscatal.5b00538},
  url =		 { http://dx.doi.org/10.1021/acscatal.5b00538 },
  eprint =	 { http://dx.doi.org/10.1021/acscatal.5b00538 },
}
#+END_SRC

The published version of this manuscript doesn't look exactly like the version I generated, for example, the output from the source blocks is missing. Hopefully that will make it into a supporting information file. Until then, you may be interested in the org file and version I submitted below.

Org source: [[./acs-cat-manuscript.org]]

References: [[./acs-cat-references.bib]]

Manuscript: [[./acs-cat-manuscript-2015-05-07.zip]]


bibliography:../../Dropbox/bibliography/references.bib