* Generating your bibliography in another file
  :PROPERTIES:
  :categories: bibtex
  :date:     2014/10/30 19:42:35
  :updated:  2014/10/30 19:42:35
  :END:

#+latex_class: cmu-article
#+latex_header: \usepackage{bibentry}

It has been proposal season. This particular round of proposals had a requirement to print the references in a separate file from the proposal. Usually I just build a pdf from org-mode, and then manually separate the references. That is not very fun if you have to do it several times. Here we examine a way to avoid this issue by using a new nobibliography link from org-ref with the bibentry LaTeX package.

We wrote this paper cite:mehta-2014-ident-poten and this one cite:xu-2014-relat.

bibliographystyle:unsrt
nobibliography:../../Dropbox/bibliography/references.bib

Here is the resulting pdf, with no references: file:separate-bib.pdf.


** Getting the references in another file
Now, we need to get the reference file. We create a new file, in org-mode, mostly for the convenience of exporting that to a pdf. Here is the code that does that.

#+BEGIN_SRC emacs-lisp
(let* ((base (file-name-sans-extension
	      (file-name-nondirectory (buffer-file-name))))
       (bbl (concat base ".bbl"))
       (orgfile (concat base "-references.org"))
       (pdffile (concat base "-references.pdf")))
  (with-temp-file orgfile
    (insert 
     (format "#+LATEX_CLASS: cmu-article
,#+OPTIONS: toc:nil

,#+BEGIN_LaTeX
\\input{%s}
,#+END_LaTeX
" bbl)))

  (find-file orgfile)
  (org-latex-export-to-pdf)
  (org-open-file pdffile))
#+END_SRC

#+RESULTS:

And, here is the reference file: file:separate-bib-references.pdf

I think this would be integrated into a noexport build section of a document that would generate the pdf and references. 
