** Sorting in python
   :PROPERTIES:
   :categories: python
   :date:     2013/02/27 14:45:26
   :updated:  2013/02/27 14:45:26
   :END:
index:sort
[[http://matlab.cheme.cmu.edu/2011/11/12/sorting-in-matlab/][Matlab post]]

Occasionally it is important to have sorted data. Python has a few sorting options. 

#+BEGIN_SRC python
a = [4, 5, 1, 6, 8, 3, 2]
print a
a.sort()  # inplace sorting
print a

a.sort(reverse=True)
print a
#+END_SRC

#+RESULTS:
: [4, 5, 1, 6, 8, 3, 2]
: [1, 2, 3, 4, 5, 6, 8]
: [8, 6, 5, 4, 3, 2, 1]

If you do not want to modify your list, but rather get a copy of a sorted list, use the sorted command.
#+BEGIN_SRC python
a = [4, 5, 1, 6, 8, 3, 2]
print 'sorted a = ',sorted(a)  # no change to a
print 'sorted a = ',sorted(a, reverse=True)  # no change to a
print 'a        = ',a
#+END_SRC

#+RESULTS:
: sorted a =  [1, 2, 3, 4, 5, 6, 8]
: sorted a =  [8, 6, 5, 4, 3, 2, 1]
: a        =  [4, 5, 1, 6, 8, 3, 2]

This works for strings too:

#+BEGIN_SRC python
a = ['b', 'a', 'c', 'tree']
print sorted(a)
#+END_SRC

#+RESULTS:
: ['a', 'b', 'c', 'tree']

Here is a subtle point though. A capitalized letter comes before a lowercase letter. We can pass a function to the sorted command that is called on each element prior to the sort. Here we make each word lower case before sorting.

#+BEGIN_SRC python
a = ['B', 'a', 'c', 'tree']
print sorted(a)

# sort by lower case letter
print sorted(a, key=str.lower)
#+END_SRC

#+RESULTS:
: ['B', 'a', 'c', 'tree']
: ['a', 'B', 'c', 'tree']

Here is a more complex sorting problem. We have a list of tuples with group names and the letter grade. We want to sort the list by the letter grades. We do this by creating a function that maps the letter grades to the position of the letter grades in a sorted list. We use the list.index function to find the index of the letter grade, and then sort on that.

#+BEGIN_SRC python

groups = [('group1', 'B'),
          ('group2', 'A+'),
          ('group3', 'A')]

def grade_key(gtup):
    '''gtup is a tuple of ('groupname', 'lettergrade')'''
    lettergrade = gtup[1]

    grades = ['A++', 'A+', 'A', 'A-', 'A/B'
              'B+', 'B', 'B-', 'B/C',
              'C+', 'C', 'C-', 'C/D',
              'D+', 'D', 'D-', 'D/R',
              'R+', 'R', 'R-', 'R--']
    
    return grades.index(lettergrade)

print sorted(groups, key=grade_key)
#+END_SRC

#+RESULTS:
: [('group2', 'A+'), ('group3', 'A'), ('group1', 'B')]
