A prototypical example based on our current work is shown in Fig. ref:fig-oxides. In Fig. [[ref:fig-oxides]]-A we show predictions of the relative stabilities of different oxide polymorphs of \ce{SnO2}. Rutile is most stable, but Columbite is close in stability suggesting epitaxial stabilization may be feasible. In Fig. [[ref:fig-oxides]]-B we show computational predictions of a catalytic property for different polymorphs of several metal oxides. The results are not specific to \ce{SnO2} in this example, and are shown to illustrate the approach. In this figure the blue square at the top of the volcano represents the most active polymorph of \ce{IrO2} (Anatase). In Fig [[ref:fig-oxides]]-C we show experimental evidence that Columbite \ce{SnO2} can be synthesized on \ce{CoNb2O6} grains that are oriented in the \([100]\) and \([010]\) directions, but not on grains oriented in the \([001]\) direction, which favors the Rutile structure.

This work will not be limited simply to predictions of stability and activity. We will also develop physics and chemistry based models for these properties based on the electronic structure calculations of the oxides (we have been active in this area for the past five years cite:akhade-2011-effec,akhade-2012-effec,calle-vallejo-2013-number,curnan-2014-effec-concen,xu-2014-relat,xu-2015-accur-u,xu-2015-relat,xu-2015-linear-respon). We will also  consider the reactivity of dopant atoms in "metastable" structures cite:xu-2015-relat. For example, it may not be possible to synthesize pure Anatase \ce{RuO2} or \ce{IrO2}, but it may be possible to grow epitaxially stabilized solid solutions of Anatase \ce{TiO2} and \ce{RuO2} or \ce{IrO2} to achieve superior properties.



* build
  :PROPERTIES:
  :ID:       DA9EC144-39D2-412F-AB7A-69C1259D1F67
  :END:

http://pandoc.org/README.html

#+BEGIN_SRC sh
pandoc -S -o main.docx --filter pandoc-citeproc  --bibliography=references.bib --csl=aip.csl pandoc-footnotes.md
#+END_SRC
*  Bibtex entries			:noexport:

#+BEGIN_SRC text :tangle references.bib
@article{akhade-2011-effec,
  author =	 {Akhade, Sneha A. and Kitchin, John R.},
  title =	 {Effects of Strain, d-Band Filling, and Oxidation State on the
                  Bulk Electronic Structure of Cubic 3d Perovskites},
  journal =	 {The Journal of Chemical Physics},
  volume =	 135,
  number =	 10,
  pages =	 {104702-6},
  year =	 2011,
  url =		 {https://doi.org/10.1063/1.3631948},
  keywords =	 {DESC0004031, early-career, orgmode},
  type =	 {Journal Article},
}



@article{akhade-2012-effec,
  author =	 {Akhade, Sneha and Kitchin, John R.},
  title =	 {Effects of Strain, d-Band Filling, and Oxidation State on the
                  Surface Electronic Structure and Reactivity of 3d Perovskite
                  Surfaces},
  journal =	 {J. Chem. Phys.},
  volume =	 137,
  pages =	 084703,
  year =	 2012,
  doi =		 {10.1063/1.4746117},
  url =
                  {http://scitation.aip.org/content/aip/journal/jcp/137/8/10.1063/1.4746117},
  keywords =	 {DESC0004031, early-career, },
  type =	 {Journal Article},
}



@article{calle-vallejo-2013-number,
  author =	 {Calle-Vallejo, Federico and Inoglu, Nilay G. and Su, Hai-Yan
                  and Martinez, Jose I. and Man, Isabela C. and Koper, Marc
                  T. M. and Kitchin, John R. and Rossmeisl, Jan},
  title =	 {Number of Outer Electrons As Descriptor for Adsorption
                  Processes on Transition Metals and Their Oxides},
  journal =	 {Chemical Science},
  volume =	 4,
  pages =	 {1245-1249},
  year =	 2013,
  doi =		 {10.1039/C2SC21601A},
  url =		 {https://doi.org/10.1039/C2SC21601A},
  keywords =	 {DESC0004031, early-career, },
  abstract =	 {The trends in adsorption energies of the intermediates of the
                  oxygen reduction and evolution reactions on transition metals
                  and their oxides are smoothly captured by the number of outer
                  electrons. This unique descriptor permits the construction of
                  predictive adsorption-energy grids and explains the existence
                  of scaling relationships among these compounds.},
  issue =	 3,
  publisher =	 {The Royal Society of Chemistry},
}



@article{curnan-2014-effec-concen,
  author =	 {Curnan, Matthew T. and Kitchin, John R.},
  title =	 {Effects of Concentration, Crystal Structure, Magnetism, and
                  Electronic Structure Method on First-Principles Oxygen Vacancy
                  Formation Energy Trends in Perovskites},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 118,
  number =	 49,
  pages =	 {28776-28790},
  year =	 2014,
  doi =		 {10.1021/jp507957n},
  url =		 {https://doi.org/10.1021/jp507957n},
  keywords =	 {orgmode},
  eprint =	 { https://doi.org/10.1021/jp507957n },
}



@article{xu-2014-relat,
  author =	 {Zhongnan Xu and John R. Kitchin},
  title =	 {Relating the Electronic Structure and Reactivity of the 3d
                  Transition Metal Monoxide Surfaces},
  journal =	 {Catalysis Communications},
  volume =	 52,
  pages =	 {60-64},
  year =	 2014,
  doi =		 {10.1016/j.catcom.2013.10.028},
  url =		 {https://doi.org/10.1016/j.catcom.2013.10.028},
  keywords =	 {DESC0004031, early-career, orgmode, },
  issn =	 "1566-7367",
  abstract =	 "Abstract We performed a series of density functional theory
                  calculations of dissociative oxygen adsorption on fcc metals
                  and their corresponding rocksalt monoxides to elucidate the
                  relationship between the oxide electronic structure and its
                  corresponding reactivity. We decomposed the dissociative
                  adsorption energy of oxygen on an oxide surface into a sum of
                  the adsorption energy on the metal and a change in adsorption
                  energy caused by both expanding and oxidizing the lattice. We
                  were able to identify the key features of the electronic
                  structure that explains the trends in adsorption energies on
                  3d transition metal monoxide surfaces. ",
}



@article{xu-2015-accur-u,
  author =	 "Xu, Zhongnan and Joshi, Yogesh V. and Raman, Sumathy and
                  Kitchin, John R.",
  title =	 {Accurate Electronic and Chemical Properties of 3d Transition
                  Metal Oxides Using a Calculated Linear Response {U} and a {DFT
                  + U(V)} Method},
  journal =	 "The Journal of Chemical Physics",
  volume =	 142,
  number =	 14,
  pages =	 144701,
  year =	 2015,
  doi =		 {10.1063/1.4916823},
  url =
                  "http://scitation.aip.org/content/aip/journal/jcp/142/14/10.1063/1.4916823",
  keywords =	 {DESC0004031, c orgmode},
  eid =		 144701,
}



@article{xu-2015-relat,
  author =	 {Zhongnan Xu and John R. Kitchin},
  title =	 {Relationships Between the Surface Electronic and Chemical
                  Properties of Doped 4d and 5d Late Transition Metal Dioxides},
  keywords =	 {orgmode},
  journal =	 {The Journal of Chemical Physics},
  volume =	 142,
  number =	 10,
  pages =	 104703,
  year =	 2015,
  doi =		 {10.1063/1.4914093},
  url =		 {https://doi.org/10.1063/1.4914093},
  date_added =	 {Sat Oct 24 10:57:22 2015},
}



@article{xu-2015-linear-respon,
  author =	 {Xu, Zhongnan and Rossmeisl, Jan and Kitchin, John R.},
  title =	 {A Linear Response {DFT}+{U} Study of Trends in the Oxygen
                  Evolution Activity of Transition Metal Rutile Dioxides},
  journal =	 {The Journal of Physical Chemistry C},
  volume =	 119,
  number =	 9,
  pages =	 {4827-4833},
  year =	 2015,
  doi =		 {10.1021/jp511426q},
  url =		 { https://doi.org/10.1021/jp511426q },
  keywords =	 {DESC0004031, early-career, orgmode, },
  eprint =	 { https://doi.org/10.1021/jp511426q },
}

#+END_SRC
