* DONE New publication in International Journal of Quantum Chemistry
  CLOSED: [2016-03-03 Thu 13:48]
  :PROPERTIES:
  :categories: news,publication
  :date:     2016/03/03 13:48:01
  :updated:  2016/03/03 13:58:22
  :END:
It is well known that DFT calculations are expensive, which limits the size of the calculations that can be performed, the number of them that can be performed, and their use in simulation methods such as molecular dynamics.  Molecular potentials are more suitable for these types of simulations, but they must be parameterized by some means. In this paper, we use a database of DFT calculations to train ReaxFF and a neural network potential. We compare and contrast these potentials with respect to their accuracy, trainability, and speed of calculation with application to properties of Au bulk, cluster and surface properties. There are clear tradeoffs with these two approaches, but both have advantages for different purposes. Congratulations Jake and Mitch! See the paper here: https://doi.org/10.1002/qua.25115.

#+BEGIN_SRC bibtex
@article {boes-2016-neural-reaxf,
  author =	 {Boes, Jacob R. and Groenenboom, Mitchell C. and Keith, John A.
                  and Kitchin, John R.},
  title =	 {Neural network and ReaxFF comparison for Au properties},
  journal =	 {International Journal of Quantum Chemistry},
  issn =	 {1097-461X},
  url =		 {https://doi.org/10.1002/qua.25115},
  doi =		 {10.1002/qua.25115},
  pages =	 {n/a--n/a},
  keywords =	 {Kohn-Sham density functional theory, neural networks, reactive
                  force fields, potential energy surfaces, machine learning},
  year =	 2016,
}
#+END_SRC

#+BEGIN_HTML
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<div data-badge-type='medium-donut' class='altmetric-embed' data-badge-details='right' data-doi='10.1002/qua.25115'></div>
#+END_HTML

