* DONE Writing scripts in Emacs-lisp
  CLOSED: [2014-08-06 Wed 14:27]
  :PROPERTIES:
  :date:     2014/08/06 14:27:58
  :updated:  2014/08/06 14:30:27
  :categories: emacs
  :END:

I have written lots of script commands, mostly in Python, occasionally in bash. Today I learned you can also write them in emacs-lisp (http://www.emacswiki.org/emacs/EmacsScripts). There is an interesting wrinkle on the first line which specifies how to run the command, which is explained in the emacswiki page.

Here is an example script that just prints some information about Emacs and the command line args you pass to it. We use some Local variables at the end to make the script open in emacs-lisp mode for editing. $0 in shell language is the name of the script being run, so the header here simply loads the script into emacs, and then runs the main function. 

#+BEGIN_SRC emacs-lisp :tangle test.el
:;exec emacs -batch -l "$0" -f main "$@"

(defun main ()
  (print (version))
  (print (format "I did it. you passed in %s" command-line-args-left)))

;; Local Variables:
;; mode: emacs-lisp
;; End:
#+END_SRC

We need to tangle this code block to get the script. 
elisp:org-babel-tangle

Since we do not have a regular shebang, we manually change the mode to make it executable, and then call the script with some arguments.

#+BEGIN_SRC sh
chmod +x test.el
./test.el arg1 arg2 
#+END_SRC

#+RESULTS:
: 
: "GNU Emacs 22.1.1 (mac-apple-darwin)
:  of 2014-06-05 on osx105.apple.com"
: 
: "I did it. you passed in (arg1 arg2)"

Hahah! I guess the emacs on my path is an old one! Ironically, the Emacs I am writing in is much more modern (but not on the path).

#+BEGIN_SRC emacs-lisp
(version)
#+END_SRC

#+RESULTS:
: GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36)
:  of 2013-03-13 on bob.porkrind.org


And it is evidence I wrote this on a Mac. First Mac post ever.
