* New publication - Integrated systems-To-Atoms (S2A) Framework for Designing Resilient and Efficient Hydrogen Infrastructure Solutions
:PROPERTIES:
:categories: news, publication
:date:     2025/02/04 07:19:06
:updated:  2025/02/04 07:19:06
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2025/02/04/New-publication---Integrated-systems-To-Atoms-(S2A)-Framework-for-Designing-Resilient-and-Efficient-Hydrogen-Infrastructure-Solutions.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2025/02/04/New-publication---Integrated-systems-To-Atoms-(S2A)-Framework-for-Designing-Resilient-and-Efficient-Hydrogen-Infrastructure-Solutions/index.html
:END:

The future of hydrogen infrastructure demands seamless integration of technology performance, operating conditions, and system configuration. This paper introduces a Systems-to-Atoms (S2A) framework, bridging material, device, and system design to optimize hydrogen storage and transport. A case study on using liquid organic hydrogen carriers (LOHCs) for refueling stations demonstrates that high reaction pressures, while not enhancing catalyst performance, can significantly reduce system costs. Interestingly, less efficient catalysts like copper may be preferred over palladium in certain conditions due to cost and supply chain considerations. The study highlights the importance of cross-scale optimization for resilient, cost-effective hydrogen solutions.

#+BEGIN_SRC bibtex
@article{yuan-2025-integ-to,
  author =	 {Mengyao Yuan and Giovanna Bucci and Tanusree Chatterjee and
                  Shyam Deo and John R. Kitchin and Carl D. Laird and Wenqin Li
                  and Thomas Moore and Corey Myers and Wenyu Sun and Ethan M.
                  Sunshine and Bo-Xun Wang and Matthew J. McNenly and Sneha A.
                  Akhade},
  title =	 {Integrated <i>systems-To-Atoms</i> (S2A) Framework for
                  Designing Resilient and Efficient Hydrogen Infrastructure
                  Solutions},
  journal =	 {Energy \& Fuels},
  volume =	 {nil},
  number =	 {nil},
  pages =	 {nil},
  year =	 2025,
  doi =		 {10.1021/acs.energyfuels.4c05903},
  url =		 {http://dx.doi.org/10.1021/acs.energyfuels.4c05903},
  DATE_ADDED =	 {Mon Feb 3 15:30:53 2025},
}
#+END_SRC

altmetric:10.1021/acs.energyfuels.4c05903

#+BEGIN_EXPORT html
<iframe title="Embed Player" src="https://play.libsyn.com/embed/episode/id/35135455/height/192/theme/modern/size/large/thumbnail/yes/custom-color/008080/time-start/00:00:00/hide-show/yes/hide-playlist/yes/hide-subscribe/yes/hide-share/yes/font-color/ffffff" height="192" width="100%" scrolling="no" allowfullscreen="" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true" style="border: none;"></iframe>
#+END_EXPORT
