* 10 years ago - org mode is awesome video
:PROPERTIES:
:date:     2024/07/04 07:52:26
:updated:  2024/07/04 07:53:03
:org-url:  https://kitchingroup.cheme.cmu.edu/org/2024/07/04/10-years-ago---org-mode-is-awesome-video.org
:permalink: https://kitchingroup.cheme.cmu.edu/blog/2024/07/04/10-years-ago---org-mode-is-awesome-video/index.html
:categories: org-mode
:END:

Ten years ago I posted a video on YouTube titled "org mode is awesome". This 18 minute video was a tour of features in org-mode that ranged included, outlining, task management, agendas, tables, code, exporting to different formats, and extendability. That video has been viewed 92.9K times!

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/fgizHHd7nOo?si=YtXo7_4jyxQh90AG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_EXPORT

A fair bit has changed since then, and a lot has stayed the same. org-mode is even more awesome! That video was made with what I called at the time ~jmax~, and that has evolved into ~scimax~ today. I use ~scimax~ on a daily basis in my research, teaching and other work. It is as important in my work today as it was 10 years ago, and has survived watching other editors come and go.

I have had in mind to make an update of that video, but it has in my opinion really stood the test of time and is still highly relevant in its present form. The only thing that would really change is the background and font colors. 

I have made over 200 other YouTube videos over that time, and many of them are on using Emacs and org-mode in a lot of different ways. These videos are organized in these playlists:

- [[https://www.youtube.com/playlist?list=PL0sMmOaE_gs1Ox-wIIbHPLZ9O5uLJ_rQW][scimax-eln]] :: Using scimax as an electronic lab notebook.
- [[https://www.youtube.com/playlist?list=PL0sMmOaE_gs3E0OjExoI7vlCAVygj6S4I][scimax]] :: Videos on libraries I developed in scimax, including org-ref
- [[https://www.youtube.com/playlist?list=PL0sMmOaE_gs3GbuZV_sNjwMREw9rfElTV][org-mode]] :: Videos exploring features in org-mode
- [[https://www.youtube.com/playlist?list=PL0sMmOaE_gs2yzwy54kLZk5c1ZH-Nh-62][pycse]] :: Videos on using Python in Emacs to solve engineering and science problems

You can see how ~scimax~ has evolved, and continues to evolve over this time through these videos, and of course through the ~scimax~ repo at https://github.com/jkitchin/scimax. There are still great things coming for ~scimax~, stay tuned!
