#+latex_class: cmu-article
#+Latex_class_options: [12pt]
#+OPTIONS: toc:nil ^:{}

The idea here is to have an entire NSF proposal in an org file, with each section getting converted to the right kind of file, properly named.

* Summary
  :PROPERTIES:
  :EXPORT_FILE_NAME: project-summary
  :END:

*overview* big picture

*Intellectual Merit* It is wonderful what we do

*Broader Impact* It will shake the universe.


bibliography:../../../Dropbox/bibliography/references.bib
* Project description
  :PROPERTIES:
  :EXPORT_FILE_NAME: project-description
  :END:
** Introduction
a citation cite:mehta-2014-ident-poten.  cite:mehta-2014-ident-poten

** Proposal
some stuff.

\newpage
bibliographystyle:unsrtnat
nobibliography:/Users/jkitchin/Dropbox/bibliography/references.bib
* References
  :PROPERTIES:
  :EXPORT_FILE_NAME: references
  :END:

#+BEGIN_LaTeX
  \input{project-description.bbl}
#+END_LaTeX
* Biosketch
I wish
* Current and Pending
  I wish
* Facilities
  :PROPERTIES:
  :EXPORT_FILE_NAME: facilities
  :END:
We have stuff

* Data management plan
  :PROPERTIES:
  :EXPORT_FILE_NAME: data-management
  :END:
We make and store data.

* Mentoring plan
  :PROPERTIES:
  :EXPORT_FILE_NAME: mentoring-plan
  :END:
We do not need one.

* build					:noexport:

#+BEGIN_SRC emacs-lisp
(org-map-entries
 (lambda ()
   (when (org-entry-get (point) "EXPORT_FILE_NAME")
     (save-restriction
       (org-narrow-to-subtree)
       (ox-manuscript-export-and-build-and-open nil t)))))
#+END_SRC

#+RESULTS:

